[master]update punch scripts of attachment and detachment
openmainframeproject/feilong pull request #372
Opened 2020-10-29 09:58 UTC by SharpRazor

1. add more comments to explain the function of commands
2. fix issue#4191 and issue#4195, these 2 issues are because
   user_friendly_names set to yes, and the parameter of multipath -f
   should be map name instead of wwid. and if the user_friendly_names
   set to no, it still can work.

Signed-off-by: SharpRazor <bjcb@cn.ibm.com>

2020-10-30 02:57 UTC, bjhuangr commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +AutoScan=`cat /sys/module/zfcp/parameters/allow_lun_scan`
same with `AutoLunScan` ?

2020-10-30 03:05 UTC, SharpRazor commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +AutoScan=`cat /sys/module/zfcp/parameters/allow_lun_scan`
you mean AutoPortScan same with AutoLunScan? you can fresh webpage, I noticed yesterday , they should be different now.

2020-10-30 04:31 UTC, jackydalong commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +    map_name=(`multipath -ll | grep $WWID | awk '{print $1}'`)
grep $WWID => grep -i $WWID

2020-10-30 04:36 UTC, jackydalong commented
The code file names start with 'rhel7_xxxxxx.j2'.   Are they only for RHEL7 ?
If so, we should add another two corresponding files with prefix "rhel8_xxxxx.j2"for RHEL8

2020-10-30 04:54 UTC, SharpRazor commented
> The code file names start with 'rhel7_xxxxxx.j2'. Are they only for RHEL7 ?
> If so, we should add another two corresponding files with prefix "rhel8_xxxxx.j2"for RHEL8

from the origin, I created new files rhel8_xxx, but it is not good for your review. so I deleted them.
when you completed the review and it passed the test. I can change the names of them to rhel8 or something else.

2020-10-30 06:25 UTC, SharpRazor commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +    map_name=(`multipath -ll | grep $WWID | awk '{print $1}'`)
done.

2020-10-30 09:00 UTC, jackydalong requested changes
Please change

2020-10-30 09:00 UTC, jackydalong commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +    multipath -f $map_name
1. "flush devmap name" only needs doing once, so it is better to be moved out of the loop.
2. need to check whether the cmd succeed; eg :
```shell
# if success then continue the following actions
   [root@rhel82-xfs-eckd ~]# multipath -f mpathb ; echo $?
   0

# if fail, stop following actions
   [root@rhel82-xfs-eckd ~]# df -h /mnt
   Filesystem           Size  Used Avail Use% Mounted on
   /dev/mapper/mpathb1  991M  2.6M  922M   1% /mnt   >>>>>----|
                                                              |
   [root@rhel82-xfs-eckd ~]# multipath -f mpathb ; echo $?    |
   Oct 30 04:47:34 | mpathb1: map in use                      |
   1                        <<<<<<<<<<<<<<<<<-----------------|
```

2020-10-30 09:00 UTC, jackydalong commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +    map_name=(`multipath -ll | grep -i $WWID | awk '{print $1}'`)
Use below method to get devmap name only/
```shell
# multipath -h
  -v lvl  verbosity level:
          . 0 no output
          . 1 print created devmap names only  <<<<<
          . 2 default verbosity
          . 3 print debug information   
          
# user_friendly_names yes                              
[root@rhel82-xfs-eckd ~]# multipath -l 3600507640083826de000000000000cf6 -v1
mpathb                          

#user_friendly_names no
[root@rhel82-xfs-eckd ~]# multipath -l 3600507640083826de000000000000cf6 -v1
3600507640083826de000000000000cf6
```

2020-10-30 09:23 UTC, SharpRazor commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +    multipath -f $map_name
great comments, I will fix it.

2020-10-30 09:54 UTC, SharpRazor commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +    map_name=(`multipath -ll | grep $WWID | awk '{print $1}'`)
@jackydalong done.

2020-10-30 09:55 UTC, SharpRazor commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +    multipath -f $map_name
done.

2020-10-30 09:55 UTC, SharpRazor commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +    map_name=(`multipath -ll | grep -i $WWID | awk '{print $1}'`)
done.

2020-10-30 10:09 UTC, jackydalong commented on zvmsdk/volumeops/templates/rhel7_attach_volume.j2
> +NPIV=`cat /sys/bus/ccw/drivers/zfcp/0.0.$fcp/$HostName/fc_host/$HostName/port_type`
HostName is not defined !

2020-11-02 02:42 UTC, SharpRazor commented on zvmsdk/volumeops/templates/rhel7_attach_volume.j2
> +NPIV=`cat /sys/bus/ccw/drivers/zfcp/0.0.$fcp/$HostName/fc_host/$HostName/port_type`
got it, done.

2020-11-02 02:45 UTC, SharpRazor commented
add rhel8_attach/detach_volume.j2 now to fit rhel8. remove `chzdev` command in rhel7_attach/detach_volume.j2.

2020-11-05 09:09 UTC, SharpRazor commented
test results(2 FCPs, 2 punch devol.sh):

first one:
```
[root@rhel78 ~]# bash devol.sh
get source device path:ccw-0.0.5c07-zfcp-0x5005076802400c1a:0x0000000000000000
scsi_id get WWID:36005076802880052a0000000000044ae
get map name: 36005076802880052a0000000000044ae
output of multipath -f:
exit code for multipath -f: 0
get SdxName: sdb
remove WWPN 0x5005076802400c1a in zfcp.conf
remove WWPN 0x5005076802400c1b in zfcp.conf
```

second one:

```
[root@rhel78 ~]# bash devol.sh
get source device path:ccw-0.0.5d0a-zfcp-0x5005076802400c1a:0x0000000000000000
scsi_id get WWID:36005076802880052a0000000000044ae
get map name:
output of multipath -f: Nov 05 03:54:25 | must provide a map name to remove
ignore error on FCP 5d0a and Lun 0x0000000000000000:Nov 05 03:54:25 | must provide a map name to remove
exit code for multipath -f: 0
get SdxName: sdd
remove WWPN 0x5005076802400c1a in zfcp.conf
remove WWPN 0x5005076802400c1b in zfcp.conf
```

2020-11-06 07:15 UTC, dongyanyang approved these changes

2020-11-06 07:15 UTC, dongyanyang commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +exit_code=$?
this exit_code would always be 0

2020-11-06 07:17 UTC, SharpRazor commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +exit_code=$?
oh...yes. I will remove the echo line.

2020-11-06 07:19 UTC, SharpRazor commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +exit_code=$?
done.

2020-11-06 08:34 UTC, bjhuangr approved these changes

2020-11-06 08:34 UTC, merged