[WIP][master]add error capture mechanism in zvmguestconfigure
openmainframeproject/feilong pull request #386
Opened 2020-12-03 05:34 UTC by SharpRazor

if zvmguestconfigure failed when executing attach/detach scripts, will raise exceptions.

Signed-off-by: SharpRazor <bjcb@cn.ibm.com>

2020-12-03 05:40 UTC, jichenjc commented on zvmsdk/volumeop.py
> +            msg = ('Attach scripts execute results: %s' % ret)
can we know the reason about failure when this error occur? 
can we get some detailed description print or log ?

2020-12-15 13:18 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +            msg = ('Attach scripts execute results: %s' % ret)
yes, I still work on this to got the reason and detailed description. i am still working on the zvmguestconfigure to return exit code, when it is done, I will print log considering the exit codes.

2020-12-21 08:53 UTC, dongyanyang requested changes
suggest to hold this change

2020-12-21 08:53 UTC, dongyanyang commented on tools/share/zvmguestconfigure
> +      exit_code=$?
there will be not only one shell file punched,  several exit_code, how to combine?

2020-12-21 08:53 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                raise exception.SDKVolumeOperationError(rs=8,
Need to rework on the rollback.
Previously we don't expect the config_detach or config_attach stage would report any exception.

2020-12-21 08:59 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +                raise exception.SDKVolumeOperationError(rs=8,
the config_attach is in _add_disk, so if exception raised, _add_disk can capture it.

2020-12-21 09:01 UTC, SharpRazor commented on tools/share/zvmguestconfigure
> +      exit_code=$?
there is only one script processed at same time. only one succeed then go ahead to next.

2020-12-22 04:37 UTC, SharpRazor commented
/hold this, will try to merge it next cycle.

2021-03-18 06:01 UTC, dongyanyang requested changes

2021-03-18 06:01 UTC, dongyanyang commented on zvmsdk/volumeops/templates/rhel8_attach_volume.j2
>  if [ -z "$enable_multipath_mod" ];then
line 125 - line 149:
I think we don't need to manually control the udev urules for rhel8.

we can just use 
```
chzdev -e -a zfcp-host 0.0.$fcp  
chzdev -e -a zfcp-lun 0.0.$fcp:$wwpn:$lun 
```
which will automatically generate the udev rules.

and also line 52-55 can be removed.

2021-03-22 11:39 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +                if exit_code == 1:
from my test, because of code:
```
if i == path_count - 1:
   need_restart = True
```
only when the last script punched, zvmguestconfigure  download and execute the scripts.
And will will return the exit code of the last downloaded script.

this will be enhanced in future PR. It is in plan.

2021-03-22 11:40 UTC, SharpRazor commented on zvmsdk/volumeops/templates/rhel7_attach_volume.j2
done.

2021-03-22 11:42 UTC, SharpRazor commented on zvmsdk/volumeops/templates/rhel8_attach_volume.j2
>  if [ -z "$enable_multipath_mod" ];then
just as your suggestion, I will commit a separated PR for this.

2021-03-22 12:06 UTC, SharpRazor commented
### before restart (1 root volume and 2 data volumes):
```
[root@rhel82-scsi ~]# multipath -l
mpathe (3600507640083826de000000000003a75) dm-0 IBM,2145
size=10G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=0 status=active
| |- 0:0:3:0  sda  8:0    active undef running
| |- 0:0:4:0  sdb  8:16   active undef running
| |- 1:0:3:0  sdf  8:80   active undef running
| |- 1:0:8:0  sde  8:64   active undef running
| |- 2:0:7:0  sdi  8:128  active undef running
| `- 2:0:8:0  sdl  8:176  active undef running
`-+- policy='service-time 0' prio=0 status=enabled
  |- 0:0:10:0 sdd  8:48   active undef running
  |- 0:0:9:0  sdc  8:32   active undef running
  |- 1:0:6:0  sdh  8:112  active undef running
  |- 1:0:7:0  sdg  8:96   active undef running
  |- 2:0:3:0  sdj  8:144  active undef running
  `- 2:0:4:0  sdk  8:160  active undef running
mpathb (3600507640083826de000000000003a73) dm-3 IBM,2145
size=1.0G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=0 status=active
| |- 0:0:3:1  sdm  8:192  active undef running
| |- 0:0:4:1  sdo  8:224  active undef running
| |- 1:0:3:1  sdu  65:64  active undef running
| |- 1:0:8:1  sdaa 65:160 active undef running
| |- 2:0:7:1  sdag 66:0   active undef running
| `- 2:0:8:1  sdai 66:32  active undef running
`-+- policy='service-time 0' prio=0 status=enabled
  |- 0:0:9:1  sdq  65:0   active undef running
  |- 0:0:10:1 sds  65:32  active undef running
  |- 1:0:6:1  sdw  65:96  active undef running
  |- 1:0:7:1  sdy  65:128 active undef running
  |- 2:0:3:1  sdac 65:192 active undef running
  `- 2:0:4:1  sdae 65:224 active undef running
mpatha (3600507640083826de000000000003a74) dm-2 IBM,2145
size=1.0G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=0 status=active
| |- 0:0:9:2  sdr  65:16  active undef running
| |- 0:0:10:2 sdt  65:48  active undef running
| |- 1:0:6:2  sdx  65:112 active undef running
| |- 1:0:7:2  sdz  65:144 active undef running
| |- 2:0:3:2  sdad 65:208 active undef running
| `- 2:0:4:2  sdaf 65:240 active undef running
`-+- policy='service-time 0' prio=0 status=enabled
  |- 0:0:3:2  sdn  8:208  active undef running
  |- 0:0:4:2  sdp  8:240  active undef running
  |- 1:0:3:2  sdv  65:80  active undef running
  |- 1:0:8:2  sdab 65:176 active undef running
  |- 2:0:8:2  sdaj 66:48  active undef running
  `- 2:0:7:2  sdah 66:16  active undef running
```

### after restart:
```
[root@rhel82-scsi ~]# multipath -l
mpathe (3600507640083826de000000000003a75) dm-0 IBM,2145
size=10G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=0 status=active
| |- 0:0:0:0  sdb  8:16   active undef running
| |- 0:0:8:0  sde  8:64   active undef running
| |- 1:0:0:0  sda  8:0    active undef running
| |- 1:0:10:0 sdq  65:0   active undef running
| |- 2:0:4:0  sdy  65:128 active undef running
| `- 2:0:5:0  sdab 65:176 active undef running
`-+- policy='service-time 0' prio=0 status=enabled
  |- 0:0:10:0 sdk  8:160  active undef running
  |- 0:0:5:0  sdf  8:80   active undef running
  |- 1:0:8:0  sdr  65:16  active undef running
  |- 1:0:9:0  sdp  8:240  active undef running
  |- 2:0:7:0  sdae 65:224 active undef running
  `- 2:0:8:0  sdah 66:16  active undef running
mpathb (3600507640083826de000000000003a73) dm-1 IBM,2145
size=1.0G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=0 status=active
| |- 0:0:0:1  sdc  8:32   active undef running
| |- 0:0:8:1  sdi  8:128  active undef running
| |- 1:0:0:1  sdn  8:208  active undef running
| |- 1:0:10:1 sdw  65:96  active undef running
| |- 2:0:4:1  sdz  65:144 active undef running
| `- 2:0:5:1  sdac 65:192 active undef running
`-+- policy='service-time 0' prio=0 status=enabled
  |- 0:0:10:1 sdl  8:176  active undef running
  |- 0:0:5:1  sdg  8:96   active undef running
  |- 1:0:8:1  sds  65:32  active undef running
  |- 1:0:9:1  sdu  65:64  active undef running
  |- 2:0:7:1  sdaf 65:240 active undef running
  `- 2:0:8:1  sdai 66:32  active undef running
mpatha (3600507640083826de000000000003a74) dm-2 IBM,2145
size=1.0G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=0 status=active
| |- 0:0:10:2 sdm  8:192  active undef running
| |- 0:0:5:2  sdh  8:112  active undef running
| |- 1:0:8:2  sdt  65:48  active undef running
| |- 1:0:9:2  sdv  65:80  active undef running
| |- 2:0:7:2  sdag 66:0   active undef running
| `- 2:0:8:2  sdaj 66:48  active undef running
`-+- policy='service-time 0' prio=0 status=enabled
  |- 0:0:0:2  sdd  8:48   active undef running
  |- 0:0:8:2  sdj  8:144  active undef running
  |- 1:0:0:2  sdo  8:224  active undef running
  |- 1:0:10:2 sdx  65:112 active undef running
  |- 2:0:4:2  sdaa 65:160 active undef running
  `- 2:0:5:2  sdad 65:208 active undef running
[root@rhel82-scsi ~]# 

```

2021-04-01 07:06 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                pattern = '(?<=status=)([1-9]+)'
Not sure whether the pattern would work for ubuntu/sles, technichly should be fine. but better to test.

2021-04-01 07:29 UTC, dongyanyang commented on zvmsdk/volumeops/templates/rhel7_attach_volume.j2
> +for j in ${ActiveWWPNs[@]}
why would you remove the sleep loop?
The disk is not always show up immediately.

2021-04-01 07:29 UTC, dongyanyang commented on zvmsdk/volumeops/templates/rhel8_attach_volume.j2
> +for j in ${ActiveWWPNs[@]}
ditto

2021-04-01 07:46 UTC, SharpRazor commented on zvmsdk/volumeops/templates/rhel7_attach_volume.j2
> +for j in ${ActiveWWPNs[@]}
I found that `echo - - -` will let the devices show up.

2021-04-02 03:25 UTC, SharpRazor commented on zvmsdk/volumeops/templates/rhel7_attach_volume.j2
> +for j in ${ActiveWWPNs[@]}
will add a sleep loop to wait the devices ready.

2021-04-02 06:50 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +                pattern = '(?<=status=)([1-9]+)'
for UBUNTU, this doesn't work:
```
dummyuser@ubuntu20:~$ systemctl status zvmguestconfigure
● zvmguestconfigure.service - Activation engine for configuring zLinux os when it start up
     Loaded: loaded (/lib/systemd/system/zvmguestconfigure.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Fri 2021-04-02 02:46:26 UTC; 4h 2min ago
   Main PID: 28406 (code=exited, status=0/SUCCESS)

Apr 02 02:46:25 ubuntu20 zvmguestconfigure[28747]: Note: You can use --force to override safety checks (*)
Apr 02 02:46:25 ubuntu20 zvmguestconfigure[28752]: zFCP LUN 0.0.1d11:0x500507680d060027:0x0000000000000000 already deconfigured
Apr 02 02:46:25 ubuntu20 zvmguestconfigure[28753]: zFCP LUN 0.0.1d11:0x500507680d120027:0x0000000000000000 already deconfigured
Apr 02 02:46:25 ubuntu20 zvmguestconfigure[28754]: zFCP LUN 0.0.1d11:0x500507680d760027:0x0000000000000000 already deconfigured
Apr 02 02:46:25 ubuntu20 zvmguestconfigure[28755]: zFCP LUN 0.0.1d11:0x500507680d820027:0x0000000000000000 already deconfigured
Apr 02 02:46:25 ubuntu20 zvmguestconfigure[28756]: FCP device 0.0.1d11 deconfigured
Apr 02 02:46:25 ubuntu20 zvmguestconfigure[28761]: sed: can't read /etc/udev/rules.d/56-zfcp.rules: No such file or directory
Apr 02 02:46:25 ubuntu20 zvmguestconfigure[28406]: zvmguestconfigure has successfully processed the reader files.
Apr 02 02:46:26 ubuntu20 systemd[1]: zvmguestconfigure.service: Succeeded.
Apr 02 02:46:26 ubuntu20 systemd[1]: Finished Activation engine for configuring zLinux os when it start up.
dummyuser@ubuntu20:~$
```
I will find another way to get exit code.

2021-04-02 06:51 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +                pattern = '(?<=status=)([1-9]+)'
I think `Main PID` string will suitable.

2021-04-02 09:02 UTC, SharpRazor commented on zvmsdk/volumeops/templates/rhel8_attach_volume.j2
> +for j in ${ActiveWWPNs[@]}
done, please help review again.

2021-04-02 09:11 UTC, dongyanyang approved these changes
lgtm. @SharpRazor please rebase, then we can merge

2021-04-06 02:13 UTC, merged