add partprobe before retry getting devNode
openmainframeproject/feilong pull request #430
Opened 2021-03-04 05:00 UTC by SharpRazor

Signed-off-by: SharpRazor <bjcb@cn.ibm.com>

2021-03-04 05:01 UTC, SharpRazor commented
@dongyanyang @jackydalong @bjhuangr please help review, thanks.

2021-03-05 03:45 UTC, SharpRazor commented
@jackydalong

2021-03-05 03:56 UTC, dongyanyang requested changes

2021-03-05 03:56 UTC, dongyanyang commented on zthin-parts/zthin/bin/refresh_bootmap
>      sleepTimes=".001 .01 .1 .5 1 2 3 5 8 15 22 34 60 90 120"
move line 413 and 414 after line 420.

2021-03-05 03:56 UTC, dongyanyang commented on zthin-parts/zthin/bin/refresh_bootmap
> +    devPath="/dev/mapper/$map_name"
before using map_name, better to check last ( rc -eq 0 ) and map_name is not null.

2021-03-05 03:56 UTC, dongyanyang commented on zthin-parts/zthin/bin/refresh_bootmap
> +    probe_partition=$(/usr/sbin/partprobe $devPath)
maybe add 2 &> 1, otherwise we won't be able to catch the error output

2021-03-05 03:56 UTC, dongyanyang commented on zthin-parts/zthin/bin/refresh_bootmap
> +    inform "Manually run command partprobe on $devPath with output: $rc"
better to also print the $wwid and $map_name.

2021-03-05 03:56 UTC, dongyanyang commented on zthin-parts/zthin/bin/refresh_bootmap
> +        inform "multipath is enabled, so probe partition"
probe partition on $wwid.

2021-03-05 03:56 UTC, dongyanyang commented on zthin-parts/zthin/bin/refresh_bootmap
>      sleepTimes=".001 .01 .1 .5 1 2 3 5 8 15 22 34 60 90 120"
decrease the sleep time.
sleepTimes=".001 .01 .1 .5 1 2 3 5 8 15 22"

2021-03-05 06:05 UTC, SharpRazor commented on zthin-parts/zthin/bin/refresh_bootmap
>      sleepTimes=".001 .01 .1 .5 1 2 3 5 8 15 22 34 60 90 120"
done.

2021-03-05 06:05 UTC, SharpRazor commented on zthin-parts/zthin/bin/refresh_bootmap
> +    devPath="/dev/mapper/$map_name"
done.

2021-03-05 06:05 UTC, SharpRazor commented on zthin-parts/zthin/bin/refresh_bootmap
> +    probe_partition=$(/usr/sbin/partprobe $devPath)
done.

2021-03-05 06:05 UTC, SharpRazor commented on zthin-parts/zthin/bin/refresh_bootmap
> +    inform "Manually run command partprobe on $devPath with output: $rc"
done.

2021-03-05 06:06 UTC, SharpRazor commented on zthin-parts/zthin/bin/refresh_bootmap
> +        inform "multipath is enabled, so probe partition"
done.

2021-03-05 06:06 UTC, SharpRazor commented on zthin-parts/zthin/bin/refresh_bootmap
>      sleepTimes=".001 .01 .1 .5 1 2 3 5 8 15 22 34 60 90 120"
done.

2021-03-08 07:14 UTC, dongyanyang approved these changes
lgtm

2021-03-08 07:19 UTC, jichenjc commented
@bjhuangr please check this ,thanks

lgtm

2021-03-08 09:50 UTC, SharpRazor commented
@dongyanyang @bjhuangr @jichenjc FYI:
in my env, I move the probePartition code out of the if statement to manually trigger this code, and deploy VMs, the output log:
```
Mar  8 00:44:26 113-cmp-cb root[1241067]: 1238469.0 refresh_bootmap: refresh_bootmap: refreshZIPL: Begin to refreshZIPL.
Mar  8 00:44:26 113-cmp-cb root[1241071]: 1238469.0 refresh_bootmap: refresh_bootmap: refreshZIPL: multipath is enabled, so probe partition on dev of wwid: 3600507640083826de0000000000034d5
Mar  8 00:44:26 113-cmp-cb root[1241078]: 1238469.0 refresh_bootmap: refresh_bootmap: probePartition: Before partprobe, /dev/disk/by-path/ folder content: ccw-0.0.0100#012ccw-0.0.0100-part1#012ccw-0.0.1a14-fc-0x500507680b21bac6-lun-0#012ccw-0.0.1a14-fc-0x500507680b21bac6-lun-0-part1#012ccw-0.0.1a14-fc-0x500507680b21bac7-lun-0#012ccw-0.0.1a14-fc-0x500507680b22bac6-lun-0#012ccw-0.0.1a14-fc-0x500507680b22bac7-lun-0#012ccw-0.0.1a14-fc-0x500507680b22bac7-lun-0-part1#012ccw-0.0.1a14-zfcp-0x500507680b21bac6:0x0000000000000000#012ccw-0.0.1a14-zfcp-0x500507680b21bac6:0x0000000000000000-part1#012ccw-0.0.1a14-zfcp-0x500507680b21bac7:0x0000000000000000#012ccw-0.0.1a14-zfcp-0x500507680b22bac6:0x0000000000000000#012ccw-0.0.1a14-zfcp-0x500507680b22bac7:0x0000000000000000#012ccw-0.0.1a14-zfcp-0x500507680b22bac7:0x0000000000000000-part1#012ccw-0.0.1b18-fc-0x500507680b21bac6-lun-0#012ccw-0.0.1b18-fc-0x500507680b21bac7-lun-0#012ccw-0.0.1b18-fc-0x500507680b22bac6-lun-0#012ccw-0.0.1b18-fc-0x500507680b22bac7-lun-0#012ccw-0.0.1b18-zfcp-0x500507680b21bac6:0x0000000000000000#012ccw-0.0.1b18-zfcp-0x500507680b21bac7:0x00000000000000
Mar  8 00:44:26 113-cmp-cb root[1241083]: 1238469.0 refresh_bootmap: refresh_bootmap: probePartition: Before partprobe, /dev/disk/by-id/ folder content: dm-name-mpathbp#012dm-name-mpathbq#012dm-name-mpathbq1#012dm-uuid-mpath-3600507640083826de00000000000331b#012dm-uuid-mpath-3600507640083826de0000000000034d5#012dm-uuid-part1-mpath-3600507640083826de0000000000034d5#012scsi-3600507640083826de00000000000331b#012scsi-3600507640083826de0000000000034d5#012scsi-3600507640083826de0000000000034d5-part1#012scsi-SIBM_2145_010020e09b78XX00#012scsi-SIBM_2145_010020e09b78XX00-part1#012wwn-0x600507640083826de00000000000331b#012wwn-0x600507640083826de0000000000034d5#012wwn-0x600507640083826de0000000000034d5-part1.
Mar  8 00:44:27 113-cmp-cb root[1241088]: 1238469.0 refresh_bootmap: refresh_bootmap: probePartition: Before partprobe, /dev/mapper/ folder content: control#012mpathbp#012mpathbq#012mpathbq1.
Mar  8 00:44:27 113-cmp-cb root[1241100]: 1238469.0 refresh_bootmap: refresh_bootmap: probePartition: Manually run command partprobe on /dev/mapper/mpathbq of wwid 3600507640083826de0000000000034d5 with return code: 0
Mar  8 00:44:27 113-cmp-cb root[1241107]: 1238469.0 refresh_bootmap: refresh_bootmap: probePartition: After partprobe, /dev/disk/by-path/ folder content: ccw-0.0.0100#012ccw-0.0.0100-part1#012ccw-0.0.1a14-fc-0x500507680b21bac6-lun-0#012ccw-0.0.1a14-fc-0x500507680b21bac6-lun-0-part1#012ccw-0.0.1a14-fc-0x500507680b21bac7-lun-0#012ccw-0.0.1a14-fc-0x500507680b22bac6-lun-0#012ccw-0.0.1a14-fc-0x500507680b22bac7-lun-0#012ccw-0.0.1a14-fc-0x500507680b22bac7-lun-0-part1#012ccw-0.0.1a14-zfcp-0x500507680b21bac6:0x0000000000000000#012ccw-0.0.1a14-zfcp-0x500507680b21bac6:0x0000000000000000-part1#012ccw-0.0.1a14-zfcp-0x500507680b21bac7:0x0000000000000000#012ccw-0.0.1a14-zfcp-0x500507680b22bac6:0x0000000000000000#012ccw-0.0.1a14-zfcp-0x500507680b22bac7:0x0000000000000000#012ccw-0.0.1a14-zfcp-0x500507680b22bac7:0x0000000000000000-part1#012ccw-0.0.1b18-fc-0x500507680b21bac6-lun-0#012ccw-0.0.1b18-fc-0x500507680b21bac7-lun-0#012ccw-0.0.1b18-fc-0x500507680b22bac6-lun-0#012ccw-0.0.1b18-fc-0x500507680b22bac7-lun-0#012ccw-0.0.1b18-zfcp-0x500507680b21bac6:0x0000000000000000#012ccw-0.0.1b18-zfcp-0x500507680b21bac7:0x000000000000000
Mar  8 00:44:27 113-cmp-cb root[1241116]: 1238469.0 refresh_bootmap: refresh_bootmap: probePartition: After partprobe, /dev/disk/by-id/ folder content: dm-name-mpathbp#012dm-name-mpathbq#012dm-name-mpathbq1#012dm-uuid-mpath-3600507640083826de00000000000331b#012dm-uuid-mpath-3600507640083826de0000000000034d5#012dm-uuid-part1-mpath-3600507640083826de0000000000034d5#012scsi-3600507640083826de00000000000331b#012scsi-3600507640083826de0000000000034d5#012scsi-3600507640083826de0000000000034d5-part1#012scsi-SIBM_2145_010020e09b78XX00#012scsi-SIBM_2145_010020e09b78XX00-part1#012wwn-0x600507640083826de00000000000331b#012wwn-0x600507640083826de0000000000034d5#012wwn-0x600507640083826de0000000000034d5-part1.
Mar  8 00:44:27 113-cmp-cb root[1241121]: 1238469.0 refresh_bootmap: refresh_bootmap: probePartition: After partprobe, /dev/mapper/ folder content: control#012mpathbp#012mpathbq#012mpathbq1.
Mar  8 00:44:27 113-cmp-cb root[1241126]: 1238469.0 refresh_bootmap: refresh_bootmap: refreshZIPL: devNode is: /dev/disk/by-id/dm-uuid-part1-mpath-3600507640083826de0000000000034d5 point: /mnt/OOvBK
```

2021-03-09 01:03 UTC, bjhuangr commented
Only one question: Is `partprobe` really required?

2021-03-09 01:46 UTC, jackydalong commented
At least one reason to keep partprobe is that
we need manually load partition in case of 'skip_kpartx = yes' in multipath.conf 
@bjhuangr Do you agree ?

2021-03-09 01:51 UTC, SharpRazor commented
yes, just like Jacky said, we found that manually run partprobe help to reduce the issue that devNode not exist.

2021-03-09 02:51 UTC, merged