fix KeyError when refresh_bootmap reach timeout
openmainframeproject/feilong pull request #431
Opened 2021-03-04 06:51 UTC by SharpRazor

Signed-off-by: SharpRazor <bjcb@cn.ibm.com>

2021-03-05 02:29 UTC, SharpRazor commented
the new errors reported is:
```
Deploy of virtual machine rhel82_scsi on host m54zvm147 failed with exception: Build of instance 2c944306-fc61-44f7-9114-f2b1e6a8d878 was re-scheduled: zVM Cloud Connector request failed: {'overallRC': 500, 'modID': 130, 'rc': 500, 'rs': 1, 'errmsg': 'Unexpected internal error in ZVM SDK, error: Unexpected internal error in ZVM SDK, error: Command "sudo /opt/zthin/bin/refresh_bootmap --fcpchannel=1a11,1b11 --wwpn=500507680B21BAC6,500507680B23BAC6,500507680B24BAC6,500507680B22BAC6,500507680B24BAC7,500507680B22BAC7,500507680B23BAC7,500507680B21BAC7 --lun=0000000000000000" Error: [Errno 1] Operation not permitted', 'output': ''}
```

I will commit a new patch to report timeout error.

2021-03-05 05:49 UTC, SharpRazor commented
the new error will be like:
```
Deploy of virtual machine rhel82_scsi on host m54zvm147 failed with exception: Build of instance d350821d-819b-4d5e-8742-1615a043073d was re-scheduled: zVM Cloud Connector request failed: {'overallRC': 300, 'modID': 30, 'rc': 300, 'rs': 7, 'errmsg': "Refresh bootmap did not finish in limited timeout with reason command ['sudo', '/opt/zthin/bin/refresh_bootmap', '--fcpchannel=1a19,1b13', '--wwpn=500507680B21BAC6,500507680B23BAC6,500507680B24BAC6,500507680B22BAC6,500507680B24BAC7,500507680B22BAC7,500507680B23BAC7,500507680B21BAC7', '--lun=0000000000000000'] timed out after 600 seconds.", 'output': ''}
```

2021-03-08 01:47 UTC, bjhuangr commented on zvmsdk/smtclient.py
> +            if err_msg.__contains__("Operation not permitted"):
not a proper keyword

2021-03-08 01:47 UTC, bjhuangr commented
And please check the py36 result

2021-03-08 01:58 UTC, SharpRazor commented on zvmsdk/smtclient.py
> +            if err_msg.__contains__("Operation not permitted"):
changed to `"Operation not permitted" in err_msg: `, is this ok?

2021-03-08 07:12 UTC, dongyanyang requested changes

2021-03-08 07:12 UTC, dongyanyang commented on zvmsdk/smtclient.py
> +            raise exception.SDKRefreshBootmapTimeoutError(rs=7, msg=err_msg)
why would you create a new excepetion class instead of using the existing SDKVolumeOperationError?

2021-03-08 07:12 UTC, dongyanyang commented on zvmsdk/smtclient.py
> +            if "Operation not permitted" in err_msg:
I also think the filter string is not proper, don't the python subprocess has a more specific error for the timeout error. 
pls attach the complete err_msg.

2021-03-08 07:50 UTC, SharpRazor commented
@dongyanyang @bjhuangr please see this:
```
[2021-03-04 20:57:08] [INFO] 127.0.0.1 "GET /guests" status: 200 length: 87 headers: [('Content-Length', '87'), ('Content-Type', 'application/json'), ('cache-control', 'no-cache')] exc_info: None
[2021-03-04 20:57:08] [ERROR] [Thread-166] (127.0.0.1:37368) Traceback (most recent call last):
  File "/usr/lib64/python3.6/subprocess.py", line 425, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib64/python3.6/subprocess.py", line 863, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib64/python3.6/subprocess.py", line 1535, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/lib64/python3.6/subprocess.py", line 891, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['sudo', '/opt/zthin/bin/refresh_bootmap', '--fcpchannel=1a11,1b11', '--wwpn=500507680B21BAC6,500507680B23BAC6,500507680B24BAC6,500507680B22BAC6,500507680B24BAC7,500507680B22BAC7,500507680B23BAC7,500507680B21BAC7', '--lun=0000000000000000']' timed out after 60 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/zvmsdk/utils.py", line 58, in execute
    timeout=timeout)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 427, in run
    process.kill()
  File "/usr/lib64/python3.6/subprocess.py", line 1610, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib64/python3.6/subprocess.py", line 1600, in send_signal
    os.kill(self.pid, sig)
PermissionError: [Errno 1] Operation not permitted
```

the subprocess will always report "Operation not permitted" error instead of its parent error of timeout.

So I need to replace them with timeout exception.

do you have a better solution experience for this? I didn't figure out, so I use `if "Operation not permitted" in err_msg: `.

2021-03-09 03:10 UTC, bjhuangr commented
In this case, you can catch `subprocess.TimeoutExpired` and `PermissionError`, to log the error, then re-raise SDKVolumeOperationError with refresh bootmap timeout message.

2021-03-09 04:50 UTC, SharpRazor commented
> In this case, you can catch `subprocess.TimeoutExpired` and `PermissionError`, to log the error, then re-raise SDKVolumeOperationError with refresh bootmap timeout message.

yes! I forgot the AND ..... OK, I will try.

2021-03-10 04:55 UTC, SharpRazor commented
the called process debug:
```
(Pdb) n
> /usr/lib/python3.6/site-packages/zvmsdk/smtclient.py(795)volume_refresh_bootmap()
-> (rc, output) = zvmutils.execute(cmd, timeout=60)
(Pdb) s
--Call--
> /usr/lib/python3.6/site-packages/zvmsdk/utils.py(43)execute()
-> def execute(cmd, timeout=None):
(Pdb) n
> /usr/lib/python3.6/site-packages/zvmsdk/utils.py(50)execute()
-> if not isinstance(cmd, list):
(Pdb) n
> /usr/lib/python3.6/site-packages/zvmsdk/utils.py(53)execute()
-> rc = 0
(Pdb) n
> /usr/lib/python3.6/site-packages/zvmsdk/utils.py(54)execute()
-> output = ""
(Pdb) n
> /usr/lib/python3.6/site-packages/zvmsdk/utils.py(55)execute()
-> try:
(Pdb) 
> /usr/lib/python3.6/site-packages/zvmsdk/utils.py(56)execute()
-> output = subprocess.check_output(cmd, close_fds=True,
(Pdb) 
> /usr/lib/python3.6/site-packages/zvmsdk/utils.py(57)execute()
-> stderr=subprocess.STDOUT,
(Pdb) 
> /usr/lib/python3.6/site-packages/zvmsdk/utils.py(58)execute()
-> timeout=timeout)
(Pdb) s
--Call--
> /usr/lib64/python3.6/subprocess.py(315)check_output()
-> def check_output(*popenargs, timeout=None, **kwargs):
(Pdb) n
> /usr/lib64/python3.6/subprocess.py(347)check_output()
-> if 'stdout' in kwargs:
(Pdb) a
timeout = 60
popenargs = (['sudo', '/opt/zthin/bin/refresh_bootmap', '--fcpchannel=1b19,1d19', '--wwpn=500507680B23BAC6,500507680B21BAC6,500507680B22BAC6,500507680B24BAC6,500507680B23BAC7,500507680B21BAC7,500507680B24BAC7,500507680B22BAC7', '--lun=0000000000000000'],)
(Pdb) 
timeout = 60
popenargs = (['sudo', '/opt/zthin/bin/refresh_bootmap', '--fcpchannel=1b19,1d19', '--wwpn=500507680B23BAC6,500507680B21BAC6,500507680B22BAC6,500507680B24BAC6,500507680B23BAC7,500507680B21BAC7,500507680B24BAC7,500507680B22BAC7', '--lun=0000000000000000'],)
(Pdb) n
> /usr/lib64/python3.6/subprocess.py(350)check_output()
-> if 'input' in kwargs and kwargs['input'] is None:
(Pdb) 
> /usr/lib64/python3.6/subprocess.py(355)check_output()
-> return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
(Pdb) 
> /usr/lib64/python3.6/subprocess.py(356)check_output()
-> **kwargs).stdout
(Pdb) s
--Call--
> /usr/lib64/python3.6/subprocess.py(392)run()
-> def run(*popenargs, input=None, timeout=None, check=False, **kwargs):
(Pdb) a
input = None
timeout = 60
(Pdb) n
> /usr/lib64/python3.6/subprocess.py(418)run()
-> if input is not None:
(Pdb) 
> /usr/lib64/python3.6/subprocess.py(423)run()
-> with Popen(*popenargs, **kwargs) as process:
(Pdb) 
> /usr/lib64/python3.6/subprocess.py(424)run()
-> try:
(Pdb) 
> /usr/lib64/python3.6/subprocess.py(425)run()
-> stdout, stderr = process.communicate(input, timeout=timeout)
(Pdb) 
subprocess.TimeoutExpired: Command '['sudo', '/opt/zthin/bin/refresh_bootmap', '--fcpchannel=1b19,1d19', '--wwpn=500507680B23BAC6,500507680B21BAC6,500507680B22BAC6,500507680B24BAC6,500507680B23BAC7,500507680B21BAC7,500507680B24BAC7,500507680B22BAC7', '--lun=0000000000000000']' timed out after 60 seconds
> /usr/lib64/python3.6/subprocess.py(425)run()
-> stdout, stderr = process.communicate(input, timeout=timeout)
(Pdb) n
> /usr/lib64/python3.6/subprocess.py(426)run()
-> except TimeoutExpired:
(Pdb) n
> /usr/lib64/python3.6/subprocess.py(427)run()
-> process.kill()
(Pdb) n
PermissionError: [Errno 1] Operation not permitted
> /usr/lib64/python3.6/subprocess.py(427)run()
-> process.kill()
(Pdb) l
422  	
423  	    with Popen(*popenargs, **kwargs) as process:
424  	        try:
425  	            stdout, stderr = process.communicate(input, timeout=timeout)
426  	        except TimeoutExpired:
427  ->	            process.kill()
428  	            stdout, stderr = process.communicate()
429  	            raise TimeoutExpired(process.args, timeout, output=stdout,
430  	                                 stderr=stderr)
431  	        except:
432  	            process.kill()
(Pdb)
```
then the process will wait for the `refresh_bootmap` exit
```
[root@113-cmp-cb ~]# ps aux | grep refresh
root     1615884  0.0  0.0  34420  7612 ?        S    23:44   0:00 sudo /opt/zthin/bin/refresh_bootmap --fcpchannel=1b19,1d19 --wwpn=500507680B23BAC6,500507680B21BAC6,500507680B22BAC6,500507680B24BAC6,500507680B23BAC7,500507680B21BAC7,500507680B24BAC7,500507680B22BAC7 --lun=0000000000000000
root     1615886  0.0  0.0   6616  2972 ?        S    23:44   0:00 /bin/bash /opt/zthin/bin/refresh_bootmap --fcpchannel=1b19,1d19 --wwpn=500507680B23BAC6,500507680B21BAC6,500507680B22BAC6,500507680B24BAC6,500507680B23BAC7,500507680B21BAC7,500507680B24BAC7,500507680B22BAC7 --lun=0000000000000000
```

then the process return:
```
(Pdb) n

--Return--
> /usr/lib64/python3.6/subprocess.py(427)run()->None
-> process.kill()
(Pdb) PermissionError: [Errno 1] Operation not permitted
> /usr/lib64/python3.6/subprocess.py(356)check_output()
-> **kwargs).stdout
(Pdb) --Return--
> /usr/lib64/python3.6/subprocess.py(356)check_output()->None
-> **kwargs).stdout
(Pdb)
(Pdb) n
> /usr/lib/python3.6/site-packages/zvmsdk/utils.py(59)execute()
-> except subprocess.CalledProcessError as err:
(Pdb) 
> /usr/lib/python3.6/site-packages/zvmsdk/utils.py(62)execute()
-> except Exception as err:
(Pdb) n
> /usr/lib/python3.6/site-packages/zvmsdk/utils.py(63)execute()
-> err_msg = ('Command "%s" Error: %s' % (' '.join(cmd), str(err)))
(Pdb) n
> /usr/lib/python3.6/site-packages/zvmsdk/utils.py(64)execute()
-> raise exception.SDKInternalError(msg=err_msg)
(Pdb) n
zvmsdk.exception.SDKInternalError: Unexpected internal error in ZVM SDK, error: Command "sudo /opt/zthin/bin/refresh_bootmap --fcpchannel=1b19,1d19 --wwpn=500507680B23BAC6,500507680B21BAC6,500507680B22BAC6,500507680B24BAC6,500507680B23BAC7,500507680B21BAC7,500507680B24BAC7,500507680B22BAC7 --lun=0000000000000000" Error: [Errno 1] Operation not permitted
> /usr/lib/python3.6/site-packages/zvmsdk/utils.py(64)execute()
-> raise exception.SDKInternalError(msg=err_msg)
(Pdb) 
```

2021-03-10 07:17 UTC, SharpRazor commented
the error reported on UI after change will be like:
```
Deploy of virtual machine rhel82_scsi on host m54zvm147 failed with exception: Build of instance 0c78ffaa-8580-4f8c-950f-56a6b35ce855 was re-scheduled: zVM Cloud Connector request failed: {'overallRC': 300, 'modID': 30, 'rc': 300, 'rs': 7, 'errmsg': "Refresh bootmap did not finish in limited timeout with reason Running command: ['sudo', '/opt/zthin/bin/refresh_bootmap', '--fcpchannel=1b14,1d18', '--wwpn=500507680B23BAC6,500507680B21BAC6,500507680B22BAC6,500507680B24BAC6,500507680B23BAC7,500507680B21BAC7,500507680B24BAC7,500507680B22BAC7', '--lun=0000000000000000'] timed out.", 'output': ''}
```

2021-03-10 07:17 UTC, SharpRazor commented on zvmsdk/smtclient.py
> +            raise exception.SDKRefreshBootmapTimeoutError(rs=7, msg=err_msg)
reuse SDKVolumeOperationError, done.

2021-03-10 07:18 UTC, SharpRazor commented on zvmsdk/smtclient.py
> +            if err_msg.__contains__("Operation not permitted"):
done.

2021-03-10 07:18 UTC, SharpRazor commented on zvmsdk/smtclient.py
> +            if "Operation not permitted" in err_msg:
.new version committed, please help review.

2021-03-10 08:48 UTC, bjhuangr commented on zvmsdk/returncode.py
> +                   "timeout with reason %(msg)s",
`Refresh bootmap timeout with reason %(msg)s`

2021-03-10 08:48 UTC, bjhuangr commented on zvmsdk/smtclient.py
> +        except Exception as err:
no need to handle this again, as it's already handled in utils

2021-03-10 09:44 UTC, SharpRazor commented on zvmsdk/returncode.py
> +                   "timeout with reason %(msg)s",
done.

2021-03-10 10:14 UTC, bjhuangr reviewed
lgtm

2021-03-18 03:01 UTC, dongyanyang approved these changes

2021-03-18 03:07 UTC, merged