refine refreshbootmap code
openmainframeproject/feilong pull request #435
Opened 2021-03-18 10:27 UTC by dongyanyang

1. use `lszfcp -P` to replace the `lsluns` to find the valid target ports
2. for the valid (fcp, wwpn) combination, do the unit_add/unit_remove to fit the disable of allow_lun_scan
3. fix the issue of wwpns variable be overwritten
4. add util functions in zthinutil to each sub task, eg addlun, removelun, dedicateonlineFCP, offlineUndedicateFCP

Signed-off-by: dyyang <dyyang@cn.ibm.com>

2021-03-18 10:32 UTC, dongyanyang commented
Do Not Merge. I need to do strong tests for this change.

2021-03-22 04:22 UTC, jackydalong commented on zthin-parts/zthin/lib/zthinshellutils
> +  out=`/opt/zthin/bin/smcli Image_Device_Dedicate -T $zthinUserID -v ${fcpChannel} -r ${fcpChannel} 0 &`
The smcli cmd here is ended with "**&**", why do we put it to background?
@dongyanyang

2021-03-22 04:24 UTC, jackydalong commented on zthin-parts/zthin/lib/zthinshellutils
> +  if (( $? )); then
Suggest using the same style, ex:
replace
```shell
if (( $? ))
```
with
```shell
if [[ $? -ne 0 ]]
```

2021-03-22 04:25 UTC, jackydalong commented on zthin-parts/zthin/lib/zthinshellutils
> +function addLun {
change "addLun" to "addLUN"

2021-03-22 05:09 UTC, jackydalong commented on zthin-parts/zthin/bin/refresh_bootmap
> +          # add this combination into valid_dict
change 
```
           # add this combination into valid_dict
```
to
```
               # add this combination into valid_dict
```

2021-03-22 05:29 UTC, jackydalong commented on zthin-parts/zthin/bin/refresh_bootmap
> +              if [[ -z ${valid_dict["$fcp"]} ]]; then
Suggest use the same style which removes the unnecessary quote
Thus, replace 
```shell
${valid_dict["$fcp"]}   <<< line 685
```
to
```shell
${valid_dict[$fcp]}   <<< line 709
```

2021-03-22 05:31 UTC, jackydalong commented on zthin-parts/zthin/bin/refresh_bootmap
> +                  old_value=${valid_dict["$fcp"]}
ditto
Suggest use the same style which removes the unnecessary quote

2021-03-22 06:35 UTC, jackydalong commented on zthin-parts/zthin/lib/zthinshellutils
> +      echo "${wwpn}" > /sys/bus/ccw/devices/0.0.${fcpChannel}/port_add
On my cmp node -> online fcp manually by smcli. 
However, there is no file "port_add" -> above cmd failed as "Permission denied"
```shell
# example

[root@113-cmp-wdl-m5403 ~]# lsmod | grep zfcp
[root@113-cmp-wdl-m5403 ~]#
[root@113-cmp-wdl-m5403 ~]# modprobe zfcp
[root@113-cmp-wdl-m5403 ~]#
[root@113-cmp-wdl-m5403 ~]# lsmod | grep zfcp
zfcp                  126976  0
scsi_transport_fc      69632  1 zfcp
qdio                   69632  3 qeth,zfcp,qeth_l2
[root@113-cmp-wdl-m5403 ~]#
[root@113-cmp-wdl-m5403 ~]# cat /sys/module/zfcp/parameters/allow_lun_scan
Y
[root@113-cmp-wdl-m5403 ~]#
[root@113-cmp-wdl-m5403 ~]# ls /sys/bus/ccw/devices/
0.0.0009  0.0.000c  0.0.000d  0.0.0100  0.0.1000  0.0.1001  0.0.1002
[root@113-cmp-wdl-m5403 ~]#
[root@113-cmp-wdl-m5403 ~]# smcli Image_Device_Dedicate -T $userid -v 1a0d -r 1a0d -R 0
[root@113-cmp-wdl-m5403 ~]#
[root@113-cmp-wdl-m5403 ~]# lszfcp
0.0.1a0d host0
[root@113-cmp-wdl-m5403 ~]# ls /sys/bus/ccw/devices/0.0.1a0d/
0x5005076306035388  0x500507680b21bac7  0x500507680d120027  card_version  driver            in_recovery  peer_d_id    port_rescan  uevent
0x5005076306105388  0x500507680b22bac6  0x500507680d760027  cmb_enable    failed            lic_version  peer_wwnn    power
0x50050763061bd388  0x500507680b22bac7  0x500507680d820027  cutype        hardware_version  modalias     peer_wwpn    status
0x500507680b21bac6  0x500507680d060027  availability        devtype       host0             online       port_remove  subsystem
[root@113-cmp-wdl-m5403 ~]#
[root@113-cmp-wdl-m5403 ~]# ls /sys/bus/ccw/devices/0.0.1a0d/port*
/sys/bus/ccw/devices/0.0.1a0d/port_remove  /sys/bus/ccw/devices/0.0.1a0d/port_rescan
[root@113-cmp-wdl-m5403 ~]#
[root@113-cmp-wdl-m5403 ~]# echo "0x5005076306035399" > /sys/bus/ccw/devices/0.0.1a0d/port_add
-bash: /sys/bus/ccw/devices/0.0.1a0d/port_add: Permission denied             <<<<<<<<
[root@113-cmp-wdl-m5403 ~]#
[root@113-cmp-wdl-m5403 ~]# ls -l /sys/bus/ccw/devices/0.0.1a0d/port*
--w-------. 1 root root 4096 Mar 22 02:29 /sys/bus/ccw/devices/0.0.1a0d/port_remove
--w-------. 1 root root 4096 Mar 22 02:29 /sys/bus/ccw/devices/0.0.1a0d/port_rescan
[root@113-cmp-wdl-m5403 ~]#
[root@113-cmp-wdl-m5403 ~]# touch /sys/bus/ccw/devices/0.0.1a0d/port_add
touch: cannot touch '/sys/bus/ccw/devices/0.0.1a0d/port_add': Permission denied
```

2021-03-22 06:48 UTC, jackydalong commented on zthin-parts/zthin/lib/zthinshellutils
> +  if (( $rc )); then
Suggest using the same style, ex:
replace
```
if (( $rc ))
```
with
```
if [[ $rc -ne 0 ]]
```

2021-03-22 07:07 UTC, jackydalong commented on zthin-parts/zthin/lib/zthinshellutils
> +  # created so we will wait up to 3 minutes for the unit_remove file to show up.
The comment does not make sense to me. Not sure what it means

2021-03-22 07:10 UTC, jackydalong commented on zthin-parts/zthin/lib/zthinshellutils
> +        echo "1" > "/sys/block/$devName/device/delete"
Based on RedHat offical doc, suggest change
```
echo "1"
```
to
```
echo 1
```

2021-03-22 07:24 UTC, jackydalong commented on zthin-parts/zthin/bin/refresh_bootmap
> +  # loop to do unit_add to each (fcp, wwpn) in valid_dict and check lun existence
replace unit_add with unit_remove in the comment here

2021-03-22 07:30 UTC, jackydalong requested changes
Please check my comments

2021-04-01 06:48 UTC, dongyanyang commented
@jackydalong @bjhuangr @jichenjc comments addressed and tested, pls check again. Then I will merge as several other changes wait for this fix.

2021-04-01 07:09 UTC, jackydalong approved these changes
LGTM

2021-04-01 07:22 UTC, merged

2021-04-01 07:22 UTC, jichenjc commented
let's merge this and move forward