[master]get_from_assigner should return unreserved FCPs
openmainframeproject/feilong pull request #436
Opened 2021-03-19 05:11 UTC by SharpRazor

Signed-off-by: SharpRazor <bjcb@cn.ibm.com>

2021-03-19 05:25 UTC, SharpRazor commented
the difference of these 2 statement are following:
```
[root@113-cmp-cb databases]# sqlite3 sdk_fcp.sqlite
SQLite version 3.26.0 2018-12-01 12:34:55
Enter ".help" for usage hints.
sqlite> select * from fcp where assigner_id='CBM5400A' and (reserved <> 0 or connections <> 0);
1a11|CBM5400A|2|1|0|
1c14|CBM5400A|2|1|1|
1d18|CBM5400A|2|1|2|
sqlite> select * from fcp where assigner_id='CBM5400A';
1a10|CBM5400A|0|0|0|
1a11|CBM5400A|2|1|0|
1c14|CBM5400A|2|1|1|
1d18|CBM5400A|2|1|2|
sqlite>
```

2021-03-19 05:42 UTC, SharpRazor commented
### without this patch:
```
[2021-03-19 01:35:23] [INFO] Got available fcp_list [('1a10', 'CBM5400A', 0, 0, 0, ''), ('1a11', 'CBM5400A', 1, 1, 0, ''), ('1c14', 'CBM5400A', 1, 1, 1, ''), ('1d18', 'CBM5400A', 1, 1, 2, '')] in Unreserve mode from CBM5400A.
```

### with this patch:
```
[2021-03-19 01:42:07] [INFO] Got available fcp_list [('1a11', 'CBM5400A', 1, 1, 0, ''), ('1c14', 'CBM5400A', 1, 1, 1, ''), ('1d18', 'CBM5400A', 1, 1, 2, '')] in Unreserve mode from CBM5400A.
```

2021-03-19 05:44 UTC, dongyanyang requested changes

2021-03-19 05:44 UTC, dongyanyang commented on zvmsdk/database.py
> +                                  "and (reserved <> 0 or connections <> 0) "
then what's the difference between get_from_assigner and get_allocated_fcps_from_assigner?

2021-03-19 05:56 UTC, jackydalong commented on zvmsdk/database.py
> +                                  "and (reserved <> 0 or connections <> 0) "
Suggest use capital format for all SQL keyword, ex:
<img width="980" alt="image" src="https://user-images.githubusercontent.com/20807562/111737592-dabc4c00-88ba-11eb-9e18-3aaf2ac0cdd7.png">

2021-03-19 06:29 UTC, SharpRazor commented on zvmsdk/database.py
> +                                  "and (reserved <> 0 or connections <> 0) "
good question, after change, they have no difference.

2021-03-19 06:31 UTC, jackydalong commented
Suggest change below "LOG.debug" to "LOG.info", which makes debug from log clearer.
```python
#zvmsdk/volumeop.py
    def get_volume_connector(self, assigner_id, reserve):
        """Get connector information of the instance for attaching to volumes.
...
        LOG.debug('get_volume_connector returns %s for %s' %.       <<<<<
                  (connector, assigner_id))
```

2021-03-19 06:48 UTC, SharpRazor commented on zvmsdk/database.py
> +                                  "and (reserved <> 0 or connections <> 0) "
I committed a new version, remove the condition that connections <> 0.

2021-03-19 06:49 UTC, SharpRazor commented on zvmsdk/database.py
> +                                  "and (reserved <> 0 or connections <> 0) "
good advice, done.

2021-03-19 06:51 UTC, SharpRazor commented
> @SharpRazor
> Suggest change below "LOG.debug" to "LOG.info", which makes debug from log clearer.
> 
> ```python
> #zvmsdk/volumeop.py
>     def get_volume_connector(self, assigner_id, reserve):
>         """Get connector information of the instance for attaching to volumes.
> ...
>         LOG.debug('get_volume_connector returns %s for %s' %.       <<<<<
>                   (connector, assigner_id))
> ```

OK, done.

2021-03-19 07:09 UTC, jackydalong approved these changes
LGTM

2021-03-19 07:22 UTC, jichenjc commented
@dongyanyang please share your opinion, thanks

2021-03-22 02:26 UTC, jackydalong commented
To make debug from log clearer, it better to print the fcp within related log.
Thus, highly suggest changing below LOG 
```python
zvmsdk/volumeop.py
    def _attach(self, fcp, assigner_id, target_wwpns, target_lun,
        LOG.info('Start to attach device to %s' % assigner_id)   <<<<<<<  1
            LOG.info('Attaching device to %s is done.' % assigner_id) <<<<<<< 2
        LOG.info('Attaching device to %s is done.' % assigner_id) <<<<<<< 3

    def _detach(self, fcp, assigner_id, target_wwpns, target_lun,
            LOG.info('Detaching device from %s is done.' % assigner_id)  <<<<< 4
        LOG.info('Detaching device from %s is done.' % assigner_id). <<<<<< 5 

```
to 
```python
    def _attach(self, fcp, assigner_id, target_wwpns, target_lun,
        LOG.info('Start to attach fcp device %s to %s' % (fcp, assigner_id)) 
            LOG.info('Attaching fcp device %s to %s is done.' % (fcp, assigner_id)) 
        LOG.info('Attaching fcp device %s to %s is done.' % (fcp, assigner_id)) 

    def _detach(self, fcp, assigner_id, target_wwpns, target_lun,
            LOG.info('Detaching fcp device %s from %s is done.' % (fcp, assigner_id))  
        LOG.info('Detaching fcp device %s from %s is done.' % (fcp, assigner_id)) 
```
@bjcb

2021-03-22 10:11 UTC, SharpRazor commented on zvmsdk/volumeop.py
> -        # Unreserved fcp device after undedicate all FCP devices
remove this because get_volume_connector will unreserve them.

2021-03-22 10:12 UTC, SharpRazor commented
> To make debug from log clearer, it better to print the fcp within related log.
> Thus, highly suggest changing below LOG
> 
> ```python
> zvmsdk/volumeop.py
>     def _attach(self, fcp, assigner_id, target_wwpns, target_lun,
>         LOG.info('Start to attach device to %s' % assigner_id)   <<<<<<<  1
>             LOG.info('Attaching device to %s is done.' % assigner_id) <<<<<<< 2
>         LOG.info('Attaching device to %s is done.' % assigner_id) <<<<<<< 3
> 
>     def _detach(self, fcp, assigner_id, target_wwpns, target_lun,
>             LOG.info('Detaching device from %s is done.' % assigner_id)  <<<<< 4
>         LOG.info('Detaching device from %s is done.' % assigner_id). <<<<<< 5 
> ```
> 
> to
> 
> ```python
>     def _attach(self, fcp, assigner_id, target_wwpns, target_lun,
>         LOG.info('Start to attach fcp device %s to %s' % (fcp, assigner_id)) 
>             LOG.info('Attaching fcp device %s to %s is done.' % (fcp, assigner_id)) 
>         LOG.info('Attaching fcp device %s to %s is done.' % (fcp, assigner_id)) 
> 
>     def _detach(self, fcp, assigner_id, target_wwpns, target_lun,
>             LOG.info('Detaching fcp device %s from %s is done.' % (fcp, assigner_id))  
>         LOG.info('Detaching fcp device %s from %s is done.' % (fcp, assigner_id)) 
> ```
> 
> @bjcb

good advice, done.

2021-03-23 10:04 UTC, dongyanyang commented
I need more time to check the logic, pls hold for a while

2021-04-02 09:48 UTC, dongyanyang approved these changes
LGTM

2021-04-02 10:46 UTC, jichenjc commented
@SharpRazor you need solve the conflict.. thanks

2021-04-02 10:47 UTC, merged