[master]Add interfaces to get disk volumes of the diskpool
openmainframeproject/feilong pull request #437
Opened 2021-04-01 03:28 UTC by trenxiaof

As for CIC onboarding feature, we need check the diskpool of
one vm is the same as the one configued for the sdkserver,
for which we can match the volumes with the one in the vm user direct.
So add these interfaces to get the disk volumes of the diskpool.

If the diskpool is provided, query the voluems of the pool, if not,
the CONF.zvm.disk_pool will be used.

Signed-off-by: Xiao Feng Ren <renxiaof@linux.vnet.ibm.com>

2021-04-01 03:29 UTC, trenxiaof commented
@jichenjc @bjhuangr @SeanHQF  Please help review. (The UT cases haven't been completed, please help check the logic first)

2021-04-08 05:30 UTC, SeanHQF commented on doc/source/restapi.rst
> +  - poolname: disk_pool
Add explanation for the arg because it can be None. If the diskpool is provided, query the voluems of the pool, if not,
the CONF.zvm.disk_pool will be used.

2021-04-08 05:32 UTC, SeanHQF commented on smtLayer/getHost.py
> +        poolNames = ["*"]
I didn't see your code to get the diskpool from CONF.zvm.disk_pool if the arg is None.

2021-04-08 05:32 UTC, SeanHQF commented
Solve the conflict and make the CI passed.

2021-04-08 05:32 UTC, SeanHQF commented
@jichenjc @bjhuangr pls help review, thanks

2021-04-08 05:41 UTC, trenxiaof commented on smtLayer/getHost.py
> +        poolNames = ["*"]
in zvmsdk/api.py  
 def host_get_diskpool_volumes(disk_pool=None):
      disk_pool = disk_pool or CONF.zvm.disk_pool  ---> here

2021-04-08 05:43 UTC, trenxiaof commented on smtLayer/getHost.py
> +        poolNames = ["*"]
The poolName here has been the poolname of CONF.zvm.disk_pool if not sent to that interface.

2021-04-08 05:47 UTC, trenxiaof commented on doc/source/restapi.rst
> +  - poolname: disk_pool
ok

2021-04-18 08:43 UTC, SeanHQF commented on smtLayer/getHost.py
> +        poolNames = ["*"]
ok

2021-04-21 06:16 UTC, bjhuangr commented on smtLayer/getHost.py
> +            poolVolumes.pop(0)
guess poolVolumes.pop(0) will pop diskpool name out, right? if invokeSMCLI issue smcli with --addRCheader , does this line still work?

2021-04-22 01:22 UTC, trenxiaof commented on smtLayer/getHost.py
> +            poolVolumes.pop(0)
yes, pop(0) pop the diskpool name.  the smcli command has been limited to "parms = ["-q", "1", "-e", "3", "-T", "dummy", "-n", "".join(poolNames)]".   no --addRCheader in this function.

2021-04-22 01:22 UTC, trenxiaof commented on doc/source/restapi.rst
> +Get volume names of the diskpool on the host.
ok for all above.

2021-04-25 05:29 UTC, trenxiaof commented
@bjhuangr @jichenjc please help review. thank you!

2021-04-26 05:15 UTC, bjhuangr requested changes

2021-04-26 05:15 UTC, bjhuangr commented on smtLayer/getHost.py
> +            poolVolumes.pop(0)
`"".join(poolNames)` => `" ".join(poolNames)`

2021-04-26 05:15 UTC, bjhuangr commented on smtLayer/getHost.py
> +            poolVolumes.pop(0)
refer to https://github.com/openmainframeproject/feilong/blob/master/smtLayer/vmUtils.py#L682

It seems invokeSMCLI will add RC header. Please double check.

2021-04-26 07:03 UTC, trenxiaof commented on smtLayer/getHost.py
> +            poolVolumes.pop(0)
The result I got was the right volume list, no RC header. Besides, in the vmUtils, 
  smcliResp = smcliResp.split('\n', 1)
  results['response'] = smcliResp[1]
The header seems removed.
I will check it agian.

2021-04-26 08:41 UTC, trenxiaof commented on smtLayer/getHost.py
> +            poolVolumes.pop(0)
Have verified, the header will not be returned by `results['response'] = smcliResp[1]`.
Other comments have also solved.

2021-04-26 08:42 UTC, trenxiaof commented on smtLayer/getHost.py
> +            poolVolumes.pop(0)
@bjhuangr

2021-04-26 09:35 UTC, bjhuangr commented on smtLayer/getHost.py
> +            poolVolumes.pop(0)
Thanks for the double check

2021-04-26 09:37 UTC, bjhuangr approved these changes

2021-04-28 07:17 UTC, merged