combine fcp_list into one punch script
openmainframeproject/feilong pull request #450
Opened 2021-04-20 09:28 UTC by SharpRazor

Signed-off-by: SharpRazor <bjcb@cn.ibm.com>

2021-04-21 07:47 UTC, dongyanyang requested changes

2021-04-21 07:47 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                              'machine %s , please check its connections '
Error msg is not accurate: device %s (fcp_list) did not show up 
should be the disk does not show up in the target virtual machine (not fcp_list)

2021-04-21 07:47 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        self.configure_volume_attach(fcp_list, assigner_id, target_wwpns,
suggest to log the parameters as info log.

2021-04-21 07:47 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        self.configure_volume_detach(fcp_list, assigner_id, target_wwpns,
log.info key parameters

2021-04-21 07:47 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            # root volume will be dedicated by refresh_bootmap
this comment is wrong.  the FCP devices are defined in user entry, don't need to use smcli to dedicate.

2021-04-21 07:47 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            errmsg = ("The passed in fcps in connection_info %s "
why would you add this check? I cann't think of a scenario for this to happen.

2021-04-21 07:47 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            raise exception.SDKVolumeOperationError(rs=7,
Also rs=7 is for refreshbootmap error, not this.

2021-04-21 07:47 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            need_restart = True
no need to keep the need_restart parameter, to keep our code clean.

2021-04-21 07:47 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                    self._dedicate_fcp(fcp, assigner_id)
1. log.info ( "start to dedicate FCP xxx to userid: xxx.") before _dedicate_fcp
2. log.info (FCP xxx dedicated to xxx) after _dedicate_fcp

2021-04-21 07:47 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        if is_root_volume:
you cann't just return at the beginning.
for root_volume, should return after connections is increased which is done in add_fcp_for_assigner.

2021-04-21 07:47 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            LOG.info("Attaching devices %s to %s is "
the log is confusing, should say sth like "is root volume, xxx."

2021-04-21 07:47 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                if fcp_status[fcp]:
add a else for this, to log.info("This is not the first volume for FCP xxx, skip dedicating FCP device.")

2021-04-21 08:13 UTC, dongyanyang requested changes

2021-04-21 08:13 UTC, dongyanyang commented on zvmsdk/volumeops/templates/rhel7_attach_volume.j2
> +        for j in ${ActiveWWPNs[@]}
should move the device check out of the current loop, after all FCPs are done unit_add.

2021-04-21 08:13 UTC, dongyanyang commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +    WWIDs[index]=$wwid
di'fferent path has same wwid. no need for array

2021-04-21 10:14 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +                              'machine %s , please check its connections '
done.

2021-04-21 10:14 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +        self.configure_volume_attach(fcp_list, assigner_id, target_wwpns,
done, but add to config_attach.

2021-04-21 10:14 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +        self.configure_volume_detach(fcp_list, assigner_id, target_wwpns,
done.

2021-04-21 10:15 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +            # root volume will be dedicated by refresh_bootmap
changed, done.

2021-04-21 10:15 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +            errmsg = ("The passed in fcps in connection_info %s "
deleted, done.

2021-04-21 10:15 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +            need_restart = True
deleted, done.

2021-04-21 10:15 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +                    self._dedicate_fcp(fcp, assigner_id)
done.

2021-04-21 10:15 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +        if is_root_volume:
oh, yes, done.

2021-04-21 10:16 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +                if fcp_status[fcp]:
done.

2021-04-21 10:16 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +            LOG.info("Attaching devices %s to %s is "
updated,  done.

2021-04-21 10:16 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +        if len(fcp) == 0:
deleted, done.

2021-04-21 10:16 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +            need_restart = True
done.

2021-04-21 10:16 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +        LOG.info("Start to detach device %s from "
done, please help review the new message content again, thanks.

2021-04-21 10:17 UTC, SharpRazor commented on zvmsdk/volumeop.py
>              LOG.warning("The connections of FCP device %s is 0.", fcp)
this is not added by my code, I dont know the reason, so I kept it.

2021-04-21 10:17 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +                    self._undedicate_fcp(fcp, assigner_id)
done.

2021-04-21 10:17 UTC, SharpRazor commented on zvmsdk/volumeops/templates/rhel7_attach_volume.j2
> +        for j in ${ActiveWWPNs[@]}
right, done.

2021-04-21 10:17 UTC, SharpRazor commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +    WWIDs[index]=$wwid
right, done.

2021-04-21 12:06 UTC, SharpRazor commented
the log in zvmsdk.log for attaching 3 volumes:
```
[2021-04-21 08:00:45] [INFO] Reserve fcp device 1a13
[2021-04-21 08:00:45] [INFO] Reserve fcp device 1b14
[2021-04-21 08:00:46] [INFO] Got available fcp_list [('1a13', 'CBM5400C', 0, 1, 0, ''), ('1b14', 'CBM5400C', 0, 1, 1, '')] in Reserve mode from CBM5400C.
[2021-04-21 08:00:46] [INFO] Found allocated fcps [('1a13', 'CBM5400C', 0, 1, 0, ''), ('1b14', 'CBM5400C', 0, 1, 1, '')] for CBM5400C, will reuse them.
[2021-04-21 08:00:46] [INFO] Reserve fcp device 1a13
[2021-04-21 08:00:46] [INFO] Reserve fcp device 1b14
[2021-04-21 08:00:46] [INFO] Got available fcp_list [('1a13', 'CBM5400C', 0, 1, 0, ''), ('1b14', 'CBM5400C', 0, 1, 1, '')] in Reserve mode from CBM5400C.
[2021-04-21 08:00:46] [INFO] Found allocated fcps [('1a13', 'CBM5400C', 0, 1, 0, ''), ('1b14', 'CBM5400C', 0, 1, 1, '')] for CBM5400C, will reuse them.
[2021-04-21 08:00:46] [INFO] Reserve fcp device 1a13
[2021-04-21 08:00:46] [INFO] Reserve fcp device 1b14
[2021-04-21 08:00:47] [INFO] get_volume_connector returns {'zvm_fcp': ['1a13', '1b14'], 'wwpns': ['c05076de33000377', 'c05076de33000373'], 'host': 'BOEM5401'} for CBM5400C
[2021-04-21 08:00:48] [INFO] get_volume_connector returns {'zvm_fcp': ['1a13', '1b14'], 'wwpns': ['c05076de33000377', 'c05076de33000373'], 'host': 'BOEM5401'} for CBM5400C
[2021-04-21 08:00:48] [INFO] get_volume_connector returns {'zvm_fcp': ['1a13', '1b14'], 'wwpns': ['c05076de33000377', 'c05076de33000373'], 'host': 'BOEM5401'} for CBM5400C
[2021-04-21 08:00:48] [INFO] get_volume_connector returns {'zvm_fcp': ['1a13', '1b14'], 'wwpns': ['c05076de33000377', 'c05076de33000373'], 'host': 'BOEM5401'} for CBM5400C
[2021-04-21 08:00:51] [INFO] Start to attach volume to FCP devices ['1a13', '1b14'] on machine CBM5400C.
[2021-04-21 08:00:53] [INFO] Start to dedicate FCP 1a13 to CBM5400C.
[2021-04-21 08:00:54] [INFO] Start to attach volume to FCP devices ['1a13', '1b14'] on machine CBM5400C.
[2021-04-21 08:00:55] [INFO] Start to attach volume to FCP devices ['1a13', '1b14'] on machine CBM5400C.
[2021-04-21 08:00:55] [INFO] FCP 1a13 dedicated to CBM5400C isdone.
[2021-04-21 08:00:55] [INFO] Start to dedicate FCP 1b14 to CBM5400C.
[2021-04-21 08:00:56] [INFO] This is not the first volume for FCP 1a13, skip dedicating FCP device.
[2021-04-21 08:00:56] [INFO] This is not the first volume for FCP 1b14, skip dedicating FCP device.
[2021-04-21 08:00:56] [INFO] Begin to configure volume (WWPN:['0x5005076306031388', '0x5005076306035388', '0x5005076306039388', '0x500507630603D388', '0x5005076306081388', '0x5005076306085388', '0x5005076306089388', '0x500507630608D388', '0x5005076306101388', '0x5005076306105388', '0x5005076306109388', '0x500507630610D388', '0x5005076306131388', '0x5005076306135388', '0x5005076306139388', '0x500507630613D388', '0x5005076306181388', '0x5005076306185388', '0x5005076306189388', '0x500507630618D388', '0x50050763061B1388', '0x50050763061B5388', '0x50050763061B9388', '0x50050763061BD388'], LUN:0x4001403800000000) on the target machine CBM5400C with FCP devices ['1a13', '1b14'].
[2021-04-21 08:00:57] [INFO] This is not the first volume for FCP 1a13, skip dedicating FCP device.
[2021-04-21 08:00:57] [INFO] This is not the first volume for FCP 1b14, skip dedicating FCP device.
[2021-04-21 08:00:57] [INFO] Begin to configure volume (WWPN:['0x500507680B24BAC6', '0x500507680B23BAC6', '0x500507680B21BAC6', '0x500507680B22BAC6', '0x500507680B24BAC7', '0x500507680B22BAC7', '0x500507680B21BAC7', '0x500507680B23BAC7'], LUN:0x0001000000000000) on the target machine CBM5400C with FCP devices ['1a13', '1b14'].
[2021-04-21 08:00:58] [INFO] FCP 1b14 dedicated to CBM5400C isdone.
[2021-04-21 08:00:58] [INFO] Begin to configure volume (WWPN:['0x500507680B24BAC6', '0x500507680B23BAC6', '0x500507680B21BAC6', '0x500507680B22BAC6', '0x500507680B24BAC7', '0x500507680B22BAC7', '0x500507680B21BAC7', '0x500507680B23BAC7'], LUN:0x0000000000000000) on the target machine CBM5400C with FCP devices ['1a13', '1b14'].
[2021-04-21 08:01:04] [INFO] Start to attach volume to FCP devices ['1a13', '1b14'] on machine CBM5400C.
[2021-04-21 08:01:06] [INFO] This is not the first volume for FCP 1a13, skip dedicating FCP device.
[2021-04-21 08:01:06] [INFO] This is not the first volume for FCP 1b14, skip dedicating FCP device.
[2021-04-21 08:01:06] [INFO] Begin to configure volume (WWPN:['0x5005076306031388', '0x5005076306035388', '0x5005076306039388', '0x500507630603D388', '0x5005076306081388', '0x5005076306085388', '0x5005076306089388', '0x500507630608D388', '0x5005076306101388', '0x5005076306105388', '0x5005076306109388', '0x500507630610D388', '0x5005076306131388', '0x5005076306135388', '0x5005076306139388', '0x500507630613D388', '0x5005076306181388', '0x5005076306185388', '0x5005076306189388', '0x500507630618D388', '0x50050763061B1388', '0x50050763061B5388', '0x50050763061B9388', '0x50050763061BD388'], LUN:0x4015400800000000) on the target machine CBM5400C with FCP devices ['1a13', '1b14'].
[2021-04-21 08:01:15] [INFO] Configuration of volume (WWPN:['0x5005076306031388', '0x5005076306035388', '0x5005076306039388', '0x500507630603D388', '0x5005076306081388', '0x5005076306085388', '0x5005076306089388', '0x500507630608D388', '0x5005076306101388', '0x5005076306105388', '0x5005076306109388', '0x500507630610D388', '0x5005076306131388', '0x5005076306135388', '0x5005076306139388', '0x500507630613D388', '0x5005076306181388', '0x5005076306185388', '0x5005076306189388', '0x500507630618D388', '0x50050763061B1388', '0x50050763061B5388', '0x50050763061B9388', '0x50050763061BD388'], LUN:0x4001403800000000) on the target machine CBM5400C with FCP devices ['1a13', '1b14'] is done.
[2021-04-21 08:01:15] [INFO] Attaching volume to FCP devices ['1a13', '1b14'] on machine CBM5400C is done.
[2021-04-21 08:01:16] [INFO] Configuration of volume (WWPN:['0x500507680B24BAC6', '0x500507680B23BAC6', '0x500507680B21BAC6', '0x500507680B22BAC6', '0x500507680B24BAC7', '0x500507680B22BAC7', '0x500507680B21BAC7', '0x500507680B23BAC7'], LUN:0x0001000000000000) on the target machine CBM5400C with FCP devices ['1a13', '1b14'] is done.
[2021-04-21 08:01:16] [INFO] Attaching volume to FCP devices ['1a13', '1b14'] on machine CBM5400C is done.
[2021-04-21 08:01:16] [INFO] Configuration of volume (WWPN:['0x5005076306031388', '0x5005076306035388', '0x5005076306039388', '0x500507630603D388', '0x5005076306081388', '0x5005076306085388', '0x5005076306089388', '0x500507630608D388', '0x5005076306101388', '0x5005076306105388', '0x5005076306109388', '0x500507630610D388', '0x5005076306131388', '0x5005076306135388', '0x5005076306139388', '0x500507630613D388', '0x5005076306181388', '0x5005076306185388', '0x5005076306189388', '0x500507630618D388', '0x50050763061B1388', '0x50050763061B5388', '0x50050763061B9388', '0x50050763061BD388'], LUN:0x4015400800000000) on the target machine CBM5400C with FCP devices ['1a13', '1b14'] is done.
[2021-04-21 08:01:16] [INFO] Attaching volume to FCP devices ['1a13', '1b14'] on machine CBM5400C is done.
[2021-04-21 08:01:16] [INFO] Configuration of volume (WWPN:['0x500507680B24BAC6', '0x500507680B23BAC6', '0x500507680B21BAC6', '0x500507680B22BAC6', '0x500507680B24BAC7', '0x500507680B22BAC7', '0x500507680B21BAC7', '0x500507680B23BAC7'], LUN:0x0000000000000000) on the target machine CBM5400C with FCP devices ['1a13', '1b14'] is done.
[2021-04-21 08:01:16] [INFO] Attaching volume to FCP devices ['1a13', '1b14'] on machine CBM5400C is done.

```

2021-04-21 12:10 UTC, SharpRazor commented
the log in zvmsdk.log for detaching 1 volumes after applying this PR:
```
[2021-04-21 08:09:20] [INFO] Start to detach volume on machine CBM5400C from FCP devices ['1a13', '1b14']
[2021-04-21 08:09:20] [INFO] Begin to deconfigure volume (WWPN:['0x500507680B24BAC6', '0x500507680B23BAC6', '0x500507680B21BAC6', '0x500507680B22BAC6', '0x500507680B24BAC7', '0x500507680B22BAC7', '0x500507680B21BAC7', '0x500507680B23BAC7'], LUN:0x0000000000000000) on the target machine CBM5400C with FCP devices ['1a13', '1b14'].
[2021-04-21 08:09:21] [INFO] Deconfiguration of volume (WWPN:['0x500507680B24BAC6', '0x500507680B23BAC6', '0x500507680B21BAC6', '0x500507680B22BAC6', '0x500507680B24BAC7', '0x500507680B22BAC7', '0x500507680B21BAC7', '0x500507680B23BAC7'], LUN:0x0000000000000000) on the target machine CBM5400C with FCP devices ['1a13', '1b14'] is done.
[2021-04-21 08:09:21] [INFO] Found still have volumes on FCP 1a13, skip undedicating FCP device.
[2021-04-21 08:09:21] [INFO] Found still have volumes on FCP 1b14, skip undedicating FCP device.
[2021-04-21 08:09:21] [INFO] Detaching volume on machine CBM5400C from FCP devices ['1a13', '1b14'] is done.
[2021-04-21 08:09:23] [INFO] Got available fcp_list [('1a13', 'CBM5400C', 3, 1, 0, ''), ('1b14', 'CBM5400C', 3, 1, 1, '')] in Unreserve mode from CBM5400C.
[2021-04-21 08:09:25] [INFO] get_volume_connector returns {'zvm_fcp': ['1a13', '1b14'], 'wwpns': ['c05076de33000377', 'c05076de33000373'], 'host': 'BOEM5401'} for CBM5400C
```

2021-04-23 10:27 UTC, dongyanyang approved these changes

2021-04-23 10:30 UTC, merged

2021-04-23 10:30 UTC, dongyanyang commented
@jichenjc @bjhuangr please help to review and merge, thanks!