add API rollback_fcp_usage
openmainframeproject/feilong pull request #459
Opened 2021-05-07 10:05 UTC by SharpRazor

this API is used to set connections and reserved values
in database when initialize_connection or terminate_connection fail.

Signed-off-by: SharpRazor <bjcb@cn.ibm.com>

2021-05-11 02:36 UTC, bjhuangr reviewed
A general comment: Instead of add new rollback API, can we add new APIs like fcp reserve/unreserve/usageUpdate ?

2021-05-11 02:36 UTC, bjhuangr commented on zvmsdk/volumeop.py
> +        if isinstance(is_attach, str):
with `is_attach` type defined as boolean type in wsgi parameter schema is not enough?

2021-05-11 03:32 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +        if isinstance(is_attach, str):
when boolean type is transferred in HTTP message, it will be transformed into a string type.

2021-05-17 03:32 UTC, dongyanyang requested changes

2021-05-17 03:32 UTC, dongyanyang commented on zvmconnector/restclient.py
> +    url = '/volumes/get_fcp_usage/%s'
my thought:
update the url  /volumes/fcp/%s
the set_fcp_usage: use the PUT or POST? (refer to other APIs)
the get_fcp_usage: use the GET method

2021-05-17 03:32 UTC, dongyanyang commented on zvmsdk/api.py
> +        :param str fcp: the fcp ID of FCP device
add the info of return value.

2021-05-17 03:32 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        if not is_root_volume and \
move this guest_exists check after the line 927-930, then you won't need to add the 'not is_root_volume' condition.

2021-05-17 04:34 UTC, dongyanyang requested changes

2021-05-17 04:34 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        LOG.info('Enter get_fcp_usage...')
add more info if you want to keep this log

2021-05-17 04:34 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        connections = self.db.get_connections_from_fcp(fcp)
suggest to use one db query to return both reserve and connections.

2021-05-17 04:34 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        self.db.update_usage(fcp, connections)
suggest to use one db cmd to update reserve and connections together.

2021-05-17 14:18 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +        self.db.update_usage(fcp, connections)
done.

2021-05-17 14:18 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +        connections = self.db.get_connections_from_fcp(fcp)
done.

2021-05-17 14:19 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +        LOG.info('Enter get_fcp_usage...')
done.

2021-05-17 14:20 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +        if not is_root_volume and \
done.

2021-05-17 14:20 UTC, SharpRazor commented on zvmconnector/restclient.py
> +    url = '/volumes/get_fcp_usage/%s'
done.

2021-05-18 03:14 UTC, SharpRazor commented on zvmsdk/api.py
> +        :param str fcp: the fcp ID of FCP device
done.

2021-05-18 05:22 UTC, dongyanyang commented on doc/source/restapi.rst
> +**GET /volumes/fcp/{userid}?fcp={fcp}**
It is wierd to me to have the userid in this GET request as we already have the fcp parameter.

2021-05-18 05:22 UTC, dongyanyang commented on doc/source/restapi.rst
> +**PUT /volumes/fcp/{userid}**
{userid}? the target should be an FCP

2021-05-18 11:59 UTC, SharpRazor commented on doc/source/restapi.rst
> +**GET /volumes/fcp/{userid}?fcp={fcp}**
done.

2021-05-18 11:59 UTC, SharpRazor commented on doc/source/restapi.rst
> +**PUT /volumes/fcp/{userid}**
done.

2021-05-19 01:58 UTC, dongyanyang approved these changes

2021-05-19 02:01 UTC, merged