[master]Add restart action after catpure active VM completed successfully.
openmainframeproject/feilong pull request #464
Opened 2021-05-25 07:34 UTC by wngzhe

code change:
1. Add VM start operation after capture active VM completed successful.
2. change unit test cases.

2021-05-25 08:07 UTC, jichenjc commented on zvmsdk/smtclient.py
> +            restart_flag = True
what about a paused VM?

2021-05-25 08:07 UTC, jichenjc commented on zvmsdk/smtclient.py
> +            # keep restart flag used after capture.
should we init the restart flag at beginning ? or we are sure this flag will be inited anyway?

2021-05-25 09:14 UTC, wngzhe commented on zvmsdk/smtclient.py
> +            restart_flag = True
I will get status restore function to make sure status keep same,,,

2021-05-26 01:48 UTC, wngzhe commented on zvmsdk/smtclient.py
> +            # keep restart flag used after capture.
we have 2 branches for get_guest_connection_status, both branch has set flags,  
flag will be inited any way,

2021-05-26 03:12 UTC, wngzhe commented on zvmsdk/smtclient.py
> +            restart_flag = True
so far we can't get  pause vm status precisly , we just check  power status ,all VM with power status  on  will be  stop before capture and start after capture ,  power off status VM will not start, 
bu this we can make active vm and shutoff vm status same before capture as after capture,
but for pause vm , after capture vm ,the VM will be start.

2021-05-31 06:36 UTC, bjhuangr requested changes

2021-05-31 06:36 UTC, bjhuangr commented on zvmsdk/smtclient.py
> +                self.guest_softstop(userid)
if not reachable but power state on, then softstop will not work

2021-05-31 07:51 UTC, SeanHQF commented on zvmsdk/smtclient.py
> +                self.guest_softstop(userid)
@wngzhe Then a reachable check is needed?

2021-06-01 08:51 UTC, wngzhe commented on zvmsdk/smtclient.py
> +                self.guest_softstop(userid)
will change to guest_stop

2021-06-03 03:36 UTC, bjhuangr approved these changes
LGTM

2021-06-03 03:39 UTC, merged