[master]Set cache for volumes list of the host
openmainframeproject/feilong pull request #466
Opened 2021-05-26 09:00 UTC by trenxiaof

Signed-off-by: Xiao Feng Ren <renxiaof@linux.vnet.ibm.com>

2021-05-26 09:00 UTC, trenxiaof commented
@bjhuangr @haoqf  please help review.

2021-06-04 01:40 UTC, trenxiaof commented
@bjhuangr @SeanHQF please help review. have verified locally.

2021-06-04 01:57 UTC, jichenjc commented on zvmsdk/hostops.py
> +            return self._volumes
i don't have too much background of this PR
my question is if disk pool changes, what's the action to sync ?

before that question clear to me ,I want to hold this

2021-06-04 02:12 UTC, SeanHQF commented on zvmsdk/hostops.py
> +            return self._volumes
I think disk pool change will cause the service restart and the cache cleaned

2021-06-04 02:14 UTC, jichenjc commented on zvmsdk/hostops.py
> +            return self._volumes
no, adding disk is done in z/VM layer
how can we detect that?

2021-06-04 03:02 UTC, trenxiaof commented on zvmsdk/hostops.py
> +            return self._volumes
> i don't have too much background of this PR
> my question is if disk pool changes, what's the action to sync ?
> 
> before that question clear to me ,I want to hold this

if the sdkserver not retart, the cache couldn't sync the latest disk_pool

2021-06-04 03:07 UTC, SeanHQF commented on zvmsdk/hostops.py
> +            return self._volumes
Either request the user to restart zCC or add expire in cache

2021-06-04 03:12 UTC, jichenjc commented on zvmsdk/hostops.py
> +            return self._volumes
>>>if the sdkserver not retart, the cache couldn't sync the latest disk_pool

that's the concern , if we have no other ways , we need well prepare for such case
add disk is something not rare..

2021-06-04 03:16 UTC, SeanHQF commented on zvmsdk/hostops.py
> +            return self._volumes
Can we set this as a limitation since it only impacts onboarding?

2021-06-29 23:49 UTC, SeanHQF commented on zvmsdk/hostops.py
> +        self._volumes = {}
should _volumes = None

2021-06-30 02:34 UTC, trenxiaof commented
@jichenjc @SeanHQF  please help review. have tested locally

2021-06-30 06:45 UTC, SeanHQF approved these changes

2021-06-30 06:49 UTC, SeanHQF commented
@trenxiaof pls solve the conflict, thanks

2021-06-30 12:14 UTC, SeanHQF commented
@trenxiaof CI failed.

2021-07-01 02:59 UTC, SeanHQF commented
@jichenjc can you help review? thanks

2021-07-01 03:03 UTC, jichenjc commented
@bjhuangr can you help check this?

2021-07-01 07:46 UTC, bjhuangr requested changes

2021-07-01 07:46 UTC, bjhuangr commented on zvmsdk/hostops.py
> +                with zvmutils.expect_invalid_resp_data(self._volumes):
with zvmutils.expect_invalid_resp_data() not helps

2021-07-01 07:46 UTC, bjhuangr commented on zvmsdk/hostops.py
> +            with zvmutils.expect_invalid_resp_data(self._volumes):
ditto

2021-11-01 02:18 UTC, bjhuangr commented
@trenxiaof any plan to update this patch?

2021-11-01 05:15 UTC, trenxiaof commented
> @trenxiaof any plan to update this patch?

Yes, will update it with your comments

2021-11-16 09:32 UTC, trenxiaof commented
@huangrui add self.disk_pool to save the old disk_pool, if the disk_pool in the config file or called are  changed, the volumes list will be updated for this new disk_pool.

2021-11-29 01:47 UTC, trenxiaof commented
@bjhuangr please help review

2021-11-30 05:18 UTC, bjhuangr approved these changes

2021-11-30 05:19 UTC, merged