permanently remove lun when detach volumes
openmainframeproject/feilong pull request #471
Opened 2021-06-07 12:57 UTC by SharpRazor

Signed-off-by: SharpRazor <bjcb@cn.ibm.com>

2021-06-08 01:54 UTC, SharpRazor commented
#### 1. attach 3 volumes to rhel8 vm
```
[root@rhel82-eckd ~]# lszfcp -HD
0.0.1a13 host0
0.0.1b11 host1
0.0.1a13/0x500507680b23bac6/0x0000000000000000 0:0:10:0
0.0.1a13/0x500507680b23bac6/0x0001000000000000 0:0:10:1
0.0.1a13/0x500507680b23bac6/0x0002000000000000 0:0:10:2
0.0.1a13/0x500507680b24bac6/0x0000000000000000 0:0:11:0
0.0.1a13/0x500507680b24bac6/0x0001000000000000 0:0:11:1
0.0.1a13/0x500507680b24bac6/0x0002000000000000 0:0:11:2
0.0.1a13/0x500507680b21bac7/0x0000000000000000 0:0:3:0
0.0.1a13/0x500507680b21bac7/0x0001000000000000 0:0:3:1
0.0.1a13/0x500507680b21bac7/0x0002000000000000 0:0:3:2
0.0.1a13/0x500507680b24bac7/0x0000000000000000 0:0:4:0
0.0.1a13/0x500507680b24bac7/0x0001000000000000 0:0:4:1
0.0.1a13/0x500507680b24bac7/0x0002000000000000 0:0:4:2
0.0.1a13/0x500507680b23bac7/0x0000000000000000 0:0:5:0
0.0.1a13/0x500507680b23bac7/0x0001000000000000 0:0:5:1
0.0.1a13/0x500507680b23bac7/0x0002000000000000 0:0:5:2
0.0.1a13/0x500507680b21bac6/0x0000000000000000 0:0:9:0
0.0.1a13/0x500507680b21bac6/0x0001000000000000 0:0:9:1
0.0.1a13/0x500507680b21bac6/0x0002000000000000 0:0:9:2
0.0.1b11/0x500507680b22bac7/0x0000000000000000 1:0:0:0
0.0.1b11/0x500507680b22bac7/0x0001000000000000 1:0:0:1
0.0.1b11/0x500507680b22bac7/0x0002000000000000 1:0:0:2
0.0.1b11/0x500507680b22bac6/0x0000000000000000 1:0:1:0
0.0.1b11/0x500507680b22bac6/0x0001000000000000 1:0:1:1
0.0.1b11/0x500507680b22bac6/0x0002000000000000 1:0:1:2
[root@rhel82-eckd ~]#
[root@rhel82-eckd ~]# lszfcp -HD | wc -l
26
```

#### 2.detach 1 volume
```
[root@rhel82-eckd ~]# lszfcp -HD | wc -l
18
[root@rhel82-eckd ~]# lszfcp -HD
0.0.1a13 host0
0.0.1b11 host1
0.0.1a13/0x500507680b23bac6/0x0000000000000000 0:0:10:0
0.0.1a13/0x500507680b23bac6/0x0002000000000000 0:0:10:2
0.0.1a13/0x500507680b24bac6/0x0000000000000000 0:0:11:0
0.0.1a13/0x500507680b24bac6/0x0002000000000000 0:0:11:2
0.0.1a13/0x500507680b21bac7/0x0000000000000000 0:0:3:0
0.0.1a13/0x500507680b21bac7/0x0002000000000000 0:0:3:2
0.0.1a13/0x500507680b24bac7/0x0000000000000000 0:0:4:0
0.0.1a13/0x500507680b24bac7/0x0002000000000000 0:0:4:2
0.0.1a13/0x500507680b23bac7/0x0000000000000000 0:0:5:0
0.0.1a13/0x500507680b23bac7/0x0002000000000000 0:0:5:2
0.0.1a13/0x500507680b21bac6/0x0000000000000000 0:0:9:0
0.0.1a13/0x500507680b21bac6/0x0002000000000000 0:0:9:2
0.0.1b11/0x500507680b22bac7/0x0000000000000000 1:0:0:0
0.0.1b11/0x500507680b22bac7/0x0002000000000000 1:0:0:2
0.0.1b11/0x500507680b22bac6/0x0000000000000000 1:0:1:0
0.0.1b11/0x500507680b22bac6/0x0002000000000000 1:0:1:2
[root@rhel82-eckd ~]#
```

2021-06-08 03:52 UTC, dongyanyang requested changes

2021-06-08 03:52 UTC, dongyanyang commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +        echo "auto lun scan is disabled, manully deconfigure LUN $lun and WWPN $wwpn on FCP device $fcp"
1. remove "auto lun scan is disabled" since you removed the condition check
2. The ActiveWWPNs may include WWPNs of different storage providers, eg, when a vm attached both v7k and ds8k volume, when you detaching a v7k volume, the ActiveWWPNs also include DS8K ports.  Will the unit_remove report lots of errors in the system log of guest?

2021-06-08 03:52 UTC, dongyanyang commented on zvmsdk/volumeops/templates/rhel8_detach_volume.j2
> +        chzdev -d zfcp-lun 0.0.$fcp:$wwpn:$lun --force
same comment to the unit_remove, error log for WWPNs of other SP?

2021-06-08 06:15 UTC, SharpRazor commented
### SLES15 
#### 1. attach 3 volumes
```
sles15sp2:~ # lszfcp -HD
0.0.1a10 host0
0.0.1b14 host1
0.0.1a10/0x500507680b21bac6/0x0000000000000000 0:0:3:0
0.0.1a10/0x500507680b21bac6/0x0001000000000000 0:0:3:1
0.0.1a10/0x500507680b21bac6/0x0002000000000000 0:0:3:2
0.0.1a10/0x500507680b21bac7/0x0000000000000000 0:0:4:0
0.0.1a10/0x500507680b21bac7/0x0001000000000000 0:0:4:1
0.0.1a10/0x500507680b21bac7/0x0002000000000000 0:0:4:2
0.0.1a10/0x500507680b23bac6/0x0000000000000000 0:0:6:0
0.0.1a10/0x500507680b23bac6/0x0001000000000000 0:0:6:1
0.0.1a10/0x500507680b23bac6/0x0002000000000000 0:0:6:2
0.0.1a10/0x500507680b23bac7/0x0000000000000000 0:0:7:0
0.0.1a10/0x500507680b23bac7/0x0001000000000000 0:0:7:1
0.0.1a10/0x500507680b23bac7/0x0002000000000000 0:0:7:2
0.0.1a10/0x500507680b24bac6/0x0000000000000000 0:0:8:0
0.0.1a10/0x500507680b24bac6/0x0001000000000000 0:0:8:1
0.0.1a10/0x500507680b24bac6/0x0002000000000000 0:0:8:2
0.0.1a10/0x500507680b24bac7/0x0000000000000000 0:0:9:0
0.0.1a10/0x500507680b24bac7/0x0001000000000000 0:0:9:1
0.0.1a10/0x500507680b24bac7/0x0002000000000000 0:0:9:2
0.0.1b14/0x500507680b22bac6/0x0000000000000000 1:0:0:0
0.0.1b14/0x500507680b22bac6/0x0001000000000000 1:0:0:1
0.0.1b14/0x500507680b22bac6/0x0002000000000000 1:0:0:2
0.0.1b14/0x500507680b22bac7/0x0000000000000000 1:0:1:0
0.0.1b14/0x500507680b22bac7/0x0001000000000000 1:0:1:1
0.0.1b14/0x500507680b22bac7/0x0002000000000000 1:0:1:2
sles15sp2:~ # lszfcp -HD | wc -l
26
```

#### 2.detach 1 volume
```
sles15sp2:~ # lszfcp -HD | wc -l
18
sles15sp2:~ # lszfcp -HD
0.0.1a10 host0
0.0.1b14 host1
0.0.1a10/0x500507680b21bac6/0x0000000000000000 0:0:3:0
0.0.1a10/0x500507680b21bac6/0x0001000000000000 0:0:3:1
0.0.1a10/0x500507680b21bac7/0x0000000000000000 0:0:4:0
0.0.1a10/0x500507680b21bac7/0x0001000000000000 0:0:4:1
0.0.1a10/0x500507680b23bac6/0x0000000000000000 0:0:6:0
0.0.1a10/0x500507680b23bac6/0x0001000000000000 0:0:6:1
0.0.1a10/0x500507680b23bac7/0x0000000000000000 0:0:7:0
0.0.1a10/0x500507680b23bac7/0x0001000000000000 0:0:7:1
0.0.1a10/0x500507680b24bac6/0x0000000000000000 0:0:8:0
0.0.1a10/0x500507680b24bac6/0x0001000000000000 0:0:8:1
0.0.1a10/0x500507680b24bac7/0x0000000000000000 0:0:9:0
0.0.1a10/0x500507680b24bac7/0x0001000000000000 0:0:9:1
0.0.1b14/0x500507680b22bac6/0x0000000000000000 1:0:0:0
0.0.1b14/0x500507680b22bac6/0x0001000000000000 1:0:0:1
0.0.1b14/0x500507680b22bac7/0x0000000000000000 1:0:1:0
0.0.1b14/0x500507680b22bac7/0x0001000000000000 1:0:1:1
sles15sp2:~ #
```

2021-06-08 06:36 UTC, SharpRazor commented
### UBUNTU
#### 1. attach 3 volumes
```
dummyuser@ubuntu20:~$ lszfcp -HD
0.0.1a12 host0
0.0.1b13 host1
0.0.1a12/0x500507680b21bac7/0x0000000000000000 0:0:1:0
0.0.1a12/0x500507680b21bac7/0x0001000000000000 0:0:1:1
0.0.1a12/0x500507680b21bac7/0x0002000000000000 0:0:1:2
0.0.1a12/0x500507680b21bac6/0x0000000000000000 0:0:4:0
0.0.1a12/0x500507680b21bac6/0x0001000000000000 0:0:4:1
0.0.1a12/0x500507680b21bac6/0x0002000000000000 0:0:4:2
0.0.1b13/0x500507680b22bac7/0x0000000000000000 1:0:1:0
0.0.1b13/0x500507680b22bac7/0x0001000000000000 1:0:1:1
0.0.1b13/0x500507680b22bac7/0x0002000000000000 1:0:1:2
0.0.1b13/0x500507680b22bac6/0x0000000000000000 1:0:2:0
0.0.1b13/0x500507680b22bac6/0x0001000000000000 1:0:2:1
0.0.1b13/0x500507680b22bac6/0x0002000000000000 1:0:2:2
dummyuser@ubuntu20:~$
dummyuser@ubuntu20:~$ lszfcp -HD | wc -l
14
```

#### 2. detach 1st volume
```
dummyuser@ubuntu20:~$ lszfcp -HD
0.0.1a12 host0
0.0.1b13 host1
0.0.1a12/0x500507680b21bac7/0x0001000000000000 0:0:1:1
0.0.1a12/0x500507680b21bac7/0x0002000000000000 0:0:1:2
0.0.1a12/0x500507680b21bac6/0x0001000000000000 0:0:4:1
0.0.1a12/0x500507680b21bac6/0x0002000000000000 0:0:4:2
0.0.1b13/0x500507680b22bac7/0x0001000000000000 1:0:1:1
0.0.1b13/0x500507680b22bac7/0x0002000000000000 1:0:1:2
0.0.1b13/0x500507680b22bac6/0x0001000000000000 1:0:2:1
0.0.1b13/0x500507680b22bac6/0x0002000000000000 1:0:2:2
dummyuser@ubuntu20:~$
dummyuser@ubuntu20:~$ lszfcp -HD | wc -l
10
dummyuser@ubuntu20:~$
```

#### 3. detach 2nd volume
```
dummyuser@ubuntu20:~$ lszfcp -HD
0.0.1a12 host0
0.0.1b13 host1
0.0.1a12/0x500507680b21bac7/0x0002000000000000 0:0:1:2
0.0.1a12/0x500507680b21bac6/0x0002000000000000 0:0:4:2
0.0.1b13/0x500507680b22bac7/0x0002000000000000 1:0:1:2
0.0.1b13/0x500507680b22bac6/0x0002000000000000 1:0:2:2
dummyuser@ubuntu20:~$ lszfcp -HD | wc -l
6
dummyuser@ubuntu20:~$
```

#### 4.detach last volume
```
dummyuser@ubuntu20:~$ lszfcp -HD
Error: No fcp devices found.
```

2021-06-08 07:15 UTC, SharpRazor commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +        echo "auto lun scan is disabled, manully deconfigure LUN $lun and WWPN $wwpn on FCP device $fcp"
per my latest test, this changes doesn't work on RHEL7.
will report errors like:
```
Jun  8 01:59:31 rhel77-small zvmguestconfigure: auto lun scan is disabled, manully deconfigure LUN 0x0001000000000000 and WWPN 0x50050763061bd388 on FCP device 1a10
Jun  8 01:59:31 rhel77-small zvmguestconfigure: devol.sh: line 66: echo: write error: Invalid argument
Jun  8 01:59:31 rhel77-small zvmguestconfigure: auto lun scan is disabled, manully deconfigure LUN 0x0001000000000000 and WWPN 0x500507680b21bac6 on FCP device 1a10
Jun  8 01:59:31 rhel77-small zvmguestconfigure: devol.sh: line 66: echo: write error: Invalid argument
Jun  8 01:59:31 rhel77-small zvmguestconfigure: auto lun scan is disabled, manully deconfigure LUN 0x0001000000000000 and WWPN 0x500507680b21bac7 on FCP device 1a10
Jun  8 01:59:31 rhel77-small zvmguestconfigure: devol.sh: line 66: echo: write error: Invalid argument
```
As for the WWPNS include DS8K ports, I also do some tests on RHEL8, attach 3 SVC volumes and 1 DS8K volumes:
```
[root@rhel82-eckd 0.0.1a12]# lszfcp -HD
0.0.1a12 host0
0.0.1b11 host1
0.0.1a12/0x5005076306105388/0x4015403f00000000 0:0:1:1077886997
0.0.1a12/0x50050763061bd388/0x4015403f00000000 0:0:2:1077886997
0.0.1a12/0x500507680b21bac6/0x0000000000000000 0:0:3:0
0.0.1a12/0x500507680b21bac6/0x0001000000000000 0:0:3:1
0.0.1a12/0x500507680b21bac6/0x0002000000000000 0:0:3:2
0.0.1a12/0x500507680b21bac7/0x0000000000000000 0:0:5:0
0.0.1a12/0x500507680b21bac7/0x0001000000000000 0:0:5:1
0.0.1a12/0x500507680b21bac7/0x0002000000000000 0:0:5:2
0.0.1b11/0x5005076306035388/0x4015403f00000000 1:0:0:1077886997
0.0.1b11/0x500507680b22bac7/0x0000000000000000 1:0:1:0
0.0.1b11/0x500507680b22bac7/0x0001000000000000 1:0:1:1
0.0.1b11/0x500507680b22bac7/0x0002000000000000 1:0:1:2
0.0.1b11/0x500507680b22bac6/0x0000000000000000 1:0:2:0
0.0.1b11/0x500507680b22bac6/0x0001000000000000 1:0:2:1
0.0.1b11/0x500507680b22bac6/0x0002000000000000 1:0:2:2
[root@rhel82-eckd 0.0.1a12]#
[root@rhel82-eckd 0.0.1a12]# lszfcp -HD | wc -l
17
```

then detach 1 SVC volume:
```
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]: zFCP LUN 0.0.1a12:0x500507680b21bac7:0x0001000000000000 deconfigured
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]: zFCP LUN 0.0.1a12:0x500507680d060027:0x0001000000000000 deconfigured
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]: zFCP LUN 0.0.1a12:0x500507680d120027:0x0001000000000000 deconfigured
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]: zFCP LUN 0.0.1a12:0x500507680d760027:0x0001000000000000 deconfigured
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]: zFCP LUN 0.0.1a12:0x500507680d820027:0x0001000000000000 deconfigured
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]: remove WWPN 0x5005076306105388 for 1a12 in zfcp.conf
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]: remove WWPN 0x50050763061bd388 for 1a12 in zfcp.conf
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]: remove WWPN 0x500507680b21bac6 for 1a12 in zfcp.conf
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]: remove WWPN 0x500507680b21bac7 for 1a12 in zfcp.conf
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]: remove WWPN 0x500507680d060027 for 1a12 in zfcp.conf
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]: remove WWPN 0x500507680d120027 for 1a12 in zfcp.conf
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]: remove WWPN 0x500507680d760027 for 1a12 in zfcp.conf
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]: remove WWPN 0x500507680d820027 for 1a12 in zfcp.conf
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]: zFCP LUN 0.0.1b11:0x5005076306035388:0x0001000000000000 deconfigured
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]:    Warning: Auto LUN scan enabled - cannot permanently deconfigure LUN
Jun  8 03:11:31 rhel82-eckd kernel: scsi 1:0:2:1: alua: Detached
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]: zFCP LUN 0.0.1b11:0x500507680b22bac6:0x0001000000000000 deconfigured
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]:    Warning: Auto LUN scan enabled - cannot permanently deconfigure LUN
Jun  8 03:11:31 rhel82-eckd kernel: scsi 1:0:1:1: alua: Detached
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]: zFCP LUN 0.0.1b11:0x500507680b22bac7:0x0001000000000000 deconfigured
Jun  8 03:11:31 rhel82-eckd zvmguestconfigure[42877]: remove WWPN 0x5005076306035388 for 1b11 in zfcp.conf
[root@rhel82-eckd 0.0.1a12]# lszfcp -HD
0.0.1a12 host0
0.0.1b11 host1
0.0.1a12/0x5005076306105388/0x4015403f00000000 0:0:1:1077886997
0.0.1a12/0x50050763061bd388/0x4015403f00000000 0:0:2:1077886997
0.0.1a12/0x500507680b21bac6/0x0000000000000000 0:0:3:0
0.0.1a12/0x500507680b21bac6/0x0002000000000000 0:0:3:2
0.0.1a12/0x500507680b21bac7/0x0000000000000000 0:0:5:0
0.0.1a12/0x500507680b21bac7/0x0002000000000000 0:0:5:2
0.0.1b11/0x5005076306035388/0x4015403f00000000 1:0:0:1077886997
0.0.1b11/0x500507680b22bac7/0x0000000000000000 1:0:1:0
0.0.1b11/0x500507680b22bac7/0x0002000000000000 1:0:1:2
0.0.1b11/0x500507680b22bac6/0x0000000000000000 1:0:2:0
0.0.1b11/0x500507680b22bac6/0x0002000000000000 1:0:2:2
[root@rhel82-eckd 0.0.1a12]#
```

2021-06-09 11:39 UTC, SharpRazor commented
## detach script change test

#### 1. deploy a RHEL78 BFV instance

#### 2. attach another 2 SVC volumes to it

after attachment:

```
[root@rhel78-scsi ~]# lszfcp -HD
0.0.1a14 host0
0.0.1b13 host1
0.0.1a14/0x500507680b21bac6/0x0000000000000000 0:0:0:0
0.0.1a14/0x500507680b21bac6/0x0001000000000000 0:0:0:1
0.0.1a14/0x500507680b21bac6/0x0002000000000000 0:0:0:2
0.0.1a14/0x500507680b21bac7/0x0000000000000000 0:0:3:0
0.0.1a14/0x500507680b21bac7/0x0001000000000000 0:0:3:1
0.0.1a14/0x500507680b21bac7/0x0002000000000000 0:0:3:2
0.0.1b13/0x500507680b22bac7/0x0000000000000000 1:0:0:0
0.0.1b13/0x500507680b22bac7/0x0001000000000000 1:0:0:1
0.0.1b13/0x500507680b22bac7/0x0002000000000000 1:0:0:2
0.0.1b13/0x500507680b22bac6/0x0000000000000000 1:0:1:0
0.0.1b13/0x500507680b22bac6/0x0001000000000000 1:0:1:1
0.0.1b13/0x500507680b22bac6/0x0002000000000000 1:0:1:2
```



#### 3. detach 1st volume

```
[root@rhel78-scsi ~]# lszfcp -HD
0.0.1a14 host0
0.0.1b13 host1
0.0.1a14/0x500507680b21bac6/0x0000000000000000 0:0:0:0
0.0.1a14/0x500507680b21bac6/0x0001000000000000 0:0:0:1
0.0.1a14/0x500507680b21bac7/0x0000000000000000 0:0:3:0
0.0.1a14/0x500507680b21bac7/0x0001000000000000 0:0:3:1
0.0.1b13/0x500507680b22bac7/0x0000000000000000 1:0:0:0
0.0.1b13/0x500507680b22bac7/0x0001000000000000 1:0:0:1
0.0.1b13/0x500507680b22bac6/0x0000000000000000 1:0:1:0
0.0.1b13/0x500507680b22bac6/0x0001000000000000 1:0:1:1
```



#### 4. detach 2nd volume

```
[root@rhel78-scsi ~]# lszfcp -HD
0.0.1a14 host0
0.0.1b13 host1
0.0.1a14/0x500507680b21bac6/0x0000000000000000 0:0:0:0
0.0.1a14/0x500507680b21bac7/0x0000000000000000 0:0:3:0
0.0.1b13/0x500507680b22bac7/0x0000000000000000 1:0:0:0
0.0.1b13/0x500507680b22bac6/0x0000000000000000 1:0:1:0
[root@rhel78-scsi ~]#
```

#### 5. attach 1 volume again

```
[root@rhel78-scsi ~]# lszfcp -HD
0.0.1a14 host0
0.0.1b13 host1
0.0.1a14/0x500507680b21bac6/0x0000000000000000 0:0:0:0
0.0.1a14/0x500507680b21bac6/0x0001000000000000 0:0:0:1
0.0.1a14/0x500507680b21bac7/0x0000000000000000 0:0:3:0
0.0.1a14/0x500507680b21bac7/0x0001000000000000 0:0:3:1
0.0.1b13/0x500507680b22bac7/0x0000000000000000 1:0:0:0
0.0.1b13/0x500507680b22bac7/0x0001000000000000 1:0:0:1
0.0.1b13/0x500507680b22bac6/0x0000000000000000 1:0:1:0
0.0.1b13/0x500507680b22bac6/0x0001000000000000 1:0:1:1
[root@rhel78-scsi ~]#
[root@rhel78-scsi ~]# multipath -l
mpathc (3600507640083826de000000000006e80) dm-2 IBM     ,2145
size=1.0G features='1 queue_if_no_path' hwhandler='0' wp=rw
|-+- policy='service-time 0' prio=0 status=active
| |- 0:0:0:1 sde 8:64  active undef running
| `- 1:0:1:1 sdh 8:112 active undef running
`-+- policy='service-time 0' prio=0 status=enabled
  |- 0:0:3:1 sdf 8:80  active undef running
  `- 1:0:0:1 sdg 8:96  active undef running
mpatha (3600507640083826de000000000006e84) dm-0 IBM     ,2145
size=10G features='1 queue_if_no_path' hwhandler='0' wp=rw
|-+- policy='service-time 0' prio=0 status=active
| |- 0:0:3:0 sdd 8:48  active undef running
| `- 1:0:0:0 sda 8:0   active undef running
`-+- policy='service-time 0' prio=0 status=enabled
  |- 0:0:0:0 sdc 8:32  active undef running
  `- 1:0:1:0 sdb 8:16  active undef running
[root@rhel78-scsi ~]#
```

2021-06-10 08:02 UTC, dongyanyang approved these changes

2021-06-10 08:09 UTC, merged