continue to do the cleanup of multipath/FCP/lun when umount fails
openmainframeproject/feilong pull request #492
Opened 2021-07-15 08:26 UTC by dongyanyang

there are some case that the umount may fail, we should continue to do
the cleanup, otherwise the fcps/lun will be left on the compute node.

Signed-off-by: dyyang <dyyang@cn.ibm.com>

2021-07-16 07:03 UTC, dongyanyang commented
@jackydalong @bjhuangr @jichenjc pls review

2021-07-16 07:46 UTC, jackydalong commented on zthin-parts/zthin/bin/refresh_bootmap
>      # remove the temporary mount point dir
Add comment : rm will fail if try deleting an actively-mounted folder or its parent folders

2021-07-16 07:49 UTC, jackydalong approved these changes

2021-07-16 07:54 UTC, jichenjc commented on zthin-parts/zthin/bin/refresh_bootmap
>      inform "Successed to umount devNode $devNode from $deviceMountPoint"
will we print logs like following which might be confsuing?

Failed to Umount devNode $devNode from $deviceMountPoint. rc: $rc. out: $out
Successed to umount devNode $devNode from $deviceMountPoint

2021-07-19 01:33 UTC, bjhuangr requested changes

2021-07-19 01:33 UTC, bjhuangr commented on zthin-parts/zthin/bin/refresh_bootmap
>      # remove the temporary mount point dir
In some case, umount failed due to device busy, then I/O snyc complete, then `rm -rf` will remove all the content of the volume? If this is the case, suggest not `rm -rf` if umount failed.

2021-07-19 06:34 UTC, jackydalong commented on zthin-parts/zthin/bin/refresh_bootmap
> +      # If umount step failed, the device is still mounted. Then the `rm -rf` command will fail like:
change 
```
If umount step failed, the device is still mounted. Then 
```
to
```
If umount step failed, but the device is still mounted, then
```

2021-07-19 06:35 UTC, jackydalong commented on zthin-parts/zthin/bin/refresh_bootmap
> +      # rm: cannot remove 'test': Device or resource busy
change 
```
       # rm: cannot remove 'test': Device or resource busy
 ```
 to
 ```
        # rm: cannot remove 'mount_point': Device or resource busy
```

2021-07-19 07:57 UTC, jackydalong approved these changes
LGTM

2021-07-19 08:02 UTC, bjhuangr approved these changes

2021-07-19 08:02 UTC, merged