[WIP]remove dirty data in zfcp.conf
openmainframeproject/feilong pull request #503
Opened 2021-08-18 03:53 UTC by SharpRazor

remove the dirty data in /etc/zfcp.conf left in image

Signed-off-by: bjcb <bjcb@cn.ibm.com>

2021-08-18 06:48 UTC, SharpRazor commented
### test on rhel82
#### create a rhel82 bfv instance and attach a volume
the zfcp.conf content:
```
[root@rhel82-bfv ~]# cat /etc/zfcp.conf

0.0.5c07 0x5005076802400c1b 0x0001000000000000
0.0.5c07 0x5005076802400c1a 0x0001000000000000
0.0.5d0e 0x5005076802400c1b 0x0001000000000000
0.0.5d0e 0x5005076802400c1a 0x0001000000000000
[root@rhel82-bfv ~]#
```

#### capture to image

#### deploy and check the new zfcp.conf:
we can see that the content of  zfcp.conf was cleared:
```
[root@rhel82-capture-with-volume ~]# ll /etc/zfcp.conf
-rw-r--r--. 1 root root 1 Aug 18 02:45 /etc/zfcp.conf
[root@rhel82-capture-with-volume ~]# cat /etc/zfcp.conf

[root@rhel82-capture-with-volume ~]#
```
because we still not solve the purge reader problem, so the zfcp.conf do not have the new content.

2021-08-19 03:36 UTC, jackydalong commented
1. Move the 3 lines here
<img width="948" alt="image" src="https://user-images.githubusercontent.com/20807562/130003429-6f1fe154-d817-4fd7-9aec-2056d4102630.png">

because 
<img width="935" alt="image" src="https://user-images.githubusercontent.com/20807562/130003295-f11a71b7-7bfc-4e5c-90c7-96e88307462e.png">

2. Change `Clear` to `Purge` for the 2nd line
@SharpRazor

2021-08-19 05:43 UTC, SharpRazor commented
@jackydalong Hi, we need to know the OS version before purge zfcp.conf, because `sles` and `ubuntu` do not have zfcp.conf.
but the code of judging OS is  between line 805 and line 828, to avoid duplicated codes, so I wrote like this.

2021-08-19 07:58 UTC, jackydalong commented
> @jackydalong Hi, we need to know the OS version before purge zfcp.conf, because `sles` and `ubuntu` do not have zfcp.conf.
> but the code of judging OS is between line 805 and line 828, to avoid duplicated codes, so I wrote like this.

Agree, though currently BFV or refresh_bootmap is NOT supported for SLES and Ubuntu.

2021-08-20 05:04 UTC, SharpRazor commented
> > @jackydalong Hi, we need to know the OS version before purge zfcp.conf, because `sles` and `ubuntu` do not have zfcp.conf.
> > but the code of judging OS is between line 805 and line 828, to avoid duplicated codes, so I wrote like this.
> 
> Agree, though currently BFV or refresh_bootmap is NOT supported for SLES and Ubuntu.
> @SharpRazor
> ### Just a reminder : change `Clear` to `Purge` or `Clean` for the 2nd line
> 
> @SharpRazor

thanks, done.

2021-08-20 05:36 UTC, jackydalong approved these changes
LGTM

2021-08-24 10:24 UTC, dongyanyang requested changes

2021-08-24 10:24 UTC, dongyanyang commented on zthin-parts/zthin/bin/refresh_bootmap
> +      inform "Purge contents in ${deviceMountPoint}/etc/zfcp.conf"
1. move these change to after line 802. where we updated the fstab and cleared multipath bindings/wwids.
2. better to check whether the zfcp.conf file exists and writable with a "-r"

2021-08-24 10:25 UTC, dongyanyang commented
> @jackydalong Hi, we need to know the OS version before purge zfcp.conf, because `sles` and `ubuntu` do not have zfcp.conf.
> but the code of judging OS is between line 805 and line 828, to avoid duplicated codes, so I wrote like this.

just saw Jacky and your comments.
Your concern can be solved by adding a [[ if -r xxx ]] before your code. Only do the change when the file exists and readable.

2021-08-25 03:44 UTC, SharpRazor commented
@dongyanyang thanks, I have changed to use if statements.

2021-08-25 07:24 UTC, dongyanyang approved these changes
lgtm

2021-08-25 10:01 UTC, merged