Generate the physical and virtual wwpn map.
openmainframeproject/feilong pull request #515
Opened 2021-09-10 10:50 UTC by wgxoyun

Signed-off-by: wgxoyun@cn.ibm.com <wgxoyun@cn.ibm.com>

Generate the physical and virtual wwpn map.

2021-09-13 09:22 UTC, jackydalong commented on zvmsdk/volumeop.py
> +        phy_virt_map = {}
suggest changing
```
phy_virt_map
```
to 
```
phy_virt_wwpn_map
```

2021-09-13 09:25 UTC, jackydalong requested changes
Left one comment. Thx @wgxoyun

2021-09-13 09:33 UTC, jackydalong commented on zvmsdk/volumeop.py
> +            # to determine the proper zoning on the fabric.
Suggest append one line of comment as following:
```
Refer to #7039 for details about avoid creating zones on the fabric to which there is no fcp connected 
```

2021-09-15 09:28 UTC, dongyanyang approved these changes

2021-09-15 10:07 UTC, jackydalong approved these changes
LGTM

2021-09-15 14:41 UTC, merged