only update database when destroy instance
openmainframeproject/feilong pull request #518
Opened 2021-09-13 11:09 UTC by SharpRazor

only update database when destroy instance and no need rollback in some cases

related issue: https://github.ibm.com/zvc/planning/issues/7111#issuecomment-35536539
Signed-off-by: flytiger <flytiger@flytiger-PC.cn.ibm.com>

2021-09-13 12:07 UTC, jichenjc commented
is it possible to add some logic for the unit ? I think mostly it's not easy to test through FVT

2021-09-14 08:45 UTC, dongyanyang requested changes

2021-09-14 08:45 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            need_rollback = False
to be accurate, need to have a flag for each FCP device, so should be a list, or a dict combining together with fcp_connections. For example: fcp_info[fcp]= {connections: xx, need_rollback: yy}

2021-09-14 08:45 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                    with zvmutils.ignore_errors():
suggest to move the _add_disks out of ”if need_rollback“. we only want to avoid increase the fcp usage.

2021-09-14 08:45 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        update_database_only = connection_info.get('update_database_only',
I think the update_database_only is not that a proper name, it is not something of "connection info".
but I don't have a better one... So I will let it be what you proposed.

You need to double check whether the API schema needs to be updated.

2021-09-14 08:45 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        update_database_only = connection_info.get('update_database_only',
and better to give some explanation to the use scenario of update_database_only.

2021-09-15 03:50 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +            need_rollback = False
@dongyanyang done, please help review again.

2021-09-15 03:50 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +                    with zvmutils.ignore_errors():
done.

2021-09-15 03:51 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +        update_database_only = connection_info.get('update_database_only',
you are right, I change to `update_connections_only`, might sound better.

2021-09-15 03:51 UTC, SharpRazor commented
> is it possible to add some logic for the unit ? I think mostly it's not easy to test through FVT

yes, when local test passed, I will add unit test cases.

2021-09-15 07:59 UTC, SharpRazor commented
## test results
### 1. test rollback changes:
add exception:
```
        try:
            #raise exception.SDKBaseException(message='bill fake ex in zcc.',
            #        results={'rc': '401', 'rs': 9})
            self._remove_disks(fcp_list, assigner_id, target_wwpns, target_lun,
                               multipath, os_version, mount_point, connections)
            for fcp in fcp_list:
                if not fcp_connections.get(fcp, 0):
                    LOG.info("Start to undedicate FCP %s from "
                             "%s." % (fcp, assigner_id))
                    self._undedicate_fcp(fcp, assigner_id)
                    LOG.info("FCP %s undedicated from %s is "
                             "done." % (fcp, assigner_id))
                else:
                    LOG.info("Found still have volumes on FCP %s, "
                             "skip undedicating FCP device." % fcp)
        except (exception.SDKBaseException,
                exception.SDKSMTRequestFailed) as err:
```
then delete the instance with volumes attached:
```
[2021-09-15 03:53:16] [INFO] Begin to soft power off vm BJCB0012
[2021-09-15 03:53:17] [INFO] Complete soft power off vm BJCB0012
[2021-09-15 03:53:17] [INFO] Start to detach volume on machine BJCB0012 from FCP devices ['5c0a', '5d0e']
[2021-09-15 03:53:17] [ERROR] detach failed with error:bill fake ex in zcc.
[2021-09-15 03:53:17] [INFO] Rollback usage of fcp 5c0a on instance BJCB0012.
[2021-09-15 03:53:17] [INFO] After rollback, fcp usage of 5c0ais (assigner_id: BJCB0012, reserved:1, connections: 1).
[2021-09-15 03:53:17] [INFO] Rollback usage of fcp 5d0e on instance BJCB0012.
[2021-09-15 03:53:17] [INFO] After rollback, fcp usage of 5d0eis (assigner_id: BJCB0012, reserved:1, connections: 1).
```

### 2. test `update_connections_only`

2021-09-15 09:26 UTC, dongyanyang approved these changes
lgtm. Please continue to add UT case and fix CI error.

2021-09-16 02:15 UTC, merged