Add fcp into into hostops
openmainframeproject/feilong pull request #519
Opened 2021-09-15 06:14 UTC by jichenjc

2021-09-15 06:24 UTC, dongyanyang requested changes

2021-09-15 06:24 UTC, dongyanyang commented on zvmsdk/hostops.py
> +        LOG.info("Get fcp information: %s", ret)
don't need this log as the info is already logged inside get_all_fcp_usage.

2021-09-15 06:24 UTC, dongyanyang commented on zvmsdk/hostops.py
> +            if ret[key][1] == 0:
1. current return info does not contain the path info,should update the get_all_fcp_usage to also return the path info.
2. both connections=0 and reserved=0 should be satisfied to mark a FCP as free.

2021-09-15 06:28 UTC, bjhuangr commented
@jichenjc could you please add commit message that helps understanding why adding this?

2021-09-15 06:36 UTC, jichenjc commented on zvmsdk/hostops.py
> +            if ret[key][1] == 0:
do we need this path info in order to know it's free or not free?

2021-09-15 09:23 UTC, dongyanyang commented on zvmsdk/hostops.py
> +            if ret[key][1] == 0:
when displaying the free or total count, we should take the path info into consideration.
eg, user has two path, each path has 4 FCP devices available. Then the total free count should be 4 instead of 8, because each vm will occupy one FCP device from each path.

2021-09-15 09:27 UTC, jichenjc commented on zvmsdk/hostops.py
> +            if ret[key][1] == 0:
so can you help provide such info to be consumed ? I 
guess some internal function provide the info then my PR can consume your function..

2021-09-15 14:39 UTC, bjhuangr requested changes

2021-09-15 14:39 UTC, bjhuangr commented on zvmsdk/hostops.py
> +        ret = _volumeop.get_all_fcp_usage()
if no fcp list configured, need to handle SDKObjectNotExistError

2021-09-16 02:07 UTC, dongyanyang commented on zvmsdk/hostops.py
> +            if ret[key][1] == 0:
@jichenjc how about let @SharpRazor download your PR code and work further to address the comments?

2021-09-17 10:17 UTC, SharpRazor commented
new PR for this: https://github.com/openmainframeproject/feilong/pull/523

2021-09-27 01:02 UTC, bjhuangr commented
close this as #523 continued same change and merged

2021-09-27 01:02 UTC, closed without merging