Add fcp info into hostops
openmainframeproject/feilong pull request #523
Opened 2021-09-17 10:11 UTC by SharpRazor

Signed-off-by: jichenjc <jichenjc@cn.ibm.com>

2021-09-22 03:45 UTC, SharpRazor commented
## test results
### 0. get host info
```
>>> from zvmconnector import connector
>>> conn = connector.ZVMConnector('127.0.0.1', port=8080, token_path='/etc/zvmsdk/token.dat')
>>> conn.send_request('host_get_info')
{'overallRC': 0, 'modID': None, 'rc': 0, 'rs': 0, 'errmsg': '', 'output': {'zcc_userid': 'BJCBVM99', 'zvm_host': 'BOEIAAS1', 'vcpus': 12, 'vcpus_used': 12, 'cpu_info': {'architecture': 's390x', 'cec_model': '2964'}, 'memory_mb': 524288.0, 'memory_mb_used': 43929.6, 'hypervisor_type': 'zvm', 'hypervisor_version': 710, 'hypervisor_hostname': 'BOEIAAS1', 'ipl_time': 'IPL at 09/16/21 13:08:12 CES', 'fcp': {'0': {'free': 9, 'used': 1}, '1': {'free': 9, 'used': 1}}, 'disk_total': 1156, 'disk_used': 981, 'disk_available': 174}}
>>> 
```
### 1. database status
```

```
sqlite> select count(*) from fcp;
20
sqlite> select * from fcp;
5c0f|BJCB001A|0|0|0|
5c07|BJCB0014|0|0|0|
5c0d|BJCB001D|0|0|0|
5c0c|BJCB000e|0|0|0|
5c0b|BJCB0004|0|0|0|
5c09|BJCB0016|0|0|0|
5c08|BJCB001E|1|1|0|
5c0a|BJCB0012|0|0|0|
5c0e|BJCB0013|0|0|0|
5c06|BJCB001B|0|0|0|
5d08|BJCB0017|0|0|1|
5d0b|BJCB0004|0|0|1|
5d09|BJCB0016|0|0|1|
5d0c|BJCB0014|0|0|1|
5d0e|BJCB0012|0|0|1|
5d0d|BJCB001B|0|0|1|
5d0f|BJCB001D|0|0|1|
5d0a|BJCB0015|0|0|1|
5d06|BJCB001A|0|0|1|
5d07|BJCB001E|1|1|1|
sqlite> 
```
### 2. reserve one FCP
```
sqlite> update fcp set reserved=1 where fcp_id='5c0f';
sqlite> 
```
### 3. get host info again
```
>>> conn.send_request('host_get_info')
{'overallRC': 0, 'modID': None, 'rc': 0, 'rs': 0, 'errmsg': '', 'output': {'zcc_userid': 'BJCBVM99', 'zvm_host': 'BOEIAAS1', 'vcpus': 12, 'vcpus_used': 12, 'cpu_info': {'architecture': 's390x', 'cec_model': '2964'}, 'memory_mb': 524288.0, 'memory_mb_used': 43827.2, 'hypervisor_type': 'zvm', 'hypervisor_version': 710, 'hypervisor_hostname': 'BOEIAAS1', 'ipl_time': 'IPL at 09/16/21 13:08:12 CES', 'fcp': {'0': {'free': 8, 'used': 2}, '1': {'free': 9, 'used': 1}}, 'disk_total': 1156, 'disk_used': 981, 'disk_available': 174}}
>>> 
```

2021-09-22 07:13 UTC, dongyanyang requested changes

2021-09-22 07:13 UTC, dongyanyang commented on zvmsdk/volumeop.py
>      def get_all_fcp_usage(self, assigner_id=None):
keep the original return value of the get_all_fcp_usage, add new function like get_all_fcp_usage_by_path to do what we need.

2021-09-22 07:52 UTC, SharpRazor commented
## test results on new change:
### 1. host info
```
>>> from zvmconnector import connector
>>> conn = connector.ZVMConnector('127.0.0.1', port=8080, token_path='/etc/zvmsdk/token.dat')
>>> conn.send_request('guest_list')
{'overallRC': 0, 'modID': None, 'rc': 0, 'rs': 0, 'errmsg': '', 'output': ['BJCB001E']}
>>> conn.send_request('host_get_info')
{'overallRC': 0, 'modID': None, 'rc': 0, 'rs': 0, 'errmsg': '', 'output': {'zcc_userid': 'BJCBVM99', 'zvm_host': 'BOEIAAS1', 'vcpus': 12, 'vcpus_used': 12, 'cpu_info': {'architecture': 's390x', 'cec_model': '2964'}, 'memory_mb': 524288.0, 'memory_mb_used': 45260.8, 'hypervisor_type': 'zvm', 'hypervisor_version': 710, 'hypervisor_hostname': 'BOEIAAS1', 'ipl_time': 'IPL at 09/16/21 13:08:12 CES', 'fcp': {'total': 10, 'used': 1}, 'disk_total': 1156, 'disk_used': 981, 'disk_available': 174}}
>>>
```
### 2. reserve one FCP on path 0 and get info again
```
>>> from zvmconnector import connector
>>> conn = connector.ZVMConnector('127.0.0.1', port=8080, token_path='/etc/zvmsdk/token.dat')
>>> conn.send_request('host_get_info')
{'overallRC': 0, 'modID': None, 'rc': 0, 'rs': 0, 'errmsg': '', 'output': {'zcc_userid': 'BJCBVM99', 'zvm_host': 'BOEIAAS1', 'vcpus': 12, 'vcpus_used': 12, 'cpu_info': {'architecture': 's390x', 'cec_model': '2964'}, 'memory_mb': 524288.0, 'memory_mb_used': 45260.8, 'hypervisor_type': 'zvm', 'hypervisor_version': 710, 'hypervisor_hostname': 'BOEIAAS1', 'ipl_time': 'IPL at 09/16/21 13:08:12 CES', 'fcp': {'total': 10, 'used': 2}, 'disk_total': 1156, 'disk_used': 981, 'disk_available': 174}}
>>>
```

2021-09-22 09:04 UTC, dongyanyang approved these changes
lgtm

2021-09-22 09:09 UTC, jichenjc commented
the CI failed ....

2021-09-23 01:23 UTC, bjhuangr reviewed
please hold a while, answer my inline comment question

2021-09-23 01:23 UTC, bjhuangr commented on zvmsdk/hostops.py
> +        ret = _volumeop.get_all_fcp_usage_grouped_by_path()
Have you considered the case that no fcp_list configured? Any exception would be raised from this call?

2021-09-23 01:51 UTC, SharpRazor commented on zvmsdk/hostops.py
> +        ret = _volumeop.get_all_fcp_usage_grouped_by_path()
@bjhuangr the UT case cover this.
```
        mock_get.return_value = {}
        ret = self._hostops._get_fcp_info()
        expected = {'total': 0, 'used': 0}
        self.assertEqual(expected, ret)
```

2021-09-23 02:50 UTC, dongyanyang commented on zvmsdk/hostops.py
> +        ret = _volumeop.get_all_fcp_usage_grouped_by_path()
@SharpRazor  The UT cann't emulate what @bjhuangr is talking about. If I understand the code logic correctly, when no fcp_list configured, an SDKobjectnotexist exception will be raised from the db layer, instead of returning empty value.

2021-09-23 04:06 UTC, SharpRazor commented on zvmsdk/hostops.py
> +        ret = _volumeop.get_all_fcp_usage_grouped_by_path()
thanks, done.

2021-09-24 11:52 UTC, merged