use vmcp query to replace smcli to get lpar name
openmainframeproject/feilong pull request #536
Opened 2021-11-16 12:21 UTC by SharpRazor

Signed-off-by: cao biao <bjcb@cn.ibm.com>

2021-11-16 12:22 UTC, SharpRazor commented
@dongyanyang please help review.

2021-11-18 04:48 UTC, dongyanyang requested changes

2021-11-18 04:48 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            return empty_connector
For line 1080, split it into two loop:
1. first loop to get the wwpns and other required info
2. 2nd loop to reserve or unreserve FCP in DB.

So that the reserve and unreserve is the last step, making it less possible that one FCP is reserved/unreserved then got exception.

2021-11-18 06:20 UTC, SharpRazor commented on zvmsdk/volumeop.py
> +            return empty_connector
done.

2021-11-22 04:32 UTC, dongyanyang approved these changes
lgtm

2021-11-22 04:40 UTC, bjhuangr approved these changes

2021-11-22 04:40 UTC, merged