add new columns of wwpn in fcp table
openmainframeproject/feilong pull request #549
Opened 2021-12-13 07:46 UTC by SharpRazor

Signed-off-by: cao biao <bjcb@cn.ibm.com>

2021-12-13 09:56 UTC, dongyanyang requested changes

2021-12-13 09:56 UTC, dongyanyang commented on zvmsdk/database.py
> +FCP_NEW_ADDED_COLS = [dict(col_name='wwpn_npiv', col_type='char(16)'),
why here use char(16) and the _initialize_table use varchar(16)?

2021-12-13 09:56 UTC, dongyanyang commented on zvmsdk/database.py
> +                    conn.execute("ALTER TABLE fcp ADD COLUMN %s %s" %
why don't you first check whether the columns already exist?

2021-12-13 09:56 UTC, dongyanyang commented on zvmsdk/database.py
> +                    LOG.warning('When upgrading table FCP, encounter '
I think we should not ignore upgrade error.

2021-12-13 09:56 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            # update wwpns
Should only update the wwpns when it is not already in DB.
So, you need to update the get_fcp_dict_in_db to also return the WWPNs info from DB.

2021-12-13 09:56 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                    LOG.error(errmsg)
line 1278 should also be updated.

2021-12-14 09:07 UTC, SharpRazor commented
## test results
### 1. drop fcp table in fcp database
### 2. restart sdkserver
### 3. go into the FCP database:
```
sqlite> select * from fcp;
fcp_id|assigner_id|connections|reserved|path|comment|wwpn_npiv|wwpn_phy
5c0a||0|0|0|{'state': 'free'}|c05076ddf7003c00|c05076ddf7001181
5c07||0|0|0|{'state': 'free'}|c05076ddf7003bf4|c05076ddf7001181
5d0b||0|0|1|{'state': 'free'}|c05076ddf700411c|c05076ddf7001d81
5d0f||0|0|1|{'state': 'free'}|c05076ddf700412c|c05076ddf7001d81
5c09||0|0|0|{'state': 'free'}|c05076ddf7003bfc|c05076ddf7001181
5c0f||0|0|0|{'state': 'free'}|c05076ddf7003c14|c05076ddf7001181
5c06||0|0|0|{'state': 'free'}|c05076ddf7003bf0|c05076ddf7001181
5c0e||0|0|0|{'state': 'free'}|c05076ddf7003c10|c05076ddf7001181
5d0a||0|0|1|{'state': 'free'}|c05076ddf7004118|c05076ddf7001d81
5c0d||0|0|0|{'state': 'active'}|c05076ddf7003c0c|c05076ddf7001181
5d09||0|0|1|{'state': 'active'}|c05076ddf7004114|c05076ddf7001d81
5d0d||0|0|1|{'state': 'active'}|c05076ddf7004124|c05076ddf7001d81
5c08||0|0|0|{'state': 'active'}|c05076ddf7003bf8|c05076ddf7001181
5c0c||0|0|0|{'state': 'free'}|c05076ddf7003c08|c05076ddf7001181
5d07||0|0|1|{'state': 'free'}|c05076ddf700410c|c05076ddf7001d81
5d08||0|0|1|{'state': 'free'}|c05076ddf7004110|c05076ddf7001d81
5d0c||0|0|1|{'state': 'free'}|c05076ddf7004120|c05076ddf7001d81
5d06||0|0|1|{'state': 'free'}|c05076ddf7004108|c05076ddf7001d81
5d0e||0|0|1|{'state': 'free'}|c05076ddf7004128|c05076ddf7001d81
5c0b||0|0|0|{'state': 'free'}|c05076ddf7003c04|c05076ddf7001181
sqlite> 
```

2021-12-16 08:19 UTC, SharpRazor commented on zvmsdk/database.py
> +                                      "connections, reserved, path, comment, "
done.

2021-12-16 08:23 UTC, dongyanyang approved these changes

2021-12-16 08:27 UTC, bjhuangr approved these changes

2021-12-16 08:27 UTC, merged