[master][wip]Add API to query if a host is an SSI cluster member
openmainframeproject/feilong pull request #563
Opened 2021-12-28 03:31 UTC by zhshuj

Return True if host is an SSI cluster member,
else return False.

Signed-off-by: Shu Juan Zhang <zshujuan@cn.ibm.com>

2021-12-28 03:32 UTC, zhshuj commented
@jichenjc @bjhuangr @SeanHQF Please review the code first. UT is under working.

2021-12-28 03:43 UTC, jichenjc commented on zvmsdk/smtclient.py
> +                LOG.info("Host is not a member of an SSI cluster.")
I think debug is good enough

2021-12-28 03:43 UTC, jichenjc commented on zvmsdk/smtclient.py
> +        if results['rc'] == 0 and results['rs'] == 0:
I am not sure , but if we get some SSI info will benefit in the future ? 
instead of just return true/false
we return [] (for nonSSI) and [xxxxxx,xxxxxx] for SSI will be helpful?

2021-12-28 03:47 UTC, zhshuj commented on zvmsdk/smtclient.py
> +                LOG.info("Host is not a member of an SSI cluster.")
ok, will change

2021-12-28 03:49 UTC, zhshuj commented on zvmsdk/smtclient.py
> +        if results['rc'] == 0 and results['rs'] == 0:
what is the [xxxx,xxxx] stands for in an SSI cluster env?
currently: smcli SSI_Query returns: 
```
# smcli SSI_Query
ssi_name = ICIC2SSI
ssi_mode = Stable
ssi_pdr = IAS7CM_on_139E
cross_system_timeouts = Enabled
output.ssiInfoCount = 4

member_slot = 1
member_system_id = BOEIAAS7
member_state = Joined
member_pdr_heartbeat = 12/28/2021_04:48:21
member_received_heartbeat = 12/28/2021_04:48:21

member_slot = 2
member_system_id = BOEIAAS8
member_state = Joined
member_pdr_heartbeat = 12/28/2021_04:48:36
member_received_heartbeat = 12/28/2021_04:48:36

member_slot = 3
member_system_id = BOEIAAS9
member_state = Joined
member_pdr_heartbeat = 12/28/2021_04:48:32
member_received_heartbeat = 12/28/2021_04:48:32

member_slot = 4
member_system_id = N/A
member_state = Available
member_pdr_heartbeat = N/A
member_received_heartbeat = N/A
```

2021-12-28 03:55 UTC, jichenjc commented on zvmsdk/smtclient.py
> +        if results['rc'] == 0 and results['rs'] == 0:
I think 
```
ssi_name = ICIC2SSI
ssi_mode = Stable
ssi_pdr = IAS7CM_on_139E
cross_system_timeouts = Enabled
output.ssiInfoCount = 4

member_slot = 3
member_system_id = BOEIAAS9
member_state = Joined
```

those info should be helpful to us .. @SeanHQF thoughts?

2021-12-28 04:12 UTC, zhshuj commented on zvmsdk/smtclient.py
> +        if results['rc'] == 0 and results['rs'] == 0:
SMAPI has parsed the format as:
I think I can return the `results.response`. 
`{'overallRC': 0, 'rc': 0, 'rs': 0, 'errno': 0, 'strError': '', 'response': ['ssi_name = ICIC2SSI', 'ssi_mode = Stable', 'ssi_pdr = IAS7CM_on_139E', 'cross_system_timeouts = Enabled', 'output.ssiInfoCount = 4', '', 'member_slot = 1', 'member_system_id = BOEIAAS7', 'member_state = Joined', 'member_pdr_heartbeat = 12/28/2021_05:10:21', 'member_received_heartbeat = 12/28/2021_05:10:21', '', 'member_slot = 2', 'member_system_id = BOEIAAS8', 'member_state = Joined', 'member_pdr_heartbeat = 12/28/2021_05:10:36', 'member_received_heartbeat = 12/28/2021_05:10:36', '', 'member_slot = 3', 'member_system_id = BOEIAAS9', 'member_state = Joined', 'member_pdr_heartbeat = 12/28/2021_05:10:32', 'member_received_heartbeat = 12/28/2021_05:10:32', '', 'member_slot = 4', 'member_system_id = N/A', 'member_state = Available', 'member_pdr_heartbeat = N/A', 'member_received_heartbeat = N/A', ''], 'logEntries': []}`

2021-12-28 04:20 UTC, SeanHQF commented on zvmsdk/smtclient.py
> +        if results['rc'] == 0 and results['rs'] == 0:
Agree to return the SSI info instead of only true/false. So smapi returns a list of SSI info, right? If that, we may also just return it and return [] for a non-SSI host as Kevin's comment. @wngzhe pls also check, thanks.

2021-12-28 05:34 UTC, zhshuj commented on zvmsdk/smtclient.py
> +        if results['rc'] == 0 and results['rs'] == 0:
> Agree to return the SSI info instead of only true/false. So smapi returns a list of SSI info, right? If that, we may also just return it and return [] for a non-SSI host as Kevin's comment. @wngzhe pls also check, thanks.

yes, as my last comment.

2021-12-28 06:06 UTC, zhshuj commented
Have updated according to comments and added UT.

2021-12-28 06:17 UTC, SeanHQF approved these changes

2021-12-29 05:46 UTC, bjhuangr requested changes

2021-12-29 05:46 UTC, bjhuangr commented on zvmsdk/api.py
> +    def host_in_ssi_cluster(self):
suggest rename to host_get_ssi_info

2021-12-29 05:47 UTC, bjhuangr commented
And submit another PR to add doc for the new API

2021-12-29 06:27 UTC, zhshuj commented on zvmsdk/api.py
> +    def host_in_ssi_cluster(self):
> suggest rename to host_get_ssi_info

Updated the name to host_get_ssi_info

2021-12-29 06:28 UTC, zhshuj commented
> And submit another PR to add doc for the new API



> And submit another PR to add doc for the new API

will do.

2021-12-29 07:16 UTC, bjhuangr approved these changes

2021-12-29 07:16 UTC, merged