update for list fcp tempate API
openmainframeproject/feilong pull request #608
Opened 2022-05-19 15:38 UTC by haolp

below are the two main method for two APIs in file `zvmsdk/volumeop.py `:

```
    def get_fcp_templates(self, assigner_id=None, template_list=None, host_default=False,
                          sp_default=False, sp_host=None):
```
```
def get_fcp_templates_detail(self, template_list=None, raw=False, statistics=True, sync_with_zvm=False):
```

2022-05-23 02:58 UTC, haolp commented
test result of get_fcp_template_detail_by_id():
```
{
  "t1": {
    "id": "123456",
    "description": "test template",
    "host_default": 1,
    "sp_default": [
      "v7k60"
    ]
  },
  "statistics": {
    "0": {
      "total": "1A0F",
      "available": "",
      "allocated": "1A0F",
      "reserve_only": "",
      "connection_only": "",
      "unallocated_but_active": [],
      "allocated_but_free": "",
      "notfound": "",
      "offline": "",
      "CHIPIDs": {
        "27": "1A0F"
      }
    },
    "1": {
      "total": "1A0F, 1C0E",
      "available": "1C0E",
      "allocated": "1A0F",
      "reserve_only": "",
      "connection_only": "",
      "unallocated_but_active": [],
      "allocated_but_free": "",
      "notfound": "",
      "offline": "",
      "CHIPIDs": {
        "32": "1C0E"
      }
    }
  }
}
```

2022-05-23 09:48 UTC, dongyanyang requested changes

2022-05-23 09:48 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +    def get_fcp_template_by_id(self, template_id):
combine get_fcp_template_by_id and get_fcp_template_by_ids into one function, the parameter is a list.

2022-05-23 09:48 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        return self.get_fcp_template_by_id(template_id)
similar issue that we should avoid too many sql cmds.
eg, isn't this just one sql cmd: select * from templates where template_id=xxx and default=true;

2022-05-23 09:48 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        template_id_list = self.db.get_fcp_template_ids_by_assigner_id(assigner_id)
please think of how to combine sql cmds, eg:

select * from templates where template_id in (select * from fcps where connections!=0 or reserved!=0 and template_id !=None)?

2022-05-23 09:48 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            self.fcp_mgr._sync_db_with_zvm()
put sync_db_with_zvm inside get_template_detail function

2022-05-23 09:48 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        fcps_by_path = self.db.get_fcp_list_of_template(template_id)
Many of your functions can be simplified with outerjoin...

2022-05-23 10:22 UTC, jackydalong commented
It's better to refer to OpenStack API examples for determining the structure of fcp template APIs.
- Do NOT group by fcp-tmpl-name. The following is a OpenStack API example
  - <img width="600" alt="image" src="https://user-images.githubusercontent.com/20807562/169799095-2d258a76-cca6-4bb5-8acb-7e339fe4b2a5.png">

2022-05-25 02:58 UTC, dongyanyang commented on zvmsdk/database.py
> +                msg = ('Templates does not exist in DB.')
FCP templates

2022-05-25 02:58 UTC, dongyanyang commented on zvmsdk/database.py
> +                                template_id_list)), template_id_list)
Good job on the sql cmds. 
My thought is that as long as it is in the same "with get_fcp_conn() as conn:", it is free to use several sql cmds, so that the code wouldn't be too hard to read.

2022-05-25 02:58 UTC, dongyanyang commented on zvmsdk/database.py
> +                obj_desc = "Get template"
Get template -> FCP templates: %template_id_list

2022-05-25 02:58 UTC, dongyanyang commented on zvmsdk/database.py
> +                msg = ('Templates does not exist in DB.')
ditto

2022-05-25 02:58 UTC, dongyanyang commented on zvmsdk/database.py
> +            template_list.append(self.compose_fcp_template_info(template))
make the function compose_fcp_template_info to accept a list, instead of making the loop outside the function.

2022-05-25 02:58 UTC, dongyanyang commented on zvmsdk/database.py
> +    def get_all_fcp_templates_details(self):
The only difference between this and get_fcp_templates_details is the "WHERE template_fcp_mapping.tmpl_id IN" ?  
If so, I think we can combine this two into one function.

2022-05-25 02:58 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            return self.get_sp_default_fcp_templates(filters)
better to use filters[‘sp_default’] as the parameter instead of filters

2022-05-25 02:58 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            raw_data = self.db.get_fcp_templates_details(tuple(template_id_list))
combine this and line 1778 into one call

2022-05-25 02:58 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            self._update_template_info(template_info, item)
the function name is confusing, it is not update.
how about  extract_template_info_from_raw_data

2022-05-25 02:58 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                self._update_raw_fcp_usage(raw_usage, item)
extract_fcp_info_from_raw_data

2022-05-26 01:04 UTC, haolp commented
@dongyanyang PR is not ready to review yet, just complete refine database methods, still working on compose statistics data...

2022-05-26 02:26 UTC, jackydalong commented
- sp_default should be a list (i.e. a fcp template can be the default for multiple SPs)

- example output of get_fcp_templates(statistics=true)
<img width="305" alt="image" src="https://user-images.githubusercontent.com/20807562/170402880-1d003543-1d94-49de-bd08-12eef37e1a49.png">

2022-05-26 02:36 UTC, haolp commented
@jackydalong thanks, I will test this case.

2022-05-27 07:05 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                        "%s with state as notfound in database ." % str(tmpl_fcp_id))
found a FCP xxx in template xxx, but not found in z/VM.

2022-05-29 09:50 UTC, dongyanyang commented on zvmsdk/database.py
> +        return format:
this comment needs update

2022-05-29 09:50 UTC, dongyanyang commented on zvmsdk/database.py
> +                msg = ('FCP Templates does not exist in DB.')
print template id out.

2022-05-29 09:50 UTC, dongyanyang commented on zvmsdk/database.py
>          """
add comment about the return format and example

2022-05-29 09:50 UTC, dongyanyang commented on zvmsdk/database.py
>          """
eg, for each template, if it is more than one SP's default, then it will show up several times in the result.

2022-05-29 09:50 UTC, dongyanyang commented on zvmsdk/database.py
> +                                        "inner join template_sp_mapping "
why get_fcp_templates and get_host_default uses "left outer join" while this one uses "inner join", all of them are between template and template_sp_mapping table.

2022-05-29 09:50 UTC, dongyanyang commented on zvmsdk/database.py
> +        template table LEFT OUTER JOIN template_sp_mapping table
this comment is hard to understand, we should describe from function level, not cmd level.

2022-05-29 09:50 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                        if section != 'unallocated_but_active' and section != 'CHIPIDs':
update all the "CHIPIDs" to "CHPIDs"

2022-05-29 09:50 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            reserved, _, _, chpid, state, owner, _ = raw_item
for the last tmpl_id, suggest to also return this info in the raw_data, representing from which template this FCP has been allocated out.

2022-05-29 09:50 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        raw_usage[template_id][path_id].append(raw_item)
why you append the whole raw_item, isn't it in format (tmpl_id|fcp_id|path|fcp_id|assigner_id|connections|reserved|
        # wwpn_npiv|wwpn_phy|chpid|state|owner|tmpl_id)?

I don't think we should return all these fields.

2022-05-29 09:50 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +    def _update_raw_fcp_usage(self, raw_usage, raw_item):
_update_template_fcp_raw_usage

2022-05-29 09:50 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                self.extract_fcp_info_from_raw_data(statistics_usage, item)
it is not easy to link the current function name to what it really does.
how about _update_template_fcp_statistics_usage?

2022-05-29 09:50 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        if chpid:
put this under the case of line 1081: if fcp_id, (because the chpid only has value when it exists in the fcp table.)

2022-05-30 01:09 UTC, haolp commented on zvmsdk/volumeop.py
> +        if filters and "sp_default" in filters:
yes, will update this check in REST/wsgi layer.

2022-05-30 02:07 UTC, haolp commented on zvmsdk/database.py
> +                                        "inner join template_sp_mapping "
When get_fcp_templates and get_host_default, sp table is a subset and optional, we need all the templates info in template table even they are not in sp table, so use 'left outer join', left is template table.

When get sp default template, sp table is must have and I put sp table as left, we only need the template which is in both sp table and template table, so use 'inner join'.

2022-05-30 02:46 UTC, haolp commented on zvmsdk/volumeop.py
> +        raw_usage[template_id][path_id].append(raw_item)
yes, currently return all the fields. I am not sure what fields we should return actually.

2022-05-30 05:54 UTC, haolp commented on zvmsdk/database.py
> +        return format:
you mean update with example?

2022-05-30 06:22 UTC, dongyanyang commented on zvmsdk/database.py
> +        return format:
I mean, what you returned is raw_data, not consistent with the one you comment.

2022-05-30 14:55 UTC, haolp commented
@dongyanyang when I test the API of get_fcp_templates, found the parameter filters is very hard to send request. So I change to use separate parameters as I did previously. Let me know if you have any concern about this change, I have tested the code, it works with new parameters, but the comment not update yet.

```
    def get_fcp_templates(self, template_id_list=None, assigner_id=None,
                          default_of_host=False, default_of_sps=None):
```

2022-05-30 14:55 UTC, haolp commented
@dongyanyang when I test the API of get_fcp_templates, found the parameter filters is very hard to send request. So I change to use separate parameters as I did previously. Let me know if you have any concern about this change, I have tested the code, it works with new parameters, but the comment not update yet.

```
    def get_fcp_templates(self, template_id_list=None, assigner_id=None,
                          default_of_host=False, default_of_sps=None):
```

2022-05-30 14:58 UTC, haolp commented on zvmsdk/database.py
>              raw = result.fetchall()
Found issue during test with API request, change to compose the cmd directly when execute.

2022-05-30 14:58 UTC, haolp commented on zvmsdk/database.py
>              raw = result.fetchall()
Found issue during test with API request, change to compose the cmd directly when execute.

2022-05-30 14:59 UTC, haolp commented on zvmsdk/database.py
Change to compose the cmd when execute.

2022-05-30 14:59 UTC, haolp commented on zvmsdk/database.py
Change to compose the cmd when execute.

2022-05-30 15:02 UTC, haolp commented on zvmsdk/volumeop.py
> +            template_id_list = ast.literal_eval(template_id_list)
template_id_list will change to string via http request, so need to change back to list.

2022-05-31 06:42 UTC, jackydalong commented on zvmsdk/api.py
> +                          default_of_host=False, default_of_sps=None):
Suggest change `default_of_host` to `host_default`
Suggest change `default_of_sps` to `default_sp_list`

2022-05-31 06:43 UTC, jackydalong commented on zvmsdk/api.py
> +        :filters: {dict}, keys can be assigner_id, host_default and sp_default
delete filter-related comments, because we decide not to use filter

2022-05-31 06:44 UTC, jackydalong commented on zvmsdk/api.py
> +                        #  comment, wwpn_npiv, wwpn_phy, chpid, tmpl_id),
No `column comment` any more. replace with `column state` and `column owner`

2022-05-31 06:44 UTC, jackydalong commented on zvmsdk/api.py
> +                            {'state': 'active','owner: 'ABCD0001'},
ditto

2022-05-31 06:45 UTC, jackydalong commented on zvmsdk/api.py
> +                            {'state': 'active', 'owner': 'ABCD0001'},
ditto

2022-05-31 06:45 UTC, jackydalong commented on zvmsdk/api.py
> +                        "available": ('1A00','1A05',...)
The FCP is a shrinked string, such as `'1A00, 1A05'`

2022-05-31 06:46 UTC, jackydalong commented on zvmsdk/api.py
> +                        "available": ('1A00','1A05',...)
ditto

2022-05-31 06:47 UTC, jackydalong commented on zvmsdk/database.py
> +        cmd = "SELECT template.*, template_sp_mapping.sp_name " \
Replace `.*` with the exact column names

2022-05-31 06:47 UTC, jackydalong commented on zvmsdk/database.py
> +                    "SELECT template.*, template_sp_mapping.sp_name "
Replace `.*` with the exact column names

2022-05-31 06:48 UTC, jackydalong commented on zvmsdk/database.py
> +                                "LEFT OUTER JOIN template_sp_mapping "
only need to query table template : is enough. So do not join other table here

2022-05-31 06:49 UTC, jackydalong commented on zvmsdk/database.py
> +            result = conn.execute("SELECT template.*, "
Replace `.*` with the exact column names

2022-05-31 06:52 UTC, jackydalong commented on zvmsdk/database.py
> +        cmd = "SELECT template.*, template_sp_mapping.sp_name " \
Replace ·`*·` with the exact column names

2022-05-31 06:56 UTC, jackydalong commented on zvmsdk/database.py
> +    def get_sp_default_fcp_template(self, sp_host_list):
Add default value for sp_host_list : `sp_host_list=None`

2022-05-31 07:00 UTC, jackydalong commented on zvmsdk/database.py
> +            if sp_host_list != "All":
It does NOT make sense to pass a string to sp_host_list.
So, suggest replace with following:
```python
# query by the passed sp_host_list
if sp_host_list:
    for sp_host in sp_host_list:
    ....
# query by all the sp
else:
    ....
```

2022-05-31 07:03 UTC, jackydalong commented on zvmsdk/database.py
> +                                        "inner join template_sp_mapping "
`inner join` to uppercase

2022-05-31 07:48 UTC, haolp commented on zvmsdk/volumeop.py
> +        if filters and "sp_default" in filters:
will not implement in this PR.

2022-05-31 08:11 UTC, haolp commented on zvmsdk/api.py
> +                        "available": ('1A00','1A05',...)
Thank you. update whole comment with latest example.

2022-05-31 08:35 UTC, jackydalong commented on zvmsdk/database.py
> +        devices_cmd = "SELECT template_fcp_mapping.*, fcp.* " \
Only select `fcp.fcp_id` is enough rather than select both `fcp_id` in 2 tables

2022-05-31 09:50 UTC, jackydalong commented on zvmsdk/volumeop.py
> +        tmpl_fcp_id, template_id, path_id, fcp_id, assigner_id, connections,\
Please modify based on that 
Only one `fcp_id` is returned (that is `template_fcp_mapping.fcp_id`)

2022-05-31 09:51 UTC, jackydalong commented on zvmsdk/volumeop.py
> +        [(fcp_id|tmpl_id|path|fcp_id|assigner_id|connections|reserved|
Please modify based on that 
Only one `fcp_id` is returned (that is `template_fcp_mapping.fcp_id`)

2022-05-31 10:47 UTC, jackydalong commented on zvmsdk/volumeop.py
> +        if fcp_id:
As comment https://github.com/openmainframeproject/feilong/pull/608/files#discussion_r885359603,
Only one `fcp_id` is returned (that is `template_fcp_mapping.fcp_id`).
### To check whether a fcp_id belong to `NotFound Set-2`,
- use `if connections is None` to represent that a fcp_id not exist in `table fcp`
<img width="374" alt="image" src="https://user-images.githubusercontent.com/20807562/171156193-fffdc904-05aa-4bb7-a8fc-b6fbc712c469.png">

2022-05-31 13:52 UTC, haolp commented on zvmsdk/database.py
> +            if sp_host_list != "All":
updated according to discuss

2022-05-31 13:53 UTC, haolp commented on zvmsdk/database.py
> +    def get_sp_default_fcp_template(self, sp_host_list):
as we discussed, sp_host_list will always have value to represent filter by sp.

2022-06-01 00:47 UTC, jackydalong requested changes
Request changes

2022-06-01 00:47 UTC, jackydalong commented on zvmsdk/volumeop.py
>      def get_all_fcp_usage(self, assigner_id=None, raw=False, statistics=True,
Is `def get_all_fcp_usage` still needed ? 
If not needed, 
then the description-comments of caseA ~ caseI should be moved into `def get_fcp_templates_details`

2022-06-01 00:47 UTC, jackydalong commented on zvmsdk/volumeop.py
> +        [(fcp_id|tmpl_id|path|assigner_id|connections|reserved|
Only one `fcp_id` is exists in raw_item.

2022-06-01 00:47 UTC, jackydalong commented on zvmsdk/volumeop.py
> +                statistics_usage[template_id][path_id]["offline"].append(tmpl_fcp_id)
change `append(tmpl_fcp_id)` to `append(fcp_id)`

2022-06-01 00:47 UTC, jackydalong commented on zvmsdk/volumeop.py
> +            statistics_usage[template_id][path_id]["CHPIDs"][chpid].append(fcp_id)
It seems this line should be enclosed within `if chpid`.

2022-06-01 00:47 UTC, jackydalong commented on zvmsdk/volumeop.py
> +        if assigner_id:
Change to the following order (1->2->3->4)
<img width="583" alt="image" src="https://user-images.githubusercontent.com/20807562/171305675-df77d549-0562-42ff-9a78-3ad2d2bea31a.png">

2022-06-01 00:47 UTC, jackydalong commented on zvmsdk/volumeop.py
> +            template_id_list = ast.literal_eval(template_id_list)
> template_id_list will change to string via http request, so need to change back to list.

Add a example of the `string via http request`

2022-06-01 00:47 UTC, jackydalong commented on zvmsdk/volumeop.py
> +        if statistics:
Move line1398~1421 into a new function called 
`def _shrink_fcp_list_in_statistics_usage(statistics_usage)`

2022-06-01 00:47 UTC, jackydalong commented on zvmsdk/volumeop.py
> +            # update base info with statistics_usage
After this line, call `def _shrink_fcp_list_in_statistics_usage(statistics_usage)`

2022-06-01 01:37 UTC, haolp commented on zvmsdk/volumeop.py
>      def get_all_fcp_usage(self, assigner_id=None, raw=False, statistics=True,
moved. thanks.

2022-06-01 02:23 UTC, jackydalong commented on zvmsdk/database.py
> +        tmpl_cmd = "SELECT template.id, template.name, " \
Use alias name for table can make sql command shorter and easier to read.
e.g.
<img width="423" alt="image" src="https://user-images.githubusercontent.com/20807562/171315290-11aae27c-66ae-4d25-8506-a83d05885aea.png">

2022-06-01 02:29 UTC, jackydalong commented on zvmsdk/database.py
> +                tmpl_result = conn.execute(tmpl_cmd + \
`\` is unnecessary within in `(...)`, so remove `\`

2022-06-01 02:59 UTC, jackydalong commented on zvmsdk/database.py
> +            if len(sp_host_list)==1 and sp_host_list[0].lower() == 'all':
Add comments about examples of sp_host_list
ex1: what it looks like when represent 'all'
ex2: what it looks like when represent a list contains 2 items

2022-06-01 06:05 UTC, haolp commented on zvmsdk/database.py
> +            if len(sp_host_list)==1 and sp_host_list[0].lower() == 'all':
add example in volumeop.py of get_fcp_templates() method.

2022-06-01 09:54 UTC, jackydalong approved these changes
LGTM

2022-06-01 09:58 UTC, dongyanyang approved these changes

2022-06-01 10:02 UTC, haolp commented on zvmsdk/volumeop.py
> +            template_id_list = ast.literal_eval(template_id_list)
move convert param type into API layer

2022-06-01 10:18 UTC, merged