Update API get_volume_connection with fcp template
openmainframeproject/feilong pull request #613
Opened 2022-05-24 04:19 UTC by xingjing-bj

Signed-off-by: xingjing <xingjing@cn.ibm.com>

2022-05-25 01:24 UTC, dongyanyang commented
@xingjing-bj 
>if user doesn't specify fcp template while detach a volume, an error will be raised, which means user must specify the fcp template when to release a volume.

After another thought, how about change to:
In this case, if only one FCP template is assigned to this user, don't raise error and use the template directly. Otherwise report error.

Your thought?

2022-05-25 01:47 UTC, xingjing-bj commented
Seems more reasonable and convenient for user, will submit another commit for this change. @dongyanyang

2022-05-25 01:52 UTC, dongyanyang commented
And suggest to add more error cases, eg:
When reserve=True:
1. the template does not contain any FCP_list
2. the FCPs in the template are all used up, no free.
3. specified template id does not exist.
4. (normal case) the 2nd time attach to the same userid, the previously assigned FCP devices should be returned.
5.  the 2nd attach：
      a. default template id is 1, the 1st time attach to userid vm1 allocated (A,B) from template 1
      b. user change the default template from 1 to 2.
      c. the 2nd time attach to vm1, if no template id specified, then we will allocate new FCP (C, D) from template 2.

When reserve=False:
1. specified template id does not exist
2. specified assigner_id and vm_id does not have any FCP allocated

2022-05-25 02:22 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                           'phy_to_virt_initiators': {}, 'fcp_paths': 0, 'fcp_template_id': fcp_tmpl_id}
return template_id as None in case of empty_connector?

2022-05-25 02:22 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            raise exception.SDKVolumeOperationError(rs=11,
why use rs=11 as I saw reason code 11 is already used in line 1274.

2022-05-25 02:31 UTC, dongyanyang commented on zvmsdk/database.py
> +            result = conn.execute("SELECT DISTINCT path FROM template_fcp_mapping")
this function should have the template_id as parameter, to show how many paths the specified template contains.

select distinct path from template_fcp_mapping where template_id=xxx

2022-05-25 02:31 UTC, dongyanyang commented on zvmsdk/database.py
> +            result = conn.execute("SELECT DISTINCT path FROM template_fcp_mapping")
WHERE template_id=fcp_template_id

2022-05-25 02:31 UTC, dongyanyang commented on zvmsdk/database.py
> +                                      "ORDER BY template_fcp_mapping.fcp_id", (fcp_template_id, no[0]))
better to order by the path

2022-05-26 10:20 UTC, dongyanyang reviewed
Review not finished yet, will continue to review.

2022-05-26 10:20 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                           'phy_to_virt_initiators': {}, 'fcp_paths': 0, 'fcp_template_id': fcp_tmpl_id}
empty_connector should contains empty  fcp_template_id

2022-05-26 10:20 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        for fcp in fcp_list:
add comment to give a sample of the fcp_list content

2022-05-26 10:20 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            if not wwpn_npiv:
(fcp, wwpn_npiv, wwpn_phy) = xxx

2022-05-27 07:52 UTC, xingjing-bj commented on zvmsdk/volumeop.py
> +                           'phy_to_virt_initiators': {}, 'fcp_paths': 0, 'fcp_template_id': fcp_tmpl_id}
Confirmed with @dongyanyang , keep it as it is now.

2022-05-27 07:52 UTC, xingjing-bj commented
> And suggest to add more error cases, eg: When reserve=True:
> 
> 1. the template does not contain any FCP_list
> 2. the FCPs in the template are all used up, no free.
> 3. specified template id does not exist.
> 4. (normal case) the 2nd time attach to the same userid, the previously assigned FCP devices should be returned.
> 5. the 2nd attach：
>    a. default template id is 1, the 1st time attach to userid vm1 allocated (A,B) from template 1
>    b. user change the default template from 1 to 2.
>    c. the 2nd time attach to vm1, if no template id specified, then we will allocate new FCP (C, D) from template 2.
> 
> When reserve=False:
> 
> 1. specified template id does not exist
> 2. specified assigner_id and vm_id does not have any FCP allocated

Reserve:
1. Return empty connector:
```
{'overallRC': 0, 'modID': None, 'rc': 0, 'rs': 0, 'errmsg': '', 'output': {'zvm_fcp': [], 'wwpns': [], 'host': '', 'phy_to_virt_initiators': {}, 'fcp_paths': 0, 'fcp_template_id': '0003'}}
```
2. Return empty connector
3. It is a TODO item which depends on the method `get_fcp_template` in Liping's PR.
4. Yes
5. Yes

Unreserve:
1. It is a TODO item which depends on the method `get_fcp_template` in Liping's PR.
2. Return empty connector

2022-05-29 09:02 UTC, dongyanyang requested changes

2022-05-30 02:58 UTC, xingjing-bj commented on zvmsdk/volumeop.py
> +                if len(fcp_list) != path_count:
updated.

2022-05-30 03:01 UTC, xingjing-bj commented on zvmsdk/volumeop.py
> +                errmsg = "fcp_template_id is not specified while releasing FCP devices."
yes, I left a TODO here, plan to do it after @haolp 's PR is merged since the method of 'get_fcp_template' is needed here.

2022-05-30 08:00 UTC, jackydalong commented on zvmsdk/database.py
> +    def get_unreservable_fcps_from_assigner(self, assigner_id, fcp_template_id):
The SQL is filtered based on `reserved <> 0`, i.e. selecting reserved fcps rather than unreservable
Suggest change the func name back to `get_reserved_fcps_from_assigner`

2022-05-30 08:10 UTC, xingjing-bj commented on zvmsdk/volumeop.py
> +        fcp_tmpl_id = fcp_template_id if fcp_template_id else self.db.get_default_fcp_template()
will do it in next PR, left a TODO here.

2022-05-30 08:41 UTC, jackydalong commented on zvmsdk/database.py
> +                                  "AND fcp.tmpl_id=?"
miss ending-whitespace

2022-05-30 08:47 UTC, jackydalong commented on zvmsdk/database.py
> +            result = conn.execute("SELECT DISTINCT path FROM template_fcp_mapping"
miss ending-whitespace

2022-05-30 08:51 UTC, jackydalong commented on zvmsdk/database.py
> +    def get_fcp_pair_with_same_index(self, fcp_template_id):
As discussed, fcp `pair` is not correct. 
How about change to `def get_fcp_device_with_same_index` ? @dongyanyang @xingjing-bj

2022-05-30 08:51 UTC, jackydalong commented on zvmsdk/database.py
> +                                  "WHERE tmpl_id=?"
missing ending whitespace

2022-05-30 09:00 UTC, jackydalong commented on zvmsdk/database.py
> +                                  "fcp.reserved, fcp.state, fcp.wwpn_npiv, fcp.wwpn_phy, template_fcp_mapping.path "
`template_fcp_mapping.path` of get_fcp_pair_with_same_index  is unnecessary to get.
Only query from table fcp is enough

2022-05-30 09:08 UTC, jackydalong commented on zvmsdk/volumeop.py
> +        fcp_paths = set(fcp[3] for fcp in fcp_list)
As mentioned here : https://github.com/openmainframeproject/feilong/pull/613/files#r884592918.
`template_fcp_mapping.path` of get_fcp_pair_with_same_index  is unnecessary to get.
Only query from table fcp is enough
.
So we can replace this line with the following
`fcp_path = len(fcp_list)`

2022-05-30 09:10 UTC, xingjing-bj commented on zvmsdk/database.py
> +                                  "AND fcp.tmpl_id=?"
done

2022-05-30 09:10 UTC, xingjing-bj commented on zvmsdk/database.py
> +            result = conn.execute("SELECT DISTINCT path FROM template_fcp_mapping"
done

2022-05-30 09:11 UTC, xingjing-bj commented on zvmsdk/database.py
> +                                  "WHERE tmpl_id=?"
done

2022-05-30 09:13 UTC, xingjing-bj commented on zvmsdk/volumeop.py
> +        fcp_paths = set(fcp[3] for fcp in fcp_list)
done

2022-05-30 09:32 UTC, jackydalong commented on zvmsdk/database.py
> +                fcp_pair_map[i] = [(fcp_no, wwpn_npiv, wwpn_phy, fcp_path)]
Why do we change this line ?

2022-05-30 09:33 UTC, jackydalong commented on zvmsdk/sdkwsgi/handlers/volume.py
> +    fcp_template_id = body['info']['fcp_template_id'] if 'fcp_template_id' in body['info'] else None
change to 
`fcp_template_id = body['info'].get('fcp_template_id', None)`

2022-05-30 09:37 UTC, jackydalong commented on zvmsdk/volumeop.py
> +            if fcp_template_id is None or len(fcp_template_id) == 0:
replace the `if` with a separate util function (ex: def  whether_fcp_template_exist). As many places need the validation.

2022-05-30 09:39 UTC, jackydalong commented on zvmsdk/volumeop.py
> +            3. If fcp_list is empty, get one from each path, then update 'reserved' and 'tmpl_id' in fcp table.
The above 3 lines are the same with `def reserve_fcp_by_assigner_and_fcp_template`. 
Suggest make them different for the 2 functions

2022-05-30 10:31 UTC, jackydalong commented on zvmsdk/volumeop.py
> +                self.db.unreserve_fcps(fcp_ids, fcp_template_id)
Do we need to check whether connections == 0 before unreserve ?

2022-05-30 10:32 UTC, jackydalong commented on zvmsdk/volumeop.py
> +            fcp_list = self.db.get_reserved_fcps_from_assigner(assigner_id, fcp_template_id)
There is no function defined with name `def get_reserved_fcps_from_assigner`.

2022-05-30 10:33 UTC, jackydalong commented on zvmsdk/volumeop.py
> +            'fcp_template_id': fcp_template_id # if user doesn't specify it, it is the host default fcp template id
change `it is the host default fcp template id` to `it is either the SP default or the host default template id`

2022-05-31 03:09 UTC, jackydalong commented on zvmsdk/volumeop.py
> +            if not wwpn_npiv:
For reserve, we can put `wwpn<>NULL or wwpn<>''` in the SQL string.
For unreserve, it is unnecessary, because for the reserved fcp, we will not sync the wwpn with zvm.(i.e. for reserved fcp, its wwpn will not changed)

2022-05-31 04:55 UTC, xingjing-bj commented on zvmsdk/volumeop.py
> +            fcp_list = self.db.get_unreservable_fcps_from_assigner(assigner_id, fcp_template_id)
fixed.

2022-05-31 04:55 UTC, xingjing-bj commented on zvmsdk/database.py
> +    def get_unreservable_fcps_from_assigner(self, assigner_id, fcp_template_id):
done.

2022-05-31 04:55 UTC, xingjing-bj commented on zvmsdk/database.py
> +    def get_fcp_pair_with_same_index(self, fcp_template_id):
done.

2022-05-31 04:56 UTC, xingjing-bj commented on zvmsdk/database.py
> +                                  "fcp.reserved, fcp.state, fcp.wwpn_npiv, fcp.wwpn_phy, template_fcp_mapping.path "
done.

2022-05-31 04:57 UTC, xingjing-bj commented on zvmsdk/database.py
> +                fcp_pair_map[i] = [(fcp_no, wwpn_npiv, wwpn_phy, fcp_path)]
get all the needed information at one time, so that avoiding frequent db operations.

2022-05-31 04:57 UTC, xingjing-bj commented on zvmsdk/sdkwsgi/handlers/volume.py
> +    fcp_template_id = body['info']['fcp_template_id'] if 'fcp_template_id' in body['info'] else None
done.

2022-05-31 04:57 UTC, xingjing-bj commented on zvmsdk/volumeop.py
> +            3. If fcp_list is empty, get one from each path, then update 'reserved' and 'tmpl_id' in fcp table.
done.

2022-05-31 04:57 UTC, xingjing-bj commented on zvmsdk/volumeop.py
> +            fcp_list = self.db.get_reserved_fcps_from_assigner(assigner_id, fcp_template_id)
fixed.

2022-05-31 04:58 UTC, xingjing-bj commented on zvmsdk/volumeop.py
> +            'fcp_template_id': fcp_template_id # if user doesn't specify it, it is the host default fcp template id
done.

2022-05-31 04:58 UTC, xingjing-bj commented on zvmsdk/volumeop.py
> +                self.db.unreserve_fcps(fcp_ids, fcp_template_id)
fixed.

2022-05-31 04:58 UTC, xingjing-bj commented on zvmsdk/volumeop.py
> +            if fcp_template_id is None or len(fcp_template_id) == 0:
will do it in next pr.

2022-05-31 04:59 UTC, xingjing-bj commented on zvmsdk/volumeop.py
> +            if not wwpn_npiv:
done

2022-05-31 04:59 UTC, xingjing-bj commented
@jackydalong @dongyanyang the comments have been addressed, please help review again.

2022-06-01 07:22 UTC, jackydalong commented on zvmsdk/volumeop.py
> +    def _valid_fcp_devcies(self, fcp_list, assigner_id):
suggest to change func name to `_validate_fcp_device_wwpn`, as the func only validate wwpn

2022-06-01 09:20 UTC, jackydalong commented on zvmsdk/database.py
> +            result = conn.execute("SELECT * FROM fcp where fcp_id=? ", (fcp,))
Upper case for 1
Remove the whitespace for 2
<img width="506" alt="image" src="https://user-images.githubusercontent.com/20807562/171371537-b7aed7a8-b927-4c61-8dbe-d15a90b4b38c.png">

2022-06-01 09:30 UTC, xingjing-bj commented on zvmsdk/database.py
> +            result = conn.execute("SELECT * FROM fcp where fcp_id=? ", (fcp,))
done.

2022-06-01 09:41 UTC, xingjing-bj commented on zvmsdk/volumeop.py
> +            wwpn_phy = fcp[2]
Changed to: `fcp_id, wwpn_npiv, wwpn_phy, *_ = fcp`

2022-06-01 09:57 UTC, jackydalong approved these changes
LGTM

2022-06-01 10:18 UTC, merged