[master]add a cfg to control whether to extend partition
openmainframeproject/feilong pull request #652
Opened 2022-08-16 06:32 UTC by haolp

2022-08-17 08:22 UTC, jackydalong commented on doc/source/zvmsdk.conf.sample
> +# When set to True, when deploying an image to a larger disk, would
- `When set to True` to `If set to True`
- `disk, would automatically extend` to `disk, zvmsdk automatically extends`

2022-08-17 08:25 UTC, jackydalong commented on doc/source/zvmsdk.conf.sample
> +# If do not want to do the extend action automaictly, can set this option
`can set this option` to `you must set this option`
ID-reviewer best practice:  use `must` rather than `should or can or could` if it is required

2022-08-17 08:28 UTC, jackydalong commented on zvmsdk/config.py
> +When set to True, when deploying an image to a larger disk, would
need do the same as https://github.com/openmainframeproject/feilong/pull/652/files#r947598727

2022-08-17 08:28 UTC, jackydalong commented on zvmsdk/config.py
> +If do not want to do the extend action automaictly, can set this option
need do the same as https://github.com/openmainframeproject/feilong/pull/652/files#r947601095

2022-08-17 08:35 UTC, jackydalong commented on zvmsdk/config.py
> +        default='True',
Suggest refer to existing example for use bool value
```
# 1
Opt('my_ip',
        section='network',
        required=True,

# 2
Opt('user_profile',
        section='zvm',
        required=True,
        ```

2022-08-17 08:35 UTC, jackydalong requested changes
left comment

2022-08-17 08:53 UTC, jackydalong commented on zvmsdk/vmops.py
> +        if not CONF.guest.extend_partition_fs.lower() == 'true':
According to python PEP best practice `EBTI: explicit better than implicit`, suggest change to
```python
if CONF.guest.extend_partition_fs.lower() != 'true'
```

2022-08-18 02:42 UTC, haolp commented on doc/source/zvmsdk.conf.sample
> +# When set to True, when deploying an image to a larger disk, would
thank you, updated with all comments.

2022-08-18 03:16 UTC, jackydalong approved these changes
LGTM

2022-08-18 09:00 UTC, dongyanyang approved these changes

2022-08-18 09:07 UTC, merged