make error message more clear for punch attach detach script
openmainframeproject/feilong pull request #656
Opened 2022-08-19 08:50 UTC by IBMCaoBiao

Signed-off-by: CaoBiao <bjcb@cn.ibm.com>

2022-08-22 09:33 UTC, xingjing-bj commented on zvmsdk/volumeops/templates/rhel7_attach_volume.j2
> +    echo "Can not found intersection between input wwpns: ${input_wwpns[@]} and lszfcp output: $lszfcp_output, exit with code 3."
typo:  `found intersection` -> `find the intersection`

2022-08-22 09:37 UTC, xingjing-bj commented on zvmsdk/volumeops/templates/rhel7_detach_volume.j2
> +    echo "Can not found intersection between input wwpns: ${input_wwpns[@]} and lszfcp output: $lszfcp_output, exit with code 3."
Ditto. Typo: `found intersection` -> `find the intersection`

2022-08-22 09:39 UTC, xingjing-bj commented on zvmsdk/volumeops/templates/ubuntu_detach_volume.j2
> +    echo "Can not found intersection between input wwpns: ${input_wwpns[@]} and lszfcp output: $lszfcp_output, exit with code 3."
ditto.

2022-08-22 10:09 UTC, jackydalong commented on zvmsdk/volumeops/templates/rhel7_attach_volume.j2
> +    exit 1
- Suggest define the exit code as variable at the head of the script, 
  - so as to avoid typing the number while having to remember the meaning of each number.
- Example
```shell
# Attach script exit code explanation:
# 0: success
# 1: failed because multipathd service is not active
# 2: failed because input parameters may have problems
# 3: failed because can not found intersection between input WWPNs and lszfcp output
# 4: failed because no disk file found in the target VM, means no volume shown in the target VM

exit_success=0
exit_fail_multipathd=1
exit_....=2
exit_....=3
exit_....=4

2022-08-22 10:26 UTC, jackydalong requested changes
The PR makes error clear, very helpful.
Left one comment. 
@IBMCaoBiao

2022-08-23 03:02 UTC, IBMCaoBiao commented
# test results
## 1. sles
when attach failed because multipathd not active:
![Uploading Screen Shot 2022-08-23 at 11.02.11.png…]()

2022-08-23 07:41 UTC, jackydalong commented on zvmsdk/volumeop.py
> +                    errmsg = ('attach script execution failed because the '
- As zvmsdk, it makes sense to mention the concept of attach_script
- However, the msg is also returned to ICIC UI/API
  - from ICIC's perspective, I suggest not mention attach_script
    - because ICIC customer do not know/care what it is (and ICIC doc never mention it)
    
- Furthermore, 
   - zvmsdk recognize 
     - a VM by `userid` rather than `display_name`
     - a volume by `LUN_ID` rather than `display_name`
  - however, 
     - `display_name` is more direct and useful to ICIC admin
     - ICIC existing message use `display_name`
  - **Suggest**: 
     - nova catch the exit_code
       - return useful exception message with `display_name` of VM and volume 
       
@IBMCaoBiao @dongyanyang

2022-08-23 07:42 UTC, jackydalong requested changes
Left comment https://github.com/openmainframeproject/feilong/pull/656/files#r952259494

May need discussion

2022-08-23 09:42 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                              'not find the intersection between the input '
failed to find valid target WWPNs on the FCP devices xxx.

2022-08-23 09:43 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                    errmsg = ('attach script execution failed because the '
I agree with these concerns.

For the display_name, it is hard to be get from ZCC layer. I assume when the error is reported back to Nova layer, Nova would report these info out. @IBMCaoBiao can check the final msg reported in UI.

2022-08-25 09:48 UTC, dongyanyang requested changes

2022-08-25 09:48 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                              'unknown reason, exit code is: %s.'
remove the "unknown reason"
just "on FCP devices %s with exit code %s"

2022-08-25 09:48 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                              'not flush the multipath device maps, refer '
because getting error when flushing the multipath device maps

2022-08-25 09:48 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                              'unknown reason, exit code is: %s.'
remove "unknown reason"

2022-08-25 09:48 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                              'input parameters are invalid, refer to the '
"input parameters" is confusing as this is not user-inputed paramter, it is internal parameter pass.
So suggest to change:
"Failed to configure volume with exit code: %s, refer to the xxx"

2022-08-25 09:48 UTC, dongyanyang commented on zvmsdk/volumeops/templates/rhel7_attach_volume.j2
> +    exit 1
the original change about replacing hardcode with variables is lost, need to check

2022-08-25 10:41 UTC, IBMCaoBiao commented on zvmsdk/volumeop.py
> +                              'input parameters are invalid, refer to the '
```
errmsg = ('Failed to configure volume because the '
                              'configuration process terminate early with '
                              'exist code %s, refer to the log messages in '
                              'target virtual machine(userid:%s) for more '
                              'details.' % (exit_code, assigner_id))
```

2022-08-25 11:08 UTC, IBMCaoBiao commented
## the new error message after latest changes
<img width="481" alt="Screen Shot 2022-08-25 at 18 59 18" src="https://user-images.githubusercontent.com/25785609/186649129-100ab373-1cd6-4e15-a051-ad547e9d4c28.png">

2022-08-26 08:29 UTC, dongyanyang approved these changes

2022-08-26 08:30 UTC, merged