try to refine do_attach and do_detach
openmainframeproject/feilong pull request #686
Opened 2022-11-08 10:19 UTC by IBMCaoBiao

2022-11-09 02:20 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                           for fcp in fcp_list}
you need to first rollback connections  (connections - 1)

2022-11-09 02:20 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                           for fcp in fcp_list}
Can line 1830 to line 1843  be replaced by calling the rollback_do_attach? to avoid code duplication.

Technicolly, rollback_add_disk just do two more steps (connections-1,  remove_disk) than rollback_do_attach.

2022-11-09 02:20 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                LOG.info("Enter rollback: _rollback_do_attach")
I still prefer to keep these exception handling and add_disks into the _do_attach function.
Because we may use userid-level lock in that function wrapper, the add_disk should be put in the userid-level lock.

2022-11-14 07:09 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                self._rollback_dedicated_fcp_devices(fcp_list, assigner_id)
before Entering this step, connections already +1, I don't see where connections is rolled back in this scenario

2022-11-14 07:09 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            self._rollback_dedicated_fcp_devices(fcp_list, assigner_id)
ditto, connections also need to rollback

2022-11-14 07:32 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            self._rollback_removed_disks(fcp_connections, assigner_id, target_wwpns, target_lun,
in this and line 2282, the connections should also be rolled back.

2022-11-16 02:39 UTC, jackydalong commented on zvmsdk/volumeop.py
> +        with zvmutils.ignore_errors():
Suggest adopt the following change, so as to decrease_connections(`2nd fcp`) even if failing to decrease_connections(`1st fcp1`)
change 
```python
with zvmutils.ignore_errors():
            for fcp in fcp_list:
```
to
```python
for fcp in fcp_list:
   with zvmutils.ignore_errors():
```

2022-11-16 02:53 UTC, jackydalong commented on zvmsdk/volumeop.py
> -        with database._DBLOCK_FCP:
suggest to change line 1918
```
# _DBLOCK_FCP is the lock used in get_fcp_conn(),
# here it is used to ensure the operation of FCP DB is thread safe.
```
to
```
# _LOCK_ATTACH_VOLUME is used to ensure the operation of FCP DB is thread safe for simultaneous volume attachments of one VM
```

2022-11-16 06:22 UTC, jackydalong commented on zvmsdk/volumeop.py
> +    def allocate_fcp_devices(self, assigner_id, fcp_template_id, sp_name):
allocate_fcp_devices still call  self.db.reserve_fcps(), 
do you want to replace it with reserve_fcp_devices() ?

2022-11-16 06:28 UTC, jackydalong commented on zvmsdk/volumeop.py
> +    def reserve_fcp_devices(self, fcp_list, assigner_id, fcp_template_id):
Are `def reserve_fcp_devices` and `def unreserve_fcp_devices` necessary?
They only contains one line code that is already clear to me. 

@dongyanyang any idea ?

2022-11-16 06:32 UTC, jackydalong commented on zvmsdk/volumeop.py
> +    def release_fcp_devices(self, assigner_id, fcp_template_id):
if the comment  (https://github.com/openmainframeproject/feilong/pull/686/files#r1023551900) is accepted, then I suggest still use `def unreserve_fcp_devices` here. 
Because, the word  `unreserve` indicates the contained operation is related to FCP DB;

2022-11-16 07:23 UTC, jackydalong commented on zvmsdk/volumeop.py
> +                # the with statement will rollback them automatically.
change
`the with statement will rollback them automatically.`
to
`increase_fcp_connections will rollback them automatically.`

2022-11-16 07:43 UTC, jackydalong commented on zvmsdk/volumeop.py
> +                # 2. operations on FCP DB done by get_volume_connector()
change
```
# 1. operations on z/VM done by _dedicate_fcp()
# 2. operations on FCP DB done by get_volume_connector()
```
to
```
# 1. operations on z/VM done by _dedicate_fcp()
# 2. operations on FCP DB done by increase_fcp_connections() and get_volume_connector()
```

2022-11-16 07:46 UTC, jackydalong commented on zvmsdk/volumeop.py
> +            # 3. operations on FCP DB done by get_volume_connector()
same as https://github.com/openmainframeproject/feilong/pull/686/files#r1023603817

2022-11-16 07:50 UTC, jackydalong commented on zvmsdk/volumeop.py
> +        with zvmutils.ignore_errors():
same as https://github.com/openmainframeproject/feilong/pull/686#discussion_r1023447311

2022-11-16 08:19 UTC, jackydalong commented on zvmsdk/volumeop.py
> +            # The three operations must be put in the same with-block:
remove comments from line 1943-1948

2022-11-16 23:17 UTC, jackydalong requested changes
left comment

2022-11-18 02:52 UTC, jackydalong commented on zvmsdk/volumeop.py
> +            #   the connections of all the FCP devices are non-zero normally, for example:
`non-zero` to `zero`

2022-11-18 02:59 UTC, jackydalong requested changes
left comment

2022-11-18 02:59 UTC, jackydalong commented on zvmsdk/tests/unit/test_volumeop.py
> +    def test_allocate_fcp_devices_with_existed_reserved_fcp(self):
Search in zvmsdk/tests/unit/test_volumeop.py, there are multiple references and delete the following from this file.
```python
Those two files are deleted by this PR
_rollback_do_attach
_rollback_do_detach
```

2022-11-21 04:36 UTC, jackydalong approved these changes
lgtm

2022-11-21 05:28 UTC, dongyanyang approved these changes

2022-11-21 05:34 UTC, bjhuangr approved these changes

2022-11-21 05:34 UTC, merged