fix bug in extract_fcp_data
openmainframeproject/feilong pull request #699
Opened 2022-12-28 08:38 UTC by IBMCaoBiao

when calling extract_fcp_data, if smcli return abnormal formatted data printLn will put msg into return data, this will cause the upper layer can not extract correct info.
what's more, sometimes the smcli return a line only contains a #, skip this line in this scenario.

Signed-off-by: CaoBiao <bjcb@cn.ibm.com>

2022-12-28 09:02 UTC, jackydalong commented on smtLayer/getVM.py
> +        if i == '' or i == '#':
Suggest add comment to give example about when i == '' or i == '#'

2022-12-28 09:02 UTC, jackydalong requested changes
left a comment

2022-12-28 09:09 UTC, IBMCaoBiao commented on smtLayer/getVM.py
> +        if i == '' or i == '#':
done.

2022-12-28 09:36 UTC, jackydalong approved these changes
LGTM. Need to add UT

2022-12-28 10:35 UTC, dongyanyang approved these changes
lgtm. 
Can be merged after UT cases added.

2022-12-29 01:10 UTC, merged

2022-12-29 01:35 UTC, IBMCaoBiao commented
UT PR for this: https://github.com/openmainframeproject/feilong/pull/700