add alternate IPL path
openmainframeproject/feilong pull request #728
Opened 2023-07-27 06:44 UTC by haolp

PR for issue https://github.ibm.com/zvc/planning/issues/14315 and https://github.ibm.com/zvc/planning/issues/14314

2023-07-28 02:29 UTC, dongyanyang requested changes

2023-07-28 02:29 UTC, dongyanyang commented on smtLayer/makeVM.py
> +        ipl_string = "LOADDEV DEVICE %s " % rh.parms['ipl']
ipl_string should be "IPL LOADDEV"
The iplparam and iplLoadparam is for the IPL line.

2023-07-28 03:40 UTC, haolp commented on smtLayer/makeVM.py
> +        ipl_string = "LOADDEV DEVICE %s " % rh.parms['ipl']
updated, thanks.

2023-07-28 05:28 UTC, bjhuangr commented on smtLayer/makeVM.py
> +        dirLines.append("LOADDEV DEVICE %s " % rh.parms['ipl'])
Is it compatible with DASD root disk with `IPL LOADDEV` + `LOADDEV DEVICE`

And `IPL LOADDEV PARM XXX` `IPL LOADDEV LOADPARM XXX`?

2023-07-28 09:16 UTC, haolp commented on smtLayer/makeVM.py
> +        dirLines.append("LOADDEV DEVICE %s " % rh.parms['ipl'])
update to not make change for dasd, thanks for your comment.

2023-07-31 02:13 UTC, dongyanyang approved these changes

2023-07-31 07:19 UTC, bjhuangr approved these changes

2023-07-31 07:19 UTC, merged

2023-07-31 07:21 UTC, bjhuangr commented
@haolp you need another PR to change the API doc for this parameter update

2023-07-31 07:22 UTC, haolp commented
> @haolp you need another PR to change the API doc for this parameter update

got it, I will submit it later.

2023-08-02 08:37 UTC, haolp commented
> @haolp you need another PR to change the API doc for this parameter update

@bjhuangr I realized that this PR did not add new parameter when create guest, just put more data in existing parameter 'loaddev', so seems no need to update the doc?

```
.. restapi_parameters:: parameters.yaml

  - guest: guest_dict
  - userid: userid_create
  - vcpus: guest_vcpus
  - memory: guest_memory
  - user_profile: user_profile_guest
  - disk_list: disk_list_guest
  - size: size_disk
  - format: format_disk
  - is_boot_disk: is_boot_disk
  - vdev: add_mdisk_disk_vdev
  - disk_pool: disk_pool_guest
  - max_cpu: guest_max_cpu
  - max_mem: guest_max_mem
  - ipl_from: guest_ipl_from
  - ipl_param: guest_ipl_param
  - ipl_loadparam: guest_ipl_loadparam
  - dedicate_vdevs: guest_dedicate_vdevs
  - loaddev: guest_loaddev     <------
  - account: guest_account
  - comment_list: guest_comment_list
```