Update the API of get_fcp_template_details and get_fcp_templates to return the CPC/LPAR/PCHID info
openmainframeproject/feilong pull request #732
Opened 2023-08-02 06:29 UTC by renpei123

Update the API of get_fcp_template_details and get_fcp_templates to return the CPC/LPAR/PCHID info

2023-08-02 07:52 UTC, dongyanyang requested changes

2023-08-02 07:52 UTC, dongyanyang commented on zvmsdk/database.py
> +            "fcp.chpid, fcp.pchid, fcp.state, fcp.owner, fcp.tmpl_id "
comment in line 1570 also needs to be updated.

2023-08-02 07:52 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                        template_id][path_id]["PCHID-CHPID"].update({pchid: []})
why using a list as the value? pchid:[], shouldn't it be a string? 
chpid and pchid is a 1v1 relationship, no need to use []

2023-08-02 07:52 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                    template_id][path_id]["total_count"][pchid].append(fcp_id)
here you use the total_count actually to store the fcp_id list on this pchid.
Although in later stage, you changed this value to the count, it is still confusing when reading this part of code.

suggest to use other name to store this info, you can later pop it out if not useful any more.
@jackydalong can also give some advice.

2023-08-02 07:52 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                    template_id][path_id]["available_count"][pchid].append(fcp_id)
same as above

2023-08-02 08:10 UTC, dongyanyang requested changes

2023-08-02 10:31 UTC, renpei123 commented on zvmsdk/volumeop.py
> +                    template_id][path_id]["available_count"][pchid].append(fcp_id)
Done in https://github.com/openmainframeproject/feilong/pull/732#discussion_r1281718751

2023-08-02 10:32 UTC, renpei123 commented on zvmsdk/volumeop.py
> +                for pchid, chpid in template_statistics[
Removed.

2023-08-04 09:36 UTC, dongyanyang requested changes

2023-08-04 09:36 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            else:
no need to keep this else.
Also defect in line 1346 and line 1349

2023-08-04 09:36 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +            # Add PCHIDs info
cpc_sn, name, lpar, all these 3 items are same for all templates, no matter to get once for each template.

2023-08-04 09:36 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                    base_info.update({"lpar": zvmutils.get_lpar_name(zhypinfo=zhypinfo)})
same as above, no need to get these info once for each template

2023-08-04 09:36 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                    base_info.update({"lpar": ''})
although no FCP device, the cpc_sn,name,lpar still should be returned with correct value instead of empty string.

2023-08-04 09:38 UTC, dongyanyang commented on zvmsdk/tests/unit/test_volumeop.py
> +    def test_create_fcp_template(self, get_uuid, mock_get_zhypinfo):
this PR only change the get_xxx function, why would you change UT of create_fcp_template?

2023-08-07 09:19 UTC, renpei123 commented on zvmsdk/tests/unit/test_volumeop.py
> +    def test_create_fcp_template(self, get_uuid, mock_get_zhypinfo):
In `test_create_fcp_template`, there's a step to call `get_fcp_templates`. 
Made change in `test_create_fcp_template` is caused by return value for `get_fcp_templates` changed.

2023-08-07 09:21 UTC, renpei123 commented on zvmsdk/volumeop.py
> +                    base_info.update({"lpar": ''})
Done.

2023-08-07 09:21 UTC, renpei123 commented on zvmsdk/volumeop.py
> +                    base_info.update({"lpar": zvmutils.get_lpar_name(zhypinfo=zhypinfo)})
Done.

2023-08-07 09:21 UTC, renpei123 commented on zvmsdk/volumeop.py
> +            # Add PCHIDs info
Done.

2023-08-07 09:21 UTC, renpei123 commented on zvmsdk/volumeop.py
> +            else:
Done.

2023-08-07 09:56 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                if len(statistics_usage[template_id][path_id]["PCHIDs"]) == 0:
code from line 1377 to line 1385 is not needed.

The value is already initiated in line 1255, 1259, 1267-1268

2023-08-07 10:05 UTC, renpei123 commented on zvmsdk/volumeop.py
> +                if len(statistics_usage[template_id][path_id]["PCHIDs"]) == 0:
Done.

2023-08-07 10:07 UTC, dongyanyang approved these changes

2023-08-07 10:08 UTC, bjhuangr approved these changes

2023-08-07 10:08 UTC, merged