fix issue for bfv deploy on zvm not support multipath ipl
openmainframeproject/feilong pull request #735
Opened 2023-08-04 02:24 UTC by haolp

2023-08-04 02:33 UTC, jichenjc commented
@haolp can you help add UT for this ?

2023-08-04 02:43 UTC, haolp commented
> @haolp can you help add UT for this ?

sure, thanks for your reminder.

2023-08-04 07:53 UTC, dongyanyang requested changes

2023-08-04 07:53 UTC, dongyanyang commented on smtLayer/makeVM.py
> +        if ('alterdev' in rh.parms and 'loadportname' in rh.parms and
change the condition to check z/VM version.

2023-08-04 10:52 UTC, dongyanyang requested changes

2023-08-04 10:52 UTC, dongyanyang commented on zvmsdk/utils.py
> +def _getZVMVersion():
please follow the same naming conventions of existing functions.

def get_zvm_version()

2023-08-04 10:52 UTC, dongyanyang commented on zvmsdk/utils.py
> +def isSupportLoaddev():
is_ipl_loaddev_supported

2023-08-04 10:52 UTC, dongyanyang commented on zvmsdk/utils.py
> +    smallV = float(result[4].strip(','))
these match rules are too risky, I think.
I have other options:
1. smcli - then you can just get the last string of the output.
```
[root@quality-ssi001 ~]# smcli Query_API_Functional_Level -T SSI10289
The API functional level is z/VM V7.2
```
2. from zthin file:
```
[root@quality-ssi001 ~]# cat /var/opt/zthin/smapi.level
720
```

Or @jichenjc @bjhuangr Do you have suggestions on how to safely get and compare the z/VM version?

2023-08-04 12:03 UTC, haolp commented on zvmsdk/utils.py
> +def isSupportLoaddev():
updated, thanks.

2023-08-04 12:03 UTC, haolp commented on smtLayer/makeVM.py
> +        if ('alterdev' in rh.parms and 'loadportname' in rh.parms and
updated, thanks.

2023-08-07 01:21 UTC, bjhuangr commented on zvmsdk/utils.py
> +    smallV = float(result[4].strip(','))
it's fine to use `/var/opt/zthin/smapi.level`

2023-08-07 04:03 UTC, haolp commented on zvmsdk/utils.py
> +    smallV = float(result[4].strip(','))
thanks,  design changed and do not need to check zvm version now.

2023-08-07 05:57 UTC, dongyanyang approved these changes

2023-08-07 07:18 UTC, bjhuangr approved these changes

2023-08-07 09:44 UTC, merged