[master] change return of edit_fcp_template add orphan values in return value dict
openmainframeproject/feilong pull request #738
Opened 2023-08-08 13:53 UTC by wngzhe

code change:
    change return of edit_fcp_template add orphan values in return value dict

2023-08-09 02:15 UTC, dongyanyang requested changes

2023-08-09 02:15 UTC, dongyanyang commented on zvmsdk/database.py
> +    def get_all_pchids_used_by_template(self):
1. current loop will call several times of db query.
Please check the implementation of get_pchids_by_fcp_template, what you need is to just remove the condition of "where xxx" in the SQL cmd.

2. move the function to database.py, refer to get_pchids_by_fcp_template.

2023-08-09 02:15 UTC, dongyanyang commented on zvmsdk/database.py
> +            orphan_items = list(set(all_items_in_db) - set(all_items_in_template))
this calculation is wrong.
1. remove the function get_all_pchids_in_db(), it only represents all the pchids on this z/VM LPAR.
2. not_used_in_any_template = set(del_items) - set(all_pchids_used_by_templates)
3. do not call it orphan_items, rename it to not_used_in_any_template

2023-08-09 03:14 UTC, jackydalong commented on zvmsdk/database.py
> +                        'all': [D, E],
change to 'all': ['D', 'E'],

2023-08-09 03:14 UTC, jackydalong commented on zvmsdk/database.py
> +                        'not_exist_in_any_template': [D]
change from [D] to ['D']

2023-08-09 03:15 UTC, jackydalong commented on zvmsdk/database.py
> +                    }
Missing the following info
```python
        'cpc_sn': '23432',      <-------
        'cpc_name': 'M54',      <-------
        'lpar': 'ZVM4OCP1',      <------- Not z/VM name BOEM5401
        "hypervisor_hostname": "BOEM5401" <-------
```

2023-08-09 04:00 UTC, jackydalong commented on zvmsdk/database.py
> +                         },
delete 4 whitespace before }

2023-08-09 04:01 UTC, jackydalong commented on zvmsdk/database.py
> +                    }
delete 4 whitespace before }

2023-08-09 04:03 UTC, jackydalong commented on zvmsdk/database.py
>              final_phid_list = self.get_pchids_by_fcp_template(fcp_template_id)
There are many variable with typo `xx_phid_xx` introduced by your last PR, please rename all of them as `xx_pchid_xx`

2023-08-09 04:15 UTC, jackydalong commented
suggest changing the title 
from 
```
change return of edit_fcp_template add orphan values in return value dict
```
to
```
add pchids-not-exist-in-any-template in the response of edit_fcp_template API
```

2023-08-09 04:22 UTC, jackydalong commented on zvmsdk/database.py
> -            all_items = final_phid_list
suggest change
from 
```
add_items, del_items, all_items
```
to
```
add_pchids, del_pchids, all_pchids
```

2023-08-09 04:26 UTC, jackydalong commented on zvmsdk/database.py
> +            delete_dict = dict(all=del_items, not_exist_in_any_template=orphan_items)
change from
```python
            all_items_in_db = self.get_all_pchids_in_db()
            all_items_in_template = self.get_all_pchids_used_by_template()
            orphan_items = list(set(all_items_in_db) - set(all_items_in_template))
            delete_dict = dict(all=del_items, not_exist_in_any_template=orphan_items)
```
to
```python
pchids_from_all_templates = self.get_pchids_from_all_fcp_templates()
pchids_not_used_in_any_template = list(set(del_pchids) - set(pchids_from_all_templates))
delete_dict = dict(all=del_pchids, not_exist_in_any_template=pchids_not_used_in_any_template)
```

2023-08-09 04:33 UTC, jackydalong commented on zvmsdk/database.py
>                      'add': add_items,
change to **'add': add_pchids**

2023-08-09 04:34 UTC, jackydalong commented on zvmsdk/database.py
> -                    'all': all_items
change to **'all': all_pchids**

2023-08-09 04:35 UTC, jackydalong commented on zvmsdk/database.py
> +    def get_all_pchids_used_by_template(self):
change the function name as 
```python
def get_pchids_from_all_fcp_templates(self)
```

2023-08-09 04:36 UTC, jackydalong commented on zvmsdk/database.py
> +    def get_all_pchids_in_db(self):
remove this function, no needed so far

2023-08-09 04:37 UTC, jackydalong commented on zvmsdk/volumeop.py
> +                    }
delete 4 whitespace before }

2023-08-09 04:38 UTC, jackydalong commented on zvmsdk/volumeop.py
> +                         },
change to
```python
               'pchids': {
                    'add' : ['C'],
                    'delete' : {
                        'all': ['D', 'E'],                <----- 'D', 'E'
                        'not_exist_in_any_template': ['D']    <---- 'D'
                     },            <--- delete 4 whitespace before }


```

2023-08-09 04:40 UTC, jackydalong commented on zvmsdk/database.py
> +    def get_all_pchids_used_by_template(self):
Please strictly follow the good practice of other functions to add **function-level comment** to 
- describe each param (if any)
- describe return value, including an example

2023-08-09 04:50 UTC, jackydalong commented on zvmsdk/database.py
> +    def get_all_pchids_used_by_template(self):
As mentioned [here](https://github.com/openmainframeproject/feilong/pull/738/files#r1287854209) , from the performance view, suggest change to
```python
        pchids = []
        with get_fcp_conn() as conn:
            result = conn.execute(
                "SELECT DISTINCT fcp.pchid "
                "FROM template_fcp_mapping AS tf "
                "INNER JOIN fcp "
                "ON tf.fcp_id=fcp.fcp_id ")

            raw = result.fetchall()
            for item in raw:
                pchids.append(item['pchid'])
        return pchids
```

2023-08-09 07:04 UTC, wngzhe commented on zvmsdk/database.py
>                      'add': add_items,
this comes from issue comment ,need we change this key?

2023-08-10 01:49 UTC, jackydalong approved these changes
lgtm

2023-08-10 02:12 UTC, dongyanyang approved these changes

2023-08-10 02:14 UTC, bjhuangr approved these changes

2023-08-10 02:14 UTC, merged