get_volume_connector_based_on_pchid_info
openmainframeproject/feilong pull request #748
Opened 2023-08-28 03:00 UTC by jackydalong

- API interface change:
  - PCHID usage info will be passed in
  - return more info:
    - the PCHID of each allocated FCP,
    - whether new FCP devices are allocated or reused, whether FCP devices are released.

- When allocating new FCP devices to VM, take the PCHID free capacity into consideration
  - PCHID load balance. (select the most free PCHIDs as possible)
  - real multipath from PCHID layer. (select different PCHIDs for different paths as possbile)

2023-08-28 06:19 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +                is_reserved_changed, fcp_list = self.fcp_mgr.release_fcp_devices(
shouldn't the fcp_list value be in the similar format with line 2565 as a dictionary? otherwise won't the code in line 2611, 2612 report key error?

2023-08-28 07:54 UTC, jackydalong commented on zvmsdk/api.py
>          :param str sp_name: the storage provider name
done

2023-08-28 07:56 UTC, jackydalong commented on zvmsdk/volumeop.py
> +                is_reserved_changed, fcp_list = self.fcp_mgr.release_fcp_devices(
I modified the comments to address the concern

2023-08-28 08:02 UTC, jackydalong commented on zvmsdk/volumeop.py
> +        hypervisor_hostname = utils.get_zvm_name()
Not duplicated.  @dongyanyang 

As shown in the following example, 
- If remove B, 
  - then zvm_host in C is undefined, 
    - because zvm_host in A becomes a local variable
```python
    def get_volume_connector(
    
        def _precheck():
            zvm_host = zvmutils.get_zvm_name()     <---- A
            
        with database.get_fcp_conn():
            zvm_host = None                     <------ B
            # precheck
            _precheck()  

        ret_host = zvm_host + '_' + assigner_id   <----- C
```

2023-08-29 01:04 UTC, dongyanyang commented on zvmsdk/volumeop.py
> +        hypervisor_hostname = utils.get_zvm_name()
I mean, the hypervisor_hostname is duplicated with zvm_host

2023-08-29 02:37 UTC, LiJunBJZhu requested changes

2023-08-29 02:37 UTC, LiJunBJZhu commented on zvmsdk/database.py
> +                comb_fcp_count_per_pchid = {
I think it stands for the count of to-be-consumed fcps per pchid with this combination. Can it be renamed to a more meaningful name? Or add a few comment here to explain its meaning.

2023-08-29 02:37 UTC, LiJunBJZhu commented on zvmsdk/volumeop.py
> +        """Get connector information of the instance for attaching volumes.
"Get connector information of the instance for attaching volumes." =>> "Get connector information of the instance for attaching or detaching volumes."

2023-08-29 02:37 UTC, LiJunBJZhu commented on zvmsdk/volumeop.py
> +                'is_reserved_changed': True  # True for either attaching 1st volume to
if is_reserved_changed is True and reserve is True, means the fcps in pchid_fcp_map need to be added to the 'fcp_devices' of the corresponding pchid and the count need to be increased in nova db, correct?

2023-08-29 03:06 UTC, jackydalong commented on zvmsdk/volumeop.py
> +        hypervisor_hostname = utils.get_zvm_name()
Done by replacing zvm_host with hypervisor_hostname

2023-08-29 03:31 UTC, jackydalong commented on zvmsdk/database.py
>              fcp_list = result.fetchall()
done

2023-08-29 05:44 UTC, jackydalong commented on zvmsdk/database.py
>          with get_fcp_conn() as conn:
done

2023-08-29 05:55 UTC, jackydalong commented on zvmsdk/database.py
> +               fcp  conn reserved state
done.

2023-08-29 05:59 UTC, jackydalong commented on zvmsdk/database.py
> +                        (fcp_no, wwpn_npiv, wwpn_phy, path, pchid))
done

2023-08-29 06:00 UTC, jackydalong commented on zvmsdk/database.py
> +            # [{'fcp_id':'1A03', 'path':0, 'pchid':'AAAA', 'wwpn_npiv':'aa', 'wwpn_phy':'xx'},
done

2023-08-29 06:18 UTC, jackydalong commented on zvmsdk/database.py
> +                comb_fcp_count_per_pchid = {
done

2023-08-29 06:20 UTC, jackydalong commented on zvmsdk/volumeop.py
> +        """Get connector information of the instance for attaching volumes.
done

2023-08-29 06:23 UTC, jackydalong commented on zvmsdk/volumeop.py
> +                'is_reserved_changed': True  # True for either attaching 1st volume to
yes. @LiJunBJZhu

2023-08-29 06:29 UTC, jackydalong commented on zvmsdk/api.py
> +            { 'AAAA': { 'total_allocate': 126, 'instance_allocate': 120, 'max': 128},
suggest nova pass pchid_info (rather than only free_capacity, which has too little info. We want to log pchid_info in our ZCC log )

2023-08-29 06:30 UTC, jackydalong commented on zvmsdk/database.py
> +          { 'AAAA': { 'total_allocate': 128, 'instance_allocate': 106, 'max': 128},
suggest to keep pchid_info without dup info. As free_capacity can be easily calculated from pchid_info, so no need to save free_capacity in pchid_info

2023-09-05 09:45 UTC, dongyanyang approved these changes

2023-09-05 09:51 UTC, bjhuangr approved these changes

2023-09-05 09:51 UTC, merged