only write fcp into rd.zfcp for rhel8 and rhel9
openmainframeproject/feilong pull request #773
Opened 2023-11-23 02:15 UTC by haolp

2023-12-05 09:19 UTC, dongyanyang requested changes

2023-12-05 09:19 UTC, dongyanyang commented on zthin-parts/zthin/bin/refresh_bootmap
> +    updaterdzfcp_with_fcp_only
updaterdzfcp_with_fcp_only -> update_rdzfcp_to_fcp_only

2023-12-05 09:19 UTC, dongyanyang commented on zthin-parts/zthin/bin/refresh_bootmap
> +      rd_zfcp+="rd.zfcp=0.0.$fcp "
If there are multiple paths bond to the same FCP, the FCP will be writen several times in rd_zfcp.

2023-12-05 10:43 UTC, dongyanyang approved these changes

2023-12-05 10:43 UTC, merged

2023-12-14 08:47 UTC, haolp commented
currently 122 is built with zvc/python-zvm-sdk repo, so my PR is not included in latest build. Later build will change to use feilong project, so shall I submit PR to this temp repo or wait for final build with feilong repo?