Update the API of get_fcp_template_details to return physical wwpns
openmainframeproject/feilong pull request #800
Opened 2024-01-08 08:53 UTC by renpei123

Update the API of get_fcp_template_details to return physical wwpns

2024-01-10 06:43 UTC, jackydalong commented on zvmsdk/database.py
> +    def get_wwpn_phy_from_pchid(self, pchid):
change wwpn_phy to phy_wwpn in all places, including 
- function name
- variable name
- comment

2024-01-10 06:55 UTC, jackydalong commented on zvmsdk/database.py
> +        return wwpn_phy[0]
The SQL only return one row, so replace fetchall() to fetchone(). You can search existing example of fetchone()
change to something below
```python
        wwpn_phy = ''
...
            raw = result.fetchone()
            wwpn_phy = raw['wwpn_phy'])
        return wwpn_phy
```
Please test after change

2024-01-10 06:57 UTC, jackydalong commented on zvmsdk/volumeop.py
> +                    wwpn_phy_dict = {}
Add a comment here to introduce your code, like line 1911

2024-01-10 07:01 UTC, jackydalong reviewed
see my comments

2024-01-10 08:31 UTC, LiJunBJZhu requested changes

2024-01-10 08:31 UTC, LiJunBJZhu commented on zvmsdk/database.py
> +    def get_wwpn_phy_from_pchid(self, pchid):
Change it support get wwpn_phys of multiple pchids

2024-01-10 08:31 UTC, LiJunBJZhu commented on zvmsdk/volumeop.py
> +                    for pchid in pchids:
Update the util method to support get wwpns of pchids, rather than make one sql query for each pchid.

2024-01-11 08:13 UTC, renpei123 commented on zvmsdk/volumeop.py
> +                    wwpn_phy_dict = {}
Done.

2024-01-11 08:14 UTC, renpei123 commented on zvmsdk/database.py
> +    def get_wwpn_phy_from_pchid(self, pchid):
Done.

2024-01-11 08:15 UTC, renpei123 commented on zvmsdk/volumeop.py
> +                    for pchid in pchids:
Done.

2024-01-11 08:18 UTC, renpei123 commented on zvmsdk/database.py
> +        return wwpn_phy[0]
@jackydalong Thanks a lot for your comment. Util method updated to support get wwpns of pchids, so still use fetchall().

2024-01-11 08:45 UTC, jackydalong commented on zvmsdk/database.py
> +    def get_wwpn_phys_from_pchids(self, pchids):
change to  **wwpn_phys** to **wwpn_phy** in the name, because it is wwpn_phy in sqlite DB table fcp

2024-01-11 08:47 UTC, LiJunBJZhu requested changes

2024-01-11 08:47 UTC, LiJunBJZhu commented on zvmsdk/volumeop.py
> +                    pchid_to_phy_wwpn_dict = {}
The logic should be moved outside 'if statistics' block. pchid_to_phy_wwpn_dict should be set no matter statistics is True or False.

2024-01-11 08:47 UTC, LiJunBJZhu commented on zvmsdk/volumeop.py
>                      base_info.update({"pchids": pchids})
Set 'pchids' should be moved outside 'if statistics' block.

2024-01-11 08:55 UTC, jackydalong commented on zvmsdk/volumeop.py
> +                    pchid_to_phy_wwpn_dict = {}
Agree

2024-01-11 09:54 UTC, renpei123 commented on zvmsdk/database.py
> +    def get_wwpn_phys_from_pchids(self, pchids):
Done.

2024-01-11 09:56 UTC, renpei123 commented on zvmsdk/volumeop.py
> +                    pchid_to_phy_wwpn_dict = {}
Done.

2024-01-11 09:56 UTC, renpei123 commented on zvmsdk/volumeop.py
>                      base_info.update({"pchids": pchids})
Done.

2024-01-11 10:05 UTC, LiJunBJZhu commented on zvmsdk/volumeop.py
> +            pchid_to_phy_wwpn_dict = self.db.get_wwpn_phy_from_pchids(pchids)
item["pchid_to_phy_wwpn"] = self.db.get_wwpn_phy_from_pchids(pchids)

2024-01-11 10:05 UTC, LiJunBJZhu approved these changes

2024-01-11 10:15 UTC, renpei123 commented on zvmsdk/volumeop.py
> +            pchid_to_phy_wwpn_dict = self.db.get_wwpn_phy_from_pchids(pchids)
Done.

2024-01-11 10:23 UTC, dongyanyang approved these changes

2024-01-11 10:28 UTC, merged