Add uwsgi service file
openmainframeproject/feilong pull request #821
Opened 2024-06-05 07:59 UTC by aazam-gh

A uwsgi.service file added under data/ for starting feilong in uwsgi

2024-06-05 08:42 UTC, Bischoff requested changes
See comments

2024-06-05 08:42 UTC, Bischoff commented on setup.py
> +                (['data/uwsgi.service'])],
No, it should be similar to line 68, as it goes to `/lib/systemd/system`.

Move it up there, and add the destination path.

2024-06-05 08:42 UTC, Bischoff commented on data/uwsgi.service
> +[Unit]
This file will conflict with the service file for `uwsgi` when you install it.

I was thinking at a file named `zvmsdk-wsgi.service`, like the one in documentation section 4.2.2:

https://cloudlib4zvm.readthedocs.io/en/latest/setuphttpd.html#start-feilong-in-uwsgi

2024-06-05 08:42 UTC, Bischoff commented on data/uwsgi.service
> +ExecStart=/usr/sbin/uwsgi --ini /data/uwsgi-zvm.conf
The configuration file is in `/etc/zvmsdk/uwsgi-zvmsdk.conf`.

2024-06-05 09:00 UTC, aazam-gh commented
Addressed the changes

2024-06-05 09:21 UTC, Bischoff reviewed
thanks for the changes

added a last nitpick

will test it live now

2024-06-05 09:21 UTC, Bischoff commented on data/zvmsdk-wsgi.service
> +WantedBy=multi-user.target
nitpick: add missing end of line

2024-06-05 09:53 UTC, Bischoff approved these changes
tested to work fine

2024-06-06 02:54 UTC, bjhuangr approved these changes

2024-06-06 06:17 UTC, bjhuangr commented
@aazam-gh please sign your PR, thanks

2024-06-07 06:53 UTC, merged