Fix Quickstart Docs b
openmainframeproject/feilong pull request #822
Opened 2024-06-06 15:07 UTC by aazam-gh

2024-06-06 15:16 UTC, Bischoff requested changes
same contents as the other pr :)

2024-06-06 16:45 UTC, Bischoff commented on doc/source/setuphttpd.rst
> +nginx does not support wsgi.
rather "mod_wsgi"

2024-06-06 16:49 UTC, Bischoff commented on doc/source/setuphttpd.rst
>  on RHEL7.2 as a sample about the deployment process, you can setup your own web server similarly.
"This guide would take Apache and uwsgi similarly on RHEL7.2 as a sample about the deployment process, you can setup your own web server similarly."
=>
"This guide walks you through the deployment process, either with uwsgi. or Apache's mod_wsgi."

2024-06-06 16:57 UTC, Bischoff requested changes
Thanks a lot.

Please prefix the title with "WIP: " in order to make clear it's a work in progress

2024-06-06 16:57 UTC, Bischoff commented on doc/source/setuphttpd.rst
>  on RHEL7.2 as a sample about the deployment process, you can setup your own web server similarly.
"This guide would take Apache and uwsgi similarly on RHEL7.2 as a sample about the deployment process, you can setup your own web server similarly."
=>
"This guide walks you through the deployment process, either with uwsgi. or with Apache's mod_wsgi."

2024-06-06 16:57 UTC, Bischoff commented on doc/source/setuphttpd.rst
>  you can refer to the specific guide of your chosen web server. This guide would take Apache and uwsgi
"running under a wsgi container such as uwsgi."
=>
"running under a wsgi container such as uwsgi, or directly connected via Apache's wsgi module.

2024-06-06 16:57 UTC, Bischoff commented on doc/source/setuphttpd.rst
>  * Install uwsgi of version >= 2.0.13. (eg, you can choose to use pip to install uwsgi and specify the version)
Remove version details, that is probably outdated, and can go below when we discuss the packages to install.

Also remove mention of pip 1) it's not preferred method, and 2) it can be discussed below too.

2024-06-06 16:57 UTC, Bischoff commented on doc/source/setuphttpd.rst
>  The uwsgi package contained in the **Ubuntu 16.04 LTS** repository cann't work on IBM Z because of
outdated, remove.

2024-06-06 16:57 UTC, Bischoff commented on doc/source/setuphttpd.rst
> +Securing connections with Tokens (Token Usage)
Remove " (Token Usage)"

2024-06-07 10:30 UTC, Bischoff approved these changes
lgtm

@mfriesenegger could you have a look too?

2024-06-07 12:09 UTC, mfriesenegger commented on doc/source/setuphttpd.rst
>  * uwsgi plugin for python: uwsgi-plugin-python
The package names for the different Linux distros may be different.  Should we list the required packages by Linux distro?

2024-06-07 12:09 UTC, mfriesenegger commented on doc/source/setuphttpd.rst
> +* libapache2-mod-wsgi
The package names for the different Linux distros may be different.  Should we list the required packages by Linux distro?

2024-06-07 12:59 UTC, Bischoff commented on doc/source/setuphttpd.rst
>  * uwsgi plugin for python: uwsgi-plugin-python
This PR is mostly about reorganizing the sections and rewriting the introductory text. Such details will be addressed in a separate PR.

2024-06-07 12:59 UTC, Bischoff commented on doc/source/setuphttpd.rst
> +* libapache2-mod-wsgi
Same. For next PR.

2024-06-07 14:18 UTC, mfriesenegger approved these changes
Thank you for the clarification to my comments.

2024-06-11 02:02 UTC, bjhuangr approved these changes

2024-06-11 02:07 UTC, merged