WIP: Docs: Installation instructions for SLES
openmainframeproject/feilong pull request #829
Opened 2024-06-21 13:36 UTC by aazam-gh

Updated `setuphttpd.rst` to include installation instructions for SLES

2024-06-23 12:33 UTC, Bischoff reviewed
Very good first draft, thank you.

See the remarks. The update to 15.5 is painful, but we need to do it.

2024-06-23 12:33 UTC, Bischoff commented on doc/source/setuphttpd.rst
> +The following instructions are for SLES15 SP4.
According to table above, they are for 15.5.

Can you please update online your target distro to 15.5? I can help you with that if needed.

2024-06-23 12:33 UTC, Bischoff commented on doc/source/setuphttpd.rst
> +The python routes package must be manually installed as a workaround for enabling the webserver to work, it should not be needed in future versions.
Please move the workaround instructions *above* the package installation instructions. Reason is, user needs to apply the workaround first, and then install.

"web server" in two words (?).

2024-07-09 05:47 UTC, bjhuangr commented
@aazam-gh still work in progress?

2024-07-09 08:42 UTC, aazam-gh commented
@bjhuangr Yes, will be ready soon after testing on z/VM

2024-08-08 13:42 UTC, mfriesenegger requested changes

2024-08-08 13:42 UTC, mfriesenegger commented on doc/source/setuphttpd.rst
>  Tested                 RHEL 9.4           SLES 15.5         Ubuntu 24.04
```suggestion
Tested                 RHEL 9.4           SLES 15 SP5         Ubuntu 24.04
```

2024-08-08 13:42 UTC, mfriesenegger commented on doc/source/setuphttpd.rst
> +    # zypper install zvmsdk-<version>-<release>.noarch.rpm
Is this needed because the zypper install command is included in the quickstart section?

2024-08-11 14:02 UTC, Bischoff commented on doc/source/setuphttpd.rst
> +    # zypper install zvmsdk-<version>-<release>.noarch.rpm
I would prefer to duplicate?

2024-08-11 14:08 UTC, Bischoff requested changes
see last remarks

2024-08-11 14:08 UTC, Bischoff commented on doc/source/setuphttpd.rst
> +Apache2 + mod_wsgi     ✓                 ✓
Please use three check marks on this line, we now also do Ubuntu with the mod_wsgi module for Apache

2024-08-11 14:08 UTC, Bischoff commented on doc/source/setuphttpd.rst
>  nginx + uwsgi
Add a check mark in "Ubuntu" column for nginx + uwsgi

2024-08-11 14:08 UTC, Bischoff commented on doc/source/setuphttpd.rst
> +The RPM packages can be downloaded from (to be determined).
please put download URL here (from `Virtualisation:feilong`)

same for RHEL, BTW

please check there are no more `(to be determined)` remarks :smile_cat:

2024-08-11 18:04 UTC, aazam-gh commented on doc/source/setuphttpd.rst
> +Apache2 + mod_wsgi     ✓                 ✓
Sure.

2024-08-11 18:21 UTC, aazam-gh commented on doc/source/setuphttpd.rst
> +The RPM packages can be downloaded from (to be determined).
Done

2024-08-13 09:31 UTC, aazam-gh commented on doc/source/setuphttpd.rst
>  Tested                 RHEL 9.4           SLES 15.5         Ubuntu 24.04
Done

2024-08-13 09:32 UTC, aazam-gh commented on doc/source/setuphttpd.rst
> +Apache2 + mod_wsgi     ✓                 ✓
Done.

2024-08-13 09:32 UTC, aazam-gh commented on doc/source/setuphttpd.rst
>  nginx + uwsgi
Noted.

2024-08-13 09:34 UTC, aazam-gh commented on doc/source/setuphttpd.rst
> +    # zypper install zvmsdk-<version>-<release>.noarch.rpm
For now in the current PR, keep the change as is.
As it is already present in the previous page, rather have the commands about starting/stopping the web server, which can be handled in a new PR.

2024-08-13 10:52 UTC, Bischoff commented on doc/source/setuphttpd.rst
> +    # zypper install zvmsdk-<version>-<release>.noarch.rpm
OK.

By the way, it seems to me that, when you install from packages, apache2 is automatically started, so you don't need instructions to start it in that specific case.

But maybe I'm starting to overthink it.

2024-08-13 11:07 UTC, mfriesenegger commented on doc/source/setuphttpd.rst
> +    # zypper install zvmsdk-<version>-<release>.noarch.rpm
I think you are thinking correctly but it does not hurt to restate that apache2 might need to be restarted.

2024-08-13 13:13 UTC, mfriesenegger commented
@bjhuangr This is ready to be merged.

2024-08-14 01:15 UTC, bjhuangr approved these changes

2024-08-14 01:15 UTC, merged