WIP: Updated quickstart docs to include packaging changes
openmainframeproject/feilong pull request #832
Opened 2024-07-25 22:52 UTC by aazam-gh

Updated the quickstart.rst documentation to improvise and include the changes to use OBS packaging for installation.

2024-07-25 22:53 UTC, aazam-gh commented
@mfriesenegger

2024-07-30 13:45 UTC, mfriesenegger commented on doc/source/quickstart.rst
> +        # dnf install epel-next-release
This step did not work on RHEL 9.1 in L1CC. I suggest removing the commands and generalizing this step. For example:

Add the Extra Packages for Enterprise Linux (EPEL) repo.
Packages in EPEL are dependencies for the feilong packages installation.

2024-07-30 14:32 UTC, aazam-gh commented on doc/source/quickstart.rst
> +        # dnf install zthin zvmsdk
Done. New separate step made.

2024-07-30 16:27 UTC, mfriesenegger commented on doc/source/quickstart.rst
> +        # dnf install epel-next-release
Your change looks good.  Thank you!

2024-07-31 11:53 UTC, mfriesenegger commented
Can you see this comment?

2024-07-31 12:02 UTC, mfriesenegger requested changes

2024-07-31 12:02 UTC, mfriesenegger commented on doc/source/quickstart.rst
> +Installation using OBS Package
```suggestion
Installation using OBS Packages
```

2024-07-31 14:58 UTC, mfriesenegger requested changes

2024-07-31 14:58 UTC, mfriesenegger commented on doc/source/quickstart.rst
> +Installation using OBS Package
@aazam-gh Can you implement this suggestion?

2024-07-31 14:58 UTC, mfriesenegger commented on doc/source/quickstart.rst
> +
```suggestion
@aazam-gh add a step to instruct the reader to skip to the SSH key authentication between consumer and BYOL server section to continue.
```

2024-07-31 14:58 UTC, mfriesenegger commented on doc/source/quickstart.rst
> +
@aazam-gh add a step to instruct the reader to skip to the SSH key authentication between consumer and BYOL server section to continue.

2024-08-01 06:46 UTC, aazam-gh commented
Requested changes have been implemented

2024-08-06 11:19 UTC, Bischoff requested changes
See remarks

2024-08-06 11:19 UTC, Bischoff commented on doc/source/quickstart.rst
> +        # dnf config-manager --add-repo=https://download.opensuse.org/repositories/home:/Aazam:/feilong/AlmaLinux_9/
This needs to move away from your home repo.

Do we already have a project repo?

If not, we might merge first "as is", and fix afterwards

2024-08-06 11:19 UTC, Bischoff commented on doc/source/quickstart.rst
> +1. Add the feilong AlmaLinux repository from OBS
Some people might not be familiar with the meaning of "OBS". I suggest:
```
1. Add the feilong AlmaLinux repository from Open Build Service (OBS)
```

2024-08-06 11:19 UTC, Bischoff commented on doc/source/quickstart.rst
> +    Add the flag `gpgkeycheck=0`to the /etc/yum.repos.d/download.opensuse.org_repositories_home_Aazam_feilong_AlmaLinux_9_.repo file.
Something is wrong with the formatting here. The underlined hyperlink should end up at download.opensuse.org.

Please ignore if this is just an effect of github and the formatting is okay in the generated HTML file.

2024-08-06 11:19 UTC, Bischoff commented on doc/source/quickstart.rst
> +    Make sure you reboot to ensure the changes are reflected and SELinux is disabled.
OK. This might be a serious problem. Some people are freaking out about security and might want to keep SELinux.

Ideally, we should provide a few SELinux policies so Feilong is a good RedHat citizen.

Creating these policies is in my experience difficult and time-consuming, and I'm not sure we have the time, nor that this is high priority enough.

Maybe we could add a sentence like:
```
We are considering writing SELinux policies for Feilong that would enable to not disable
SELinux as a whole.
```
and then let it as an open task for the future.

2024-08-06 11:19 UTC, Bischoff commented on doc/source/quickstart.rst
> +
ok, how?

Maybe give command.

2024-08-06 11:19 UTC, Bischoff commented on doc/source/quickstart.rst
> +2. Add the feilong SUSE repository from OBS
See above

2024-08-06 11:19 UTC, Bischoff commented on doc/source/quickstart.rst
> +   Make sure SELinux is set to disabled mode.
Provide command how to do that.

Also read long discussion on disabling SELinux above.

2024-08-06 11:19 UTC, Bischoff commented on doc/source/quickstart.rst
> +(to be continued)
Are we ready to provide this section, or merge and leave the "to be continued" for now?

2024-08-06 11:19 UTC, Bischoff commented on doc/source/quickstart.rst
> -   If you build server is RHEL8, the build command should be:
It feels so good to be rid of that one :smile:

2024-08-06 11:22 UTC, aazam-gh commented on doc/source/quickstart.rst
> +        # dnf config-manager --add-repo=https://download.opensuse.org/repositories/home:/Aazam:/feilong/AlmaLinux_9/
We had applied for a project repo under the virtualization repo, but no response yet.
 We can merge it as is for now.

2024-08-06 11:25 UTC, aazam-gh commented on doc/source/quickstart.rst
> +    Make sure you reboot to ensure the changes are reflected and SELinux is disabled.
We do not have enough time to consider SELinux  policies and test them. 
Adding to the docs now seems to be the most viable option.

2024-08-06 11:25 UTC, aazam-gh commented on doc/source/quickstart.rst
> +(to be continued)
Separate PR for the debian changes.

2024-08-06 11:28 UTC, aazam-gh commented on doc/source/quickstart.rst
> +    Add the flag `gpgkeycheck=0`to the /etc/yum.repos.d/download.opensuse.org_repositories_home_Aazam_feilong_AlmaLinux_9_.repo file.
Will check the generated file again to be certain.

2024-08-06 11:28 UTC, aazam-gh commented on doc/source/quickstart.rst
> +1. Add the feilong AlmaLinux repository from OBS
We have it initially explained here 
https://github.com/openmainframeproject/feilong/pull/832#discussion_r1697273155

2024-08-06 11:30 UTC, aazam-gh commented on doc/source/quickstart.rst
> +
Discussed with Mike to not include the command as we would have to then add for each (Alma/Rocky/RHEL)

2024-08-06 14:41 UTC, Bischoff commented on doc/source/quickstart.rst
> +        # dnf config-manager --add-repo=https://download.opensuse.org/repositories/home:/Aazam:/feilong/AlmaLinux_9/
Now we know the final location, and you may change `home:/Aazam:` to `Virtualization:/feilong:`.

2024-08-06 14:42 UTC, Bischoff commented on doc/source/quickstart.rst
> +1. Add the feilong AlmaLinux repository from OBS
Perfect, then please ignore.

2024-08-06 14:43 UTC, Bischoff commented on doc/source/quickstart.rst
> +
OK.

2024-08-06 14:44 UTC, Bischoff commented on doc/source/quickstart.rst
> +(to be continued)
Works for me.

2024-08-07 11:46 UTC, aazam-gh commented on doc/source/quickstart.rst
> +2. Add the feilong SUSE repository from OBS
It has been added

2024-08-07 11:46 UTC, closed without merging

2024-08-07 11:51 UTC, aazam-gh commented on doc/source/quickstart.rst
> +   Make sure SELinux is set to disabled mode.
Done

2024-08-07 13:43 UTC, aazam-gh commented
PR closed accidentally, new PR here https://github.com/openmainframeproject/feilong/pull/835