Docs: Updated quickstart with OBS Package install for RPM and SLES
openmainframeproject/feilong pull request #835
Opened 2024-08-07 13:43 UTC by aazam-gh

Updated `quickstart.rst`

PR forwarded from https://github.com/openmainframeproject/feilong/pull/832

2024-08-07 13:50 UTC, Bischoff requested changes
see nitpick

2024-08-07 13:50 UTC, Bischoff commented on doc/source/quickstart.rst
> +    Add the flag `gpgkeycheck=0`to the /etc/yum.repos.d/download.opensuse.org_repositories_Virtualization_feilong_AlmaLinux_9_.repo file.
formatting problem here (the hyperlink)

please ignore if doc generation does not have the problem (ie if it's only a problem with github's rendering)

2024-08-07 13:53 UTC, Bischoff commented on doc/source/quickstart.rst
> +        # zypper ar https://download.opensuse.org/repositories/Virtualization:/feilong/15.5/ feilong
I think it's called "SLE_15_SP5" now instead of "15.5"

please check the link.

2024-08-08 11:40 UTC, aazam-gh commented on doc/source/quickstart.rst
> +    We are considering writing SELinux policies for Feilong that would enable to not disable SELinux as a whole.
The line after the sub heading? It is the same format as the rest

2024-08-08 11:40 UTC, aazam-gh commented on doc/source/quickstart.rst
> +        # zypper ar https://download.opensuse.org/repositories/Virtualization:/feilong/15.5/ feilong
done

2024-08-08 13:13 UTC, Bischoff commented on doc/source/quickstart.rst
> +    We are considering writing SELinux policies for Feilong that would enable to not disable SELinux as a whole.
I was suggesting to add a blank line before "We are considering writing"

2024-08-08 13:16 UTC, Bischoff commented on doc/source/quickstart.rst
> +   We are considering writing SELinux policies for Feilong that would enable to not disable SELinux as a whole.
? I think you can remove this whole paragraph. By default, SLES uses apparmor, not SELinux.

(unless you have seen SELinux on SLES on linux 1 VM?)

2024-08-08 13:29 UTC, mfriesenegger approved these changes
I will create an issue for a future effort to fix the manual installation section.

2024-08-11 17:50 UTC, aazam-gh commented on doc/source/quickstart.rst
> +   We are considering writing SELinux policies for Feilong that would enable to not disable SELinux as a whole.
Yes SLES indeed uses apparmor on L1CC as well. Removing the entire paragraph

2024-08-12 09:07 UTC, Bischoff commented on doc/source/quickstart.rst
> -
Instead of removing paragraph 1, say we now have packages, maybe?

2024-08-12 09:08 UTC, Bischoff commented on doc/source/quickstart.rst
> -
or this is done above? i'm getting a bit lost

2024-08-12 09:53 UTC, Bischoff commented on doc/source/quickstart.rst
> +(to be continued)
this could be updated now?

2024-08-12 09:54 UTC, Bischoff commented on doc/source/quickstart.rst
> +(to be continued)
or separate PR

2024-08-12 12:01 UTC, mfriesenegger commented on doc/source/quickstart.rst
> -
> Instead of removing paragraph 1, say we now have packages, maybe?

I am OK with removing these lines versus repeating a statement that packages exist.  The `Installation using OBS Packages` section is before the `Manual Installation` so a reader hopefully will have seen that packages exist.

2024-08-12 13:53 UTC, Bischoff commented on doc/source/quickstart.rst
> -
Fine :) 

Then please ignore Aazam.

2024-08-12 13:54 UTC, Bischoff commented on doc/source/quickstart.rst
> +(to be continued)
then please ignore Aazam.

2024-08-13 09:06 UTC, aazam-gh commented on doc/source/quickstart.rst
> +    We are considering writing SELinux policies for Feilong that would enable to not disable SELinux as a whole.
Done

2024-08-13 09:06 UTC, aazam-gh commented on doc/source/quickstart.rst
> -
Okay

2024-08-13 09:07 UTC, aazam-gh commented on doc/source/quickstart.rst
> +(to be continued)
Seperate PR.

2024-08-13 09:09 UTC, aazam-gh commented
Changes have been done. Ready for Merge :)

2024-08-13 11:05 UTC, mfriesenegger requested changes

2024-08-13 11:05 UTC, mfriesenegger commented on doc/source/quickstart.rst
> +Debian for Ubuntu
```suggestion
DEB for Ubuntu
```

2024-08-13 11:05 UTC, mfriesenegger commented on doc/source/quickstart.rst
> +Debian for Ubuntu
I think "DEB" could be all lowercase but I am suggesting all uppercase like has been done with RPM for RH and SLES.

2024-08-13 13:15 UTC, mfriesenegger commented
@bjhuangr This is ready to be merged.

2024-08-14 01:16 UTC, bjhuangr approved these changes

2024-08-14 01:17 UTC, merged