WIP:Updated Installation Docs for Deb Packaging
openmainframeproject/feilong pull request #837
Opened 2024-08-14 17:54 UTC by aazam-gh

Updated `quickstart.rst`

2024-08-15 02:02 UTC, mfriesenegger requested changes
I know that you will be adding more but I thought I would review what you have already done.  Good job!

2024-08-15 12:32 UTC, Bischoff commented on doc/source/quickstart.rst
> +compute server，please make ensure you can ssh nova@nova-compute-ip without
Same, I know it's not finished, but:

Feilong can work independently of IBM Cloud Infrastructure Center (ICIC, based on openstack).

Therefore I would prefer to remove all references to a "nova compute server" and call it "BYOL server" or "Feilong server".

2024-08-15 12:35 UTC, Bischoff commented on doc/source/quickstart.rst
> +compute server，please make ensure you can ssh nova@nova-compute-ip without
You may also be considering that you're just moving this block of text, and that it's not your problem.

2024-08-19 08:04 UTC, aazam-gh commented on doc/source/quickstart.rst
> +compute server，please make ensure you can ssh nova@nova-compute-ip without
This has been added to the parking lot notes for future changes.

2024-08-19 13:09 UTC, mfriesenegger requested changes

2024-08-19 13:11 UTC, Bischoff requested changes
see nitpicks

2024-08-19 13:11 UTC, Bischoff commented on doc/source/quickstart.rst
>     rpm name.
"the package name" instead of "your own rpm name" or "your own deb name"?

2024-08-19 13:11 UTC, Bischoff commented on doc/source/quickstart.rst
> +   Be sure to replace the *zthin-3.1.2.s390x.deb* with your own deb name.
Same, "the package name" instead of "your own rpm name" or "your own deb name"?

2024-08-19 13:11 UTC, Bischoff commented on doc/source/quickstart.rst
> +   Be sure to replace the *zvmsdk-1.4.0-snap201710300123.s390x.rpm* with your own
"the package name" instead of "your own rpm name" or "your own deb name"?

2024-08-19 13:11 UTC, Bischoff commented on doc/source/quickstart.rst
> +   Be sure to replace the *zvmsdk-1.4.0.s390x.deb* with your own deb name.
"the package name" instead of "your own rpm name" or "your own deb name"?

2024-08-19 13:11 UTC, Bischoff commented on doc/source/quickstart.rst
> +   sdk_fcp database with type **`varchar(16)`**, which located at
which is located

2024-08-19 13:11 UTC, Bischoff commented on doc/source/quickstart.rst
> +zvmsdk: is running user of the BYOL server.
is the user on the BYOL server that is used to run the z/VM SDK.

2024-08-19 13:11 UTC, Bischoff commented on doc/source/quickstart.rst
>     If this build finishes successfully, the result rpm will be generated
resulting rpm package

2024-08-19 13:11 UTC, Bischoff commented on doc/source/quickstart.rst
> +    If the build finishes successfully, the resulting deb will be generated
resulting deb package

2024-08-19 13:11 UTC, Bischoff commented on doc/source/quickstart.rst
> +   If this build finishes successfully, the result rpm will be generated
same, resulting rpm package

2024-08-19 13:11 UTC, Bischoff commented on doc/source/quickstart.rst
> +   If the build finishes successfully, the resulting deb will be generated
same, resulting deb package

2024-08-19 13:11 UTC, Bischoff commented on doc/source/quickstart.rst
> +authorized by the user of the consumer (eg nova-compute) if they are not in
needs to be authorized

2024-08-19 13:14 UTC, Bischoff commented on doc/source/quickstart.rst
> +compute server，please make ensure you can ssh nova@nova-compute-ip without
ok

2024-08-26 10:06 UTC, aazam-gh commented on doc/source/quickstart.rst
> +    Add the flag `gpgkeycheck=0` to the /etc/yum.repos.d/download.opensuse.org_repositories_Virtualization_feilong_AlmaLinux_9_.repo file.
Done

2024-08-26 10:09 UTC, aazam-gh commented on doc/source/quickstart.rst
>     rpm name.
Done

2024-08-26 10:10 UTC, aazam-gh commented on doc/source/quickstart.rst
> +   Be sure to replace the *zthin-3.1.2.s390x.deb* with your own deb name.
Done

2024-08-26 10:10 UTC, aazam-gh commented on doc/source/quickstart.rst
> +   Be sure to replace the *zvmsdk-1.4.0-snap201710300123.s390x.rpm* with your own
Done

2024-08-26 10:10 UTC, aazam-gh commented on doc/source/quickstart.rst
> +   Be sure to replace the *zvmsdk-1.4.0.s390x.deb* with your own deb name.
Done

2024-08-26 10:13 UTC, aazam-gh commented on doc/source/quickstart.rst
>     If this build finishes successfully, the result rpm will be generated
Done

2024-08-26 10:13 UTC, aazam-gh commented on doc/source/quickstart.rst
> +zvmsdk: is running user of the BYOL server.
Done

2024-08-26 10:13 UTC, aazam-gh commented on doc/source/quickstart.rst
> +    If the build finishes successfully, the resulting deb will be generated
Done

2024-08-26 10:14 UTC, aazam-gh commented on doc/source/quickstart.rst
> +   If this build finishes successfully, the result rpm will be generated
Done

2024-08-26 10:14 UTC, aazam-gh commented on doc/source/quickstart.rst
> +   If the build finishes successfully, the resulting deb will be generated
Done

2024-08-26 10:15 UTC, aazam-gh commented on doc/source/quickstart.rst
> +authorized by the user of the consumer (eg nova-compute) if they are not in
Done

2024-08-26 10:17 UTC, aazam-gh commented on doc/source/quickstart.rst
> +   *zvmsdk-version-snapdate.s390x.rpm* where *version* is the zvmsdk version
Corrected the change as it is visible only in building the rpm and not the debian.

2024-11-13 03:48 UTC, mfriesenegger approved these changes

2024-11-13 03:49 UTC, merged