WIP: Docs: Update webserver setup instructions
openmainframeproject/feilong pull request #838
Opened 2024-08-15 09:02 UTC by aazam-gh

Updated `setuphttpd.rst`

2024-08-19 12:51 UTC, Bischoff requested changes
minor nitpicks

2024-08-19 12:51 UTC, Bischoff commented on doc/source/setuphttpd.rst
> +The following instructions are for RHEL 9.4
I'd rather keep this end of sentence dot.

2024-08-19 12:51 UTC, Bischoff commented on doc/source/setuphttpd.rst
> -Before installing the necessary packages, it is important to set up the EPEL repository.
add a final dot at end of sentence.

2024-08-26 10:20 UTC, aazam-gh commented on doc/source/setuphttpd.rst
> -Before installing the necessary packages, it is important to set up the EPEL repository.
Would it not confuse the readers with entering a dot at the end of the link?

2024-08-26 11:19 UTC, Bischoff approved these changes
lgtm

2024-08-26 11:19 UTC, Bischoff commented on doc/source/setuphttpd.rst
> -Before installing the necessary packages, it is important to set up the EPEL repository.
It depends on how it is rendered by the rst-to-html conversion.

What I usually do in such cases, to avoid such confusions, is to add as pace before the dot. Not ideal, but it separates the link and the punctuation.

2024-08-28 18:45 UTC, aazam-gh commented
Ready to merge

2024-11-13 03:50 UTC, merged