Doc: FCP templates API calls and other fixes
openmainframeproject/feilong pull request #843
Opened 2024-11-17 14:31 UTC by Bischoff

Documentation fixes

1) Move method to vswitch section

 * Get vswitch info

2) Fix typography and English

3) Fix parameters of existing volume functions

 * Refresh volume bootstrap info
 * Get volume connector
 * Attach volume
 * Detach volume
 * Get FCP usage
 * Set FCP usage

4) Add FCP templates API calls

 * Create FCP template
 * Delete FCP template
 * Get FCP templates
 * Edit FCP template
 * Get FCP templates details

5) Remove unused parameters

Fixes #772

2025-02-03 01:36 UTC, mfriesenegger requested changes
Thank you for the great work on this!  I used the `tox -e docs` command that you shared with me to generate a readable local copy for myself.  I have pointed out a number of items that should be updated before merging this PR.

2025-02-03 01:36 UTC, mfriesenegger commented on doc/source/parameters.yaml
> +    Operating system version. The valid alues are: ``rhel6.x``,
```suggestion
    Operating system version. The valid values are: ``rhel6.x``,
```

2025-02-03 01:36 UTC, mfriesenegger commented on doc/source/parameters.yaml
> +    Operating system version. The valid alues are: ``rhel6.x``,
I think this should be changed in multiple places.

2025-02-03 01:39 UTC, mfriesenegger commented
I will take your word that this fixes https://github.com/openmainframeproject/feilong/issues/772.  Please help me to remember to close issue #772 when this PR is merged!

2025-02-04 14:17 UTC, Bischoff commented on doc/source/parameters.yaml
> +    types of location\:
done

2025-02-04 14:18 UTC, Bischoff commented on doc/source/parameters.yaml
> +    Maximal version of Feilong.
done

2025-02-04 14:19 UTC, Bischoff commented on doc/source/parameters.yaml
> +    How the image is generated, if it captured from root disk the
done

2025-02-04 14:20 UTC, Bischoff commented on doc/source/parameters.yaml
> +    Operating system version. The valid alues are: ``rhel6.x``,
Done, but I only found this occurrence.

2025-02-04 14:28 UTC, Bischoff commented
Suggestions applied, please review again.

2025-02-04 14:29 UTC, Bischoff commented
> I will take your word that this fixes #772. Please help me to remember to close issue #772 when this PR is merged!

@dongyanyang wrote in that issue: "The doc of CRUD of fcp_template and the attach_volume/detach_volume APIs are missing, need to add them."

The doc was not completely "missing", but needed a whole lot of work to match the API. I do not see what I might have missed, but one never knows. I suggest that we close #772, and detect a missing doc piece, we reopen a new issue.

2025-02-09 12:48 UTC, mfriesenegger approved these changes

2025-02-09 12:49 UTC, mfriesenegger commented
@Bischoff Thank you for all of your work on this PR!

2025-02-09 12:49 UTC, merged